### ISSUE TITLE
Redis::TimeoutError with Resque

### ISSUE THREAD

**Issue by JohnBat26** [resque/resque#1018]
Hi all.
I use last redis-rb 3.0.4 driver with last resque-1.24.1.
All work exccellent.
But, after ~ 12 hours when application don't used (for example, after night), appears errors: Redis::TimeoutError.

I init connection this way:
Resque.redis = 'remote_server:6379'

I have used timeout option (10s) but this don't help me :(.
When in application appear Redis::TimeoutError-s, in redis-cli connection work normally.
So, network problem is absent. + with mongodb that exists at the same server with redis this problem absents.

**Comment by jwg2s** [comment]
@mmzoo, we're suffering from the same issue.  What was your network error?  Maybe we have the same problem.

**Comment by mmzoo** [comment]
Our network error is called EC2 :) It turns out that, across all applications and all servers, connections to the redis server time out again and again. It does not appear resque-specific at the moment. What's strange is that the Redis `SLOWLOG` never complains about anything. Oh well :)

**Comment by jwg2s** [comment]
How were you able to resolve?  Is it possible to specify a timeout in the redis connection?  I've been searching but haven't found an example.

**Comment by mmzoo** [comment]
We have not resolved it. We're using a [custom built wrapper](https://github.com/bukowskis/raidis) which automatically reconnects on timeouts. In practice, the timeouts we experience have not caused any trouble. At least not anything we would know about.

As for the timeout, `Redis.new` takes a  `:timeout` option [as we use it here](https://github.com/bukowskis/raidis/blob/de32ce755aa830b22a7c4fbd6da51effd6230aae/lib/raidis/redis_wrapper.rb#L103). The original `redis-rb` has that [configuration here](https://github.com/redis/redis-rb/blob/3c0668c9b04300338ba81b15bc01dae360b407fe/lib/redis/client.rb#L14). The default is 5 seconds, we use 3 seconds in our environment.

**Comment by steveklabnik** [comment]
Could anyone help me get a clean reproduction of this issue?

**Comment by JohnBat26** [comment]
Hello, Steve! 
This situation emerges when system has idle time about hour and more time. Is this case, router cleans routing table, and connection leaves in indefinite state.
In other words, the less we use system, the more probability appears of this problem.
I suppose, we need simply do reconnect, when catch this error.

P.S. This situation more particularly describes in this book: Release it!

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!

**Comment by sasaya-loilo** [comment]
Hello.
I encountered a similar problem; worker processes died due to Redis::TimeoutError. It'd be nice if resque keeps running instead of dying on redis timeouts.

If you want to reproduce Redis::TimeoutError, you could just suspend the redis server by pressing Ctrl-Z.
