### ISSUE TITLE
Travis: "blocks on pop" legacy tests are flaky

### ISSUE THREAD

**Issue by jacobo** [resque/resque#1034]
A compilation of test runs that never completed in travis due to some sort of deadlock issues?

https://travis-ci.org/resque/resque/builds/7712492
https://travis-ci.org/resque/resque/builds/7209606
https://travis-ci.org/resque/resque/builds/7209456
https://travis-ci.org/resque/resque/builds/7204972
https://travis-ci.org/resque/resque/builds/7204293
https://travis-ci.org/resque/resque/builds/7177587
https://travis-ci.org/resque/resque/builds/7065903
https://travis-ci.org/resque/resque/builds/7046607

These have output showing which tests may be at fault:

https://travis-ci.org/resque/resque/jobs/7204295
https://travis-ci.org/resque/resque/jobs/7204295

and attempts to force-reproduce:

https://travis-ci.org/resque/resque/jobs/7204976
https://travis-ci.org/resque/resque/jobs/7209457
https://travis-ci.org/resque/resque/jobs/7209460

**Comment by Jacobkg** [comment]
@steveklabnik From what I can see the 1-x-stable test suite seems to be pretty solid. Is there something here still to do?

**Comment by steveklabnik** [comment]
Yes, let's close this. If we find specific tests being flaky, we can fix them, but I'm not sure it's worth keeping open.
