### ISSUE TITLE
Resque stays on 'starting' state when BACKGROUND=yes

### ISSUE THREAD

**Issue by gamafranco** [resque/resque#1035]
Hi.

When I run resque with BACKGROUND=yes, the process stays on the state 'starting'. It doesn't change to the state 'wating'

If I execute resque on the foreground, resque runs OK.

I'm having this issue with Ubuntu 12.04 - kernel 3.2.0-45-generic, with resque 1.24.1. Rails 3.2.11.

Thanks.

**Comment by steveklabnik** [comment]
@gamafranco are you still having this problem? Can you help me reproduce it?

**Comment by gamafranco** [comment]
Hi @steveklabnik, I don't think this is applicable anymore. Closing for now.
