### ISSUE TITLE
Backwards pagination

### ISSUE THREAD

**Issue by maletor** [resque/resque#1044]
Any ideas what contributes to this?

![screen shot 2013-06-14 at 4 22 09 pm](https://f.cloud.github.com/assets/138785/657291/487f5d50-d549-11e2-8fed-3748440ebe74.png)

**Comment by steveklabnik** [comment]
@maletor can you help me reproduce this?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
