### ISSUE TITLE
A strange resque process write file problem

### ISSUE THREAD

**Issue by grantchen** [resque/resque#1052]
I have a strange problem.

A resque process are manged by monit always runing like below.
```bash
$  ps -ef | grep resque
grant   5868     1  0 15:02 ?        00:00:00 /bin/sh -l -c . /etc/environment && cd /home/grant/test/current; nohup bundle exec rake environment resque:work RAILS_ENV=production QUEUE=* VERBOSE=1 PIDFILE=tmp/pids/resque-worker.pid
grant   5871  5868  0 15:02 ?        00:00:28 resque-1.24.1: Waiting for *
```

but when this process write a file(same user group with process user).
It cause Permission denied error.

```bash
$ ls -l test.txt
-rw-rw-r-- 1 alex alex 21931 Jun 25 16:46 text.txt

$ groups grant
grant : admin alex grant
 
```

**Comment by steveklabnik** [comment]
Any way that you can help me reproduce this?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
