### ISSUE TITLE
Workers hang on job that doesn't exist

### ISSUE THREAD

**Issue by barmstrong** [resque/resque#1079]
We had some jobs scheduled in the future (using `resque-scheduler`) that we no longer need.  We removed the class from our `app/jobs` folder.

Now as they start to run the worker just hangs on them (instead of throwing an error or moving past it somehow).

Has anyone seen this or can you think of any potential solutions?  For now we've had to add the job back temporarily, as all the workers are tied up and it took down the rest of the site.

    gem 'resque',                        '1.24.1'
    gem 'resque_mailer',                 '2.2.1'
    gem 'resque-scheduler',              '2.0.0', require: 'resque_scheduler'
    gem 'resque-failed-job-mailer',      '0.0.1', require: 'resque_failed_job_mailer'
    gem 'resque-retry',                  '1.0.0'

**Comment by steveklabnik** [comment]
Closing due to previous comments about duplicates and new releases. let me know if this is still an issue.
