### ISSUE TITLE
Rails 4 removed ActiveRecord::Base#verify_active_connections!

### ISSUE THREAD

**Issue by codyrobbins** [resque/resque#1098]
The [FAQ](https://github.com/resque/resque/wiki/FAQ#how-do-you-work-around-the-mysql-server-has-gone-away-error-) still indicates that `ActiveRecord::Base#verify_active_connections!` is the way to work around the “MySQL server has gone away” error, but that method was removed from Rails 4 in rails/rails@9d1f1b1. The commit says that `verify_active_connections!` is obsolete and that Rails does it a “different way” now, but there’s no mention of what that way is.

I’ve been using [socialcast/resque-ensure-connected](https://github.com/socialcast/resque-ensure-connected) to work around this problem automatically, but it hasn’t been updated. (See socialcast/resque-ensure-connected#3.)

Does anyone know what the FAQ should be updated with in order to work around this issue with Rails 4?

**Comment by chrisccerami** [comment]
I've updated this section of the Wiki with the relevant information for Rails 4. Should this also be updated in the Readme?

**Comment by steveklabnik** [comment]
Yes, that'd be great.

**Comment by steveklabnik** [comment]
This should be fixed now. Thanks everyone!
