### ISSUE TITLE
Resque::Server UI and NewRelic

### ISSUE THREAD

**Issue by jmif** [resque/resque#1104]
NewRelic is reporting my request metrics from the Resque::Server UI.  It's not the end of the world, but I would be nice have them filtered out.

I did some research on this, and attempted to do it myself but everything I tried ended up with nothing but NoMethodErrors when trying to call newrelic_ignore (no Sinatra experience).

https://newrelic.com/docs/ruby/sinatra-support-in-the-ruby-agent

Looks like we should be able to call newrelic_ignore, perhaps after first checking if NewRelic is defined?

**Comment by steveklabnik** [comment]
I am going to give this a close, as I have no idea how to reproduce it. @jmif if you happen to know of a way, please let me know.

**Comment by chrisccerami** [comment]
Is this still an issue? Is there a reproduction or has @lauradiane's solution solved your problem? @jmif
