### ISSUE TITLE
can not run sudo in a  worker

### ISSUE THREAD

**Issue by grantchen** [resque/resque#1158]
I have a  worker which need run some shell command.

for example

```ruby
`sudo echo "XXX" >> xx.log`
```

but when worker call this, will raise below error

```
sudo: no tty present and no askpass program specified
```

I have add 'whoami' debug code to find which user run this sudo command,
and also set this user's group "test" who execute command will don't need password.

I'm also test same command in shell console, it works right, don't need input password.

sudo visudo

```
%test ALL=NOPASSWD:ALL
```

but when the worker run sudo, will says above error, require input password.

Who can tell me why? How to resolve it.

Thanks.

**Comment by steveklabnik** [comment]
Since this is not a bug in Resque, I'm giving it a close.
