### ISSUE TITLE
Tempfiles created by a resque worker are not deleted

### ISSUE THREAD

**Issue by such** [resque/resque#1167]
Hello,
I'm copying here [this](http://stackoverflow.com/questions/21097172/tempfiles-created-by-a-resque-worker-are-not-deleted) question I asked on StackOverflow 

I tested this simple job, executed by a plain resque worker.

    require 'tempfile'

    class Jobs::TestTempfile
      @queue = :test

      def self.perform
        Tempfile.open('foo') do |f|
           puts f.path
        end
      end
    end

The temporary file created remains after the end of the job and even once the worker has been terminated (kill -QUIT pid).

I am aware the best practice is to unlink and close all Tempfiles but this seems like an issue anyway... Is anyone aware of some global solution to this? Or do I have to go through all the existing jobs to manually unlink Tempfiles.

I tested with ruby 2.1 (but I'm positive the issue existed with 2.0) and resque 1.24.1.

Thanks!

**Comment by steveklabnik** [comment]
Giving this a close as "not a bug", it seems.
