### ISSUE TITLE
resque v1.25.x breaks semantic versioning

### ISSUE THREAD

**Issue by crankharder** [resque/resque#1168]
In 1.25.x various warnings were introduced to note that Helpers will be disappearing in 2.0.0.  With the same release, Resque, Job and Worker stopped including and/or extending Helpers.

http://semver.org/

Since the methods that were included were public, this breaks the expected functionality of Resque - in a minor version release.

This can, and has, broken certain plugins.

**Comment by steveklabnik** [comment]
I vaguely remember fixing this, but if I didn't, it should be fixed.

**Comment by Jacobkg** [comment]
The referenced PR https://github.com/resque/resque/pull/1169/files was merged in November so maybe this issue is resolved. Thoughts @crankharder?

**Comment by chrisccerami** [comment]
Seems like this should be closed then for now? Can always be reopened if need be, but seems like it's fixed.

**Comment by steveklabnik** [comment]
yes, please let me know if this is still an issue, but it should have been addressed.
