### ISSUE TITLE
Resque 2.0 Release Date?

### ISSUE THREAD

**Issue by jaredonline** [resque/resque#1170]
Would it be worthwhile to peg a release date for Resque 2.0? That'll help us to get a set of goals that can be accomplished by that date and move everything else out to Resque 2.1.

**Comment by goooooouwa** [comment]
It seems Resque 2.0 is cancelled. The `2.0.0` branch is replaced by `two-oh-is-cancelled`. And the PR https://github.com/resque/resque/pull/1352 doing this is not found. I didn't find any announcement.

**Comment by steveklabnik** [comment]
Yup.
