### ISSUE TITLE
undefined method `new' for Resque:Module

### ISSUE THREAD

**Issue by wlodi83** [resque/resque#1175]
Hi,

I am using Rails 4.0.2 and ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]

I have installed Resque::VERSION => "2.0.0.pre.1"

However when I try Resque.new in the console I am getting an error:   undefined method `new' for Resque:Module

Could you let me know how to fix it?

**Comment by luca3m** [comment]
some issue of @gmalkas Readme needs an update probably

**Comment by eltonokada** [comment]
So, how should i send a job to the queue?

**Comment by eavgerinos** [comment]
`Resque` is still a module and will be converted to a class in 2.0.0.

Documentation in master branch does not represent anything but a specification for the new version.

**Comment by AshtonKem** [comment]
For the record, this is incredibly frustrating for end users, as it 
isn't called out clearly enough on the master's README. As a result the 
documentation feels downright duplicitous.

**Comment by eltonokada** [comment]
So, i think you should write this on the README, as i lost a few hours with this new version, and in the end i will use the 1.x version of resque.

**Comment by sepastian** [comment]
Yes, please update the README!

It took me hours and lots of frustration to figure out that Resque 2.0 is not ready yet...

**Comment by anagri** [comment]
WTF ?

Can someone just update the README to not show how to integrate v2-pre rather point to v1 ? 

Is anyone even maintaining the code ?

**Comment by jeremywadsack** [comment]
Doesn't it already have that? https://github.com/resque/resque#a-note-about-branches

**Comment by AshtonKem** [comment]
I think no matter what it's a bad idea to have purposefully wrong documentation on the master README. 

--
Ashton

**Comment by hoffmanc** [comment]
Why wouldn't 2.0 be a branch instead of master?  That is the git workflow
I'm used to seeing (i.e., master is always deployable after CI passes -
feature branches don't get merged in until we are ready to deploy them to
production).

**Comment by leikind** [comment]
When you follow installation instructions on a github page and it does not work because the README does not correspond to the code, this is extremely frustrating. Do you expect every user to find your "Not about branches" and switch the branch? Unbelievable. 

If this is a development branch, fine. Just change the default branch to show on opening https://github.com/resque/resque  to something else then.

**Comment by ggharry** [comment]
Please make README reflect a **stable** version.

**Comment by cdrage** [comment]
Readme has been updated :) Let's close these issues? See #976

**Comment by steveklabnik** [comment]
Yup!
