### ISSUE TITLE
Redis::CommandError: ERR max number of clients reached

### ISSUE THREAD

**Issue by stabenfeldt** [resque/resque#1226]
I get this exception when I do **Retry all**.
I've searched for concurrency but could not find any information on how to get Resque to reduce the number of connections.
Is there a way I can tell Resque to only make 1 connection to the redis-server?
I only got 1 worker running.

Best,
Martin

**Comment by pengfei-xue** [comment]
this works for me

`$ redis-cli 
> CLIENT LIST
> CLIENT KILL nn.nn.nn.nn:nnnnn`
