### ISSUE TITLE
resque web broken with multiple failure queues

### ISSUE THREAD

**Issue by irenemachine** [resque/resque#1230]
I set the environment variable FAILURE_BACKEND to 'redis_multi_queue'.  The failed jobs are placed into the appropriate failure queue.  The failure queues and job count are accurately listed on the overview page.  However, navigating to /resque/failed or /resque/failed/queue_name_failed result in:

ArgumentError at /resque/failed
wrong number of arguments (4 for 3)
file: resque.rb location: list_range line: 247

This is with both v1.25.2 and branch release/1.26.0.

**Comment by thesmart** [comment]
This is still an issue in the resque web as of 1.25.2

**Comment by omarqureshi** [comment]
Indeed, this is still an issue - could #1234 be looked at?

**Comment by steveklabnik** [comment]
I'm getting #1234 merged in https://github.com/resque/resque/pull/1374 and this will be fixed in 1.26.0.
