### ISSUE TITLE
"rake resque:workers" is not documented

### ISSUE THREAD

**Issue by wonnage** [resque/resque#1253]
If you don't pass an environment variable, it just exits immediately. And it's not on the FAQ or anything.

**Comment by Jacobkg** [comment]
@steveklabnik There are a couple problems here. The first is that this commit broke the `abort` error message which explained which environment variables to set: https://github.com/resque/resque/commit/7d0b20ee00986b749b03d4407af199039b504cc2

The second is that if you don't set `COUNT` in `rake resque:workers` then we don't enter the loop that starts threads so no other checks are started.

I can create separate pull requests for each of these

**Comment by steveklabnik** [comment]
@Jacobkg that'd be great! I just merged the first one.

**Comment by steveklabnik** [comment]
With these two PRs merged, I believe this is now fixed :confetti_ball:
