### ISSUE TITLE
Can't bundle install resque 1.25.2 with ruby 2.1.2, OSX 10.9.4

### ISSUE THREAD

**Issue by timruffles** [resque/resque#1256]
```
ƒ bundle install
...
Bundler::GemspecError: Could not read gem at /Users/dev/app/vendor/ruby/2.1.0/cache/resque-1.25.2.gem. It may be corrupted.
An error occurred while installing resque (1.25.2), and Bundler cannot continue.
Make sure that `gem install resque -v '1.25.2'` succeeds before bundling.
```

I have to install via `gem install resque -v '1.25.2'`, and then re-enable shared gems (really not ideal) for this to work.

**Comment by steveklabnik** [comment]
This seems both unfortunate and really hard for me to reproduce :(

shared gems? What tool are you using to manage Ruby?

**Comment by timruffles** [comment]
`rvm`. By shared gems I mean I'd disabled global gems, and was having bundler install in a project-local folder.

Thanks for looking at such an old ticket!

**Comment by steveklabnik** [comment]
I can't reproduce this bug. :( Until we can find some sort of clean-room way to do so, I can't really help, so I'm going to give this a close. Sorry :(
