### ISSUE TITLE
[2.0] Problems with `Resque.redis=` vs. `Resque::Config#redis=`

### ISSUE THREAD

**Issue by davidcelis** [resque/resque#1258]
Hey guys; I just found this problem while investigating davidcelis/recommendable#98. There are discrepancies between assigning a Redis client in the two main ways it provides.

First, there is this pattern:

```ruby
Resque.configure do |config|
  config.redis = 'redis://localhost:6379'
end
```

This merely assigns the `redis` attribute on Resque's config object. However, then there's `Resque.redis=`...

```ruby
Resque.redis = 'redis://localhost:6379'
```

This passes through to `config.redis = ...` and _also_ initializes Resque's `@backend` and `@queues` ivars. What this means is that if somebody uses the configuration pattern (which I would expect to be the _main_ pattern to assign a Redis instance), those ivars never get assigned. The problem in davidcelis/recommendable#98 was specifically that `@queues` was nil, which would cause problems when trying to enqueue a Resque job.

I'd like to submit a patch for this, but wanted to check in on the desired approach. IMO Resque should by default try to connect to Redis on localhost:6379 by default (maybe it already is?) and those ivars should probably be initialized elsewhere (or both from `Resque.redis=` and `Resque.configure { ... }`.

**Comment by dfockler** [comment]
@davidcelis When you do `Resque.redis = Redis.new` it will set the defaults to `redis://127.0.0.1:6379`, I think `configure` was meant more for if you weren't going to use Redis as the backend or if you needed something other than `Hash`

**Comment by steveklabnik** [comment]
As 2.0 is no longer happening, this can now be closed.
