### ISSUE TITLE
Can't bundle install resque 1.25.2 with redis 3.1.0 in linux environment.

### ISSUE THREAD

**Issue by shubhamdotror** [resque/resque#1260]
When I try to run bundle install with redis 3.1.0 and resque 1,25,2, I get the following error.

Bundler could not find compatible versions for gem "redis":
  In Gemfile:
    resque (>= 0) ruby depends on
      redis (~> 3.0.4) ruby

    redis (3.1.0)

**Comment by lukeasrodgers** [comment]
@shubhamdotror try upgrading redis-namespace. Since https://github.com/resque/redis-namespace/commit/3df9d3d0c82366fe8827c02f1638f936c8cba92e#diff-b7c45dab652c3b1dceb8b56c134258e2, the redis dependency has been relaxed.

**Comment by steveklabnik** [comment]
I'm assuming this has been fixed, let me know otherwise.
