### ISSUE TITLE
undefine method require_dependency Rails 4.1.4. Resque 1.25.2

### ISSUE THREAD

**Issue by ghost** [resque/resque#1265]
Would you mind give answer please what's this https://github.com/resque/resque/blob/master/lib/resque/tasks.rb#L6  

I had error when running a worker

``` bash
rake resque:work QUEUE='*'
rake aborted!
NoMethodError: undefined method 'require_dependency' for #<AppName::Application:0x00000005073cd0>
/home/user/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.1.4/lib/rails/engine.rb:468:in 'block (2 levels) in eager_load!'
/home/user/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.1.4/lib/rails/engine.rb:467:in 'each'
/home/user/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.1.4/lib/rails/engine.rb:467:in 'block in eager_load!'
/home/user/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.1.4/lib/rails/engine.rb:465:in 'each'
/home/user/.rvm/gems/ruby-2.0.0-p594/gems/railties-4.1.4/lib/rails/engine.rb:465:in 'eager_load!'
/home/user/.rvm/gems/ruby-2.0.0-p594/bundler/gems/resque-41469a3eaa93/lib/resque/tasks.rb:62:in 'block (2 levels) in <top (required)>'
```

But when I added that

``` bash
task 'resque:setup' => :environment
```

in main Rakefile, this mistake was gone.
Thanks you.

**Comment by luoguanzhong** [comment]
@avastor I got the same error, thanks.

**Comment by pnock** [comment]
I'm having trouble with this too, trying to upgrade from rails 3 to rails 4.  My rake tasks include the environment task, but my worker fails with an undefined method `layout' erorr for the first controller it tries to load in eager_load. Struggling to see what's different between the rails 3 and rails 4 code, or what I can configure differently to get this to work...

**Comment by pnock** [comment]
(For future googlers)

I figured out my problem. Root cause was somewhat random: $rails_rake_task doesn't seem to work as it did in rails 3. Because of that, some conditional stuff in the environment was kicking in that shouldn't have.
