### ISSUE TITLE
Background worker logs

### ISSUE THREAD

**Issue by mehulkar** [resque/resque#1266]
If I start a worker with this command in `v.1.25`:

```bash
PIDFILE="./resque.pid" BACKGROUND=yes QUEUE=paperclip rake environment resque:work
```

Where should I expect to see the logs for this queue?

**Comment by justinjohnsonio** [comment]
+1, preferably in the YAML file passed to `resque work -c=resque.yml`

**Comment by MrHubble** [comment]
> In the context of Rails, logs from this go to the appropriate Rails log file (e.g. log/development.log).

@mehulkar Is there a way to view just the worker in the logs? For example, I think with Heroku we can use something like `heroku logs --source app --ps worker` but I'm unsure how to do this locally in development.

**Comment by mehulkar** [comment]
@MrHubble no, I don't think so. But with 1.x, you can assign a logger like this:

```
Resque.logger = Logger.new("#{Rails.root}/log/resque.log")
```

Or similar. Then you can `tail -f log/resque.log and only get resque logs.

**Comment by MrHubble** [comment]
Brilliant! That is a massive help. Thank you so much @mehulkar

**Comment by steveklabnik** [comment]
Yes, that's the right way to set the logger. Closing!
