### ISSUE TITLE
ArgumentError in RedisMultiQueue in 1-x-stable

### ISSUE THREAD

**Issue by jonah-williams** [resque/resque#1270]
Commit 10912efdcec91de7486e273f203c884db5f523f8 introduced a call to [`Resque.list_range(queue, offset, limit, order)`](https://github.com/resque/resque/blame/1-x-stable/lib/resque/failure/redis_multi_queue.rb#L37). Unfortunately `list_range` is only accepts 3 arguments: [`def list_range(key, start = 0, count = 1)`](https://github.com/resque/resque/blob/1-x-stable/lib/resque.rb#L247 ).

I can't find any 4 argument version of `list_range` where this would be a valid call. As a result `RedisMultiQueue` is broken in `1-x-stable` as of at least 1.25.0. Anyone attempting to view `/resque/failed` in Resque web will always hit an exception.

**Comment by lisadu** [comment]
Any update on when this can be merged? `RedisMultiQueue.all` is completely broken in the current version.

**Comment by guilherme** [comment]
i have my thoughts on this, check #1283

**Comment by steveklabnik** [comment]
I have merged https://github.com/resque/resque/pull/1374 which will fix this.

**Comment by tneems** [comment]
Keep up the good work. Glad to see movement again.

**Comment by steveklabnik** [comment]
Thanks. I don't have a ton of time, but I'm gonna do my best.

**Comment by jonah-williams** [comment]
Thanks @steveklabnik, nice to see an issue fixed with whatever time you can spare.
