### ISSUE TITLE
Unexplained "HOOKNAME_IDENTIFIER" in docs

### ISSUE THREAD

**Issue by zmillman** [resque/resque#1279]
https://github.com/resque/resque/blob/master/docs/HOOKS.md

What does `HOOKNAME_IDENTIFIER` mean?

**Comment by yaauie** [comment]
Huh. That's one of those things that makes a lot of sense once you know, but I can see how it's not clear on a first read.

The method names need to start with the hook name (e.g., `before_enqueue`, `around_perform`), followed by an underscore & a descriptive identifier to help you tell it apart from other hooks.

For example, an `around_perform` hook that logged exceptions should be named something like `around_perform_log_exceptions`.

If you can think of a better way to express this, I'd gladly accept a pull-request :smile:

**Comment by zmillman** [comment]
See #1280 :+1:
