### ISSUE TITLE
Resque worker exit with exit code 0

### ISSUE THREAD

**Issue by bpaquet** [resque/resque#1282]
I have a standard resque worker launched with supervisord and the task resque:work

In some network edge cases, when redis is not reachable, the worker end with exit code 0 instead of an error code.

I'm using the 1.25.2
How I reproduce it :
- start the worker with supervisor
- wait the worker is online
- block the traffic on redis : sudo /sbin/iptables -A INPUT -p tcp --destination-port 6379 -j DROP
- the worker end with an exit code > 0, supervisord restart the worker
- the worker restart after few seconds, unable to connect to redis (normal)
- enable redis traffic : sudo /sbin/iptables -D INPUT -p tcp --destination-port 6379 -j DROP
- sometimes, the worker end with exit code 0, instead of a code > 0

I have traced the error to https://github.com/resque/resque/blob/v1.25.2/lib/resque/worker.rb#L211
A Redis::CannotConnectError exception is launched but not trapped (may be the condition is true).

I have seen all this code has been refactored in master.
Do you think the problem will fixed in future version ?
Do you need more information ?

**Comment by steveklabnik** [comment]
Hey @bpaquet ,

I would be interested in trying to track down a fix for this, but it would be nice to build this report into an actual test case somehow.

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
