### ISSUE TITLE
Confusing lack out output from workers

### ISSUE THREAD

**Issue by fields** [resque/resque#1284]
I run my resque workers in screen sessions so I can examine their output as they're running (a shell script starts the actual worker via the rake task). Most of the time this is a lot of output streaming by as the worker is processing jobs, but periodically some of them will freeze. The screen session sticks around, but the output stops, and the worker appears to be stuck.

However, if I examine the processes, the worker is still running and spawning new child processes. This one is stuck:

    $ ps -ef | grep 28740
    resque 13383 19927  0 17:23 pts/47   00:00:00 grep --color=auto 28740
    resque 28740     1  0 Feb06 ?        00:12:55 SCREEN -a -d -m -S worker1 /home/resque/execute_resque_worker.sh
    resque 28742 28740  0 Feb06 pts/1    00:00:00 /bin/bash /home/resque/execute_resque_worker.sh
    $ ps -ef | grep 28742
    resque 13423 19927  0 17:23 pts/47   00:00:00 grep --color=auto 28742
    resque 28742 28740  0 Feb06 pts/1    00:00:00 /bin/bash /home/resque/execute_resque_worker.sh
    resque 29829 28742 11 Feb06 pts/1    10:44:24 resque-1.25.2: Forked 13424 at 1423589034                                                                                    
    $ ps -ef | grep 29829
    resque 14336 19927  0 17:24 pts/47   00:00:00 grep --color=auto 29829
    resque 29829 28742 11 Feb06 pts/1    10:44:25 resque-1.25.2: Forked 14339 at 1423589041                                                                                    
    $ ps -ef | grep 29829
    resque 16853 29829  0 17:24 pts/1    00:00:00 resque-1.25.2: Processing get_metadata since 1423589054 [GetMetadataJob]                                      
    resque 16858 19927  0 17:24 pts/47   00:00:00 grep --color=auto 29829
    resque 29829 28742 11 Feb06 pts/1    10:44:28 resque-1.25.2: Forked 16853 at 1423589054                                                                                    
    $ ps -ef | grep 29829
    resque 19273 19927  0 17:24 pts/47   00:00:00 grep --color=auto 29829
    resque 29829 28742 11 Feb06 pts/1    10:44:30 resque-1.25.2: Forked 19297 at 1423589065                                                                                    
    $ ps -ef | grep 29829
    resque 19849 29829  0 17:24 pts/1    00:00:00 resque-1.25.2: Processing get_metadata since 1423589067 [GetMetadataJob]                                      
    resque 19941 19927  0 17:24 pts/47   00:00:00 grep --color=auto 29829
    resque 29829 28742 11 Feb06 pts/1    10:44:30 resque-1.25.2: Processing get_metadata since 1423589068 [GetMetadataJob] 

Any thoughts about why this would stop giving output or how to debug it further?

**Comment by steveklabnik** [comment]
Could you find a way to help me reproduce this issue?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
