### ISSUE TITLE
Resque fails with `undefined method `[]' for nil:NilClass`

### ISSUE THREAD

**Issue by adsteel** [resque/resque#1285]
In Rails 4.2, after starting redis via `$ redis-server`, a call to Resque fails with `undefined method '[]' for nil:NilClass` at the following line in the controller:

    Resque.enqueue(BackgroundStat, 1)

From my gemfile.lock:

    resque (~> 2.0.0.pre.1)!

I am not using the New Relic gem. Any ideas?

**Comment by hasJackb** [comment]
I'm not sure about this particular case, by I found that https://github.com/resque/resque/blob/master/lib/resque.rb#L85 sets the `@queues` instance var, and is only triggered if you call `Resque.redis = <something>` in an initializer or some such. This is the offending line: https://github.com/resque/resque/blob/master/lib/resque.rb#L268

I was able to get it working in a Sinatra app by using that call for establishing the redis connection. I'm open to making a PR, but I'm not familiar enough with Resque to know how this *should* be handled.

**Comment by hasJackb** [comment]
This is referenced more fully in this issue: https://github.com/resque/resque/issues/1258

**Comment by DannyBen** [comment]
I am having the same issue and same offending line. 
Tried changing different things in the initializer (currently just has something like `Resque.configure { |config| config.redis = 'redis://localhost:6379' }` but none of my attempts work.

Any ideas?

**Comment by geoom** [comment]
@DannyBen change config, add only `Resque.redis = 'localhost:6379'` in resque initializer file, this fixed my problem

**Comment by DannyBen** [comment]
Thanks @geoom , but still this seems to be a bug that needs fixing no?

**Comment by geoom** [comment]
you're right!

**Comment by steveklabnik** [comment]
As 2.0 is no longer happening, this bug is no longer relevant. Thanks.
