### ISSUE TITLE
cli.rb:15:in `initialize': undefined method `symbolize_keys'

### ISSUE THREAD

**Issue by twmulloy** [resque/resque#1290]
https://github.com/resque/resque/blob/master/lib/resque/cli.rb#L15

`gems/resque-6eba083bbdf8/lib/resque/cli.rb:15:in `initialize': undefined method `symbolize_keys' for #<String:0x007fd53323c890> (NoMethodError)`

Using `Procfile` command `worker: resque work -c='./.resque' --queues=mailer`

`.resque`

```
Resque.configure do |config|
  config.redis = 'localhost:6379'
end
```

**Comment by yaauie** [comment]
It looks like the content of your config file isn't a YAML-encoded hash, which is what we expect.

**Comment by twmulloy** [comment]
how do you use the `Resque.configure` config? https://github.com/resque/resque#configuration

**Comment by yaauie** [comment]
Your command line passes in `-c='./.resque'`, which is why this is failing; `./.resque` is a file that exists, but it's not a YAML-encoded hash, so there's en exception trying to handle it.

Either skip the `-c` directive, or use it to specify the path to a YAML-encoded config hash.

**Comment by twmulloy** [comment]
How do you use the `*.rb` `Resque.configure` block as shown in the `README`? I'm only looking to pass a different host to the `resque work` command. The `README` only says "You can also configure Resque via Resque.configure" but doesn't mention how to use it so it seems like it is to be assumed it is used the same as the `*.yml` config. Thanks

**Comment by dfockler** [comment]
@twmulloy https://github.com/resque/resque/issues/1258 This issue is basically talking about what you are asking. `Resque.configure` block doesn't do setup for you, it just sets the `redis` config as a string. There's not a fix yet. You can do something like `Resque.redis = 'localhost:6379'` and it will get everything setup for you though.

**Comment by steveklabnik** [comment]
Now that 2.0 is no longer a thing, this shouldn't be open anymore.
