### ISSUE TITLE
resque worker redundancy fail and try to connect to different redis database?

### ISSUE THREAD

**Issue by cdrage** [resque/resque#1292]
In my setup, I have Redis + Resque-Web setup with distributed Resque Workers running in Go.

We use Sinatra (took the code from the example app of Resque) to connect to redis and initiate the job.  

Is there any way to add redundancy in case one Redis instance goes down? In other words, hosting the Redis database on a different machine / redundant ones? 

EDIT: Re-worded question. Didn't have enough coffee.

**Comment by steveklabnik** [comment]
I believe this is one of the solutions Redis Cluster is intended to solve, and from my reading of the docs, it should Just Work, though I haven't tried it yet.
