### ISSUE TITLE
Resque web doen't retry the correct failed job on the second page of the failed jobs

### ISSUE THREAD

**Issue by marcelrouw** [resque/resque#1293]
Hi resque,

If I have more than 20 failed jobs in resque web and I want to retry a job on the second page. I doesn't restart the correct job! On the first page of the failed jobs in resque web the correct jobs are started.

I.e. if I retry worker with argument 27 (which is on the second page). I see in the log worker 17 is retried.

I've made a little test to confirm this problem.
Worker: I use the id to keep track of the job. I put in a `raise` to intentionally fail the job.
```ruby 
class TestWorker
  @queue = :test_queue
  
  def self.perform(id)
    Rails.logger.info "test #{id} worker ! #{Time.now.inspect}"
    puts "test #{id} worker! #{Time.now.inspect}" 
    
    raise    
  end
end
```

to add 30 workers 
```ruby 
    for i in 0..29
      Resque.enqueue(TestWorker, i)
    end
```

gems
```ruby 
gem 'resque', '1.25.2'
gem 'resque-scheduler', '2.5.5'
gem 'resque_mailer', '2.2.7'
```

ruby-1.9.3
rails 3.2

Kind Regards 
Marcel

**Comment by marcelrouw** [comment]
Hi,

I created a fix for this problem and created a pull requests.

Kind Regards
Marcel

**Comment by steveklabnik** [comment]
https://github.com/resque/resque/pull/1288 should have fixed this.
