### ISSUE TITLE
Resque broken with ruby 2.2

### ISSUE THREAD

**Issue by bkeroackdsc** [resque/resque#1295]
Attempting to run resque under ruby 2.2 (rails 3-2-stable from github) fails silently with no output.

```
root@986255b26a04# ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux-gnu]
root@986255b26a04# bundle --version
Bundler version 1.7.12
root@986255b26a04# bundle exec rails --version
Rails 3.2.21
root@986255b26a04# bundle exec rake resque:work RAILS_ENV="development" QUEUE=* VERBOSE="1" BACKGROUND="no" --trace; echo $?
0
```

The command returns immediately with no output. I notice a daemonized resque process that runs for a few seconds and then exits. No information is available on what happened.

Any ideas?

**Comment by mindware** [comment]
Was this fixed?

**Comment by bkeroackdsc** [comment]
Not that I know of. Should it be fixed?

**Comment by dplummer** [comment]
What version of resque are you using?

**Comment by bkeroackdsc** [comment]
1.24.1

**Comment by lukeasrodgers** [comment]
@bkeroackdsc 1-x-stable should now work with ruby 2.2, as of https://github.com/resque/resque/pull/1322.

When you get a chance could you see if you're still getting this issue?

**Comment by steveklabnik** [comment]
I'm giving this a close, as it should be fixed. Please let me know if it isn't!
