### ISSUE TITLE
No failed job showing in resque web interface, even through I enqueue wrong class jobs on purpose. 

### ISSUE THREAD

**Issue by kaikao** [resque/resque#1298]
I just tried to use resque to be my queue-job system, and try to put some jobs to queue 'default', resque-web is good to show me how many jobs was processed in the queue, but I can't see any filed jobs even through I put a wrong class job to the queue on purpose.

The version of ruby
```
ruby 2.0.0p643 (2015-02-25) [x86_64-linux]
```
The version of resque-web
```
rack 1.3
sinatra 1.4.6
vegas 0.1.11
```

This is my resque-web panel:

![screen shot 2015-04-24 at 2 02 37 am](https://cloud.githubusercontent.com/assets/2077651/7303906/4c04b9cc-ea26-11e4-9800-c561d1cb3073.png)

And the tab of stats
![screen shot 2015-04-24 at 2 05 13 am](https://cloud.githubusercontent.com/assets/2077651/7303957/99821cf8-ea26-11e4-8719-09f8c22cfc8d.png)

No failed jobs... but actually my redis server show me there are truly failed jobs.
![screen shot 2015-04-24 at 2 06 15 am](https://cloud.githubusercontent.com/assets/2077651/7303954/94af19ec-ea26-11e4-9d47-994949b12c9a.png)
 
![screen shot 2015-04-24 at 2 06 25 am](https://cloud.githubusercontent.com/assets/2077651/7303959/9cec7c76-ea26-11e4-8837-5bfb3c538697.png)

I have no idea whats going on, It's very thankful if anyone can give me some advices.

**Comment by steveklabnik** [comment]
Can you help me reproduce this issue? Maybe some sample jobs that cause it?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
