### ISSUE TITLE
Log errors with the appropriate (ERROR) log level

### ISSUE THREAD

**Issue by bob-rove** [resque/resque#1299]
Currently, all the messages are logged with DEBUG or INFO log level.
So in case of error, exception will be logged with INFO level. And if you are following a good practice to log only WARN and ERROR messages in production, you are in trouble. There is no way to resolve any issues in production with Resque failures before begin..resque block (https://github.com/resque/resque/blob/v1.25.2/lib/resque/worker.rb#L186) as you won't see anything in your logs.
As an example, if you have a short-term problem with connectivity between Resque and Redis, then worker will die trying to reserve the job and you will se nothing in the logs (if your verbosity level WARN).

**Comment by chrisccerami** [comment]
I can take a crack at this.

**Comment by chrisccerami** [comment]
@steveklabnik The `CONTRIBUTING.md` mentions `CHANGELOG` entries, but I don't see a Changelog in the repo. Am I missing something, or is the Contributing file out of date?

**Comment by steveklabnik** [comment]
It's that we lost the old CHANGELOG because I'm a bad maintainer.

I would like to have a good CHANGELOG, it was one of the things I was going to investigate for the next release.

**Comment by chrisccerami** [comment]
@bob-rove this should be addressed now by #1405
