### ISSUE TITLE
Wiki: ActiveJob - NotImplementedError

### ISSUE THREAD

**Issue by sepastian** [resque/resque#1302]
When implementing `perform` as a class method as described on Resque's [Wiki page for ActiveJob](https://github.com/resque/resque/wiki/ActiveJob), a `NotImplementedError` occurs, because ActiveJob cannot find `JobClass#perform`.

After removing `self` in front of `perform`, the error is gone.

```
class Archive < ActiveJob::Base
  queue_as :default

  def perform(repo_id, branch = 'master')
    repo = Repository.find(repo_id)
    repo.create_archive(branch)
  end
end
```

**Comment by mcfiredrill** [comment]
Thank you for your issue.
Looks like the wiki has been fixed since then. Closing this.

**Comment by akshaysharma096** [comment]
You have not changed the wiki page, please change it ASAP, it is causing a lot of confusion.

**Comment by chrisccerami** [comment]
@akshaysharma096 first, the Wiki was indeed updated [here](https://github.com/resque/resque/wiki/ActiveJob/5948047ee02a0d64c75cbb51e11ca30f1e7fe851). Second, I don't think any open source contributors appreciate demands being made. If you have an issue, we are happy to help when able, but we are not your paid employees, we are volunteers trying to help the open source community. Try to be more polite next time you raise an issue.
