### ISSUE TITLE
Tests Failed

### ISSUE THREAD

**Issue by balasankarc** [resque/resque#1303]
Hi,

I am packaging resque for Debian and have some issues with running tests. This is the output I got when I ran `bundle exec rake`. - http://paste.debian.net/178117/

How can I get the tests running succesfully?

**Comment by dfockler** [comment]
It looks like you need to check and make sure you have a `ps` command in your execution path. You got this as an error in that output

`System call for ps command failed. Please make sure that you have a compatible ps command in the path!`

**Comment by steveklabnik** [comment]
As this does not seem to be a bug in resque, I'm giving it a close. Thanks!
