### ISSUE TITLE
Misleading worker hostname implementation

### ISSUE THREAD

**Issue by andriytyurnikov** [resque/resque#1304]
Current implementation assumes that instance of Worker class is always used on same machine:
```ruby
# lib/resque/worker.rb
def hostname
  Socket.gethostname
end
```
When we have worker instances on worker machines (like ALL heroku deployments), then running rails console:
`Resque.workers[0].hostname` will return hostname of rails console machine

It seems wrong to invoke runtime-dependent class method, and to expose it as instance method

**Comment by steveklabnik** [comment]
Yes, this seems bad.

**Comment by crazymykl** [comment]
Question: if you call `to_s` on the worker, which hostname does it give in the string?

**Comment by chrisccerami** [comment]
@crazymykl without being able to test this out, my intuition in looking at the code is that it will still give the wrong answer in the above scenario.

```ruby
    def to_s
      @to_s ||= "#{hostname}:#{pid}:#{@queues.join(',')}"
    end
    alias_method :id, :to_s

    def hostname
      Socket.gethostname
    end
```

`#to_s` on `Worker` calls the same `#hostname` method, and so would have the same problem, no?
