### ISSUE TITLE
 Resque::Config (NameError)

### ISSUE THREAD

**Issue by dougfarre** [resque/resque#1306]
I have an initializer file that contains the following:

Resque.configure do |config|
  config.redis = Rails.application.secrets.redis_url
end

I am getting an error when i try to start the rails server:
/Users/dougf/.rvm/gems/ruby-2.2.0@project/gems/resque-1.25.2/lib/resque.rb:59:in `config': uninitialized constant Resque::Config (NameError)
	from /Users/dougf/.rvm/gems/ruby-2.2.0@project/gems/resque-1.25.2/lib/resque.rb:63:in `configure'
	from /Users/dougf/Documents/project/config/initializers/resque.rb:3:in `<top (required)>

**Comment by sbusso** [comment]
Seems configure is for Resque 2.0pre. You may want to look at https://github.com/resque/resque/tree/1-x-stable for documentation about 1.x

**Comment by J-F-Liu** [comment]
Meet the same error: `C:/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque.rb:59:in 'config': uninitialized constant Resque::Config (NameError)`

**Comment by hoffmanc** [comment]
@J-F-Liu: @sbusso is correct - that information is for the unreleased 2.0 branch, which happens to live on master right now.  Look to the  [1-x-stable](https://github.com/resque/resque/tree/1-x-stable) branch for the proper configuration details.

CC: @steveklabnik

**Comment by steveklabnik** [comment]
This is now out of date, since master no longer talks about any of this.
