### ISSUE TITLE
Restarting Resque jobs in 1.24.1 creates duplicate failures

### ISSUE THREAD

**Issue by ponny** [resque/resque#1310]
When restarting my workers, duplicate failed jobs seem to be created.  The Resque::DirtyExit failures seem to create between 1 and 5 copies of the failure.  Any ideas what could be causing this?  

Screenshot: https://dl.dropboxusercontent.com/spa/wdptakhwk6xo3zk/psp-gxck.png

**Comment by yaauie** [comment]
Likely a race condition in the startup of new resque processes. Upon startup, each process checks to see if there is any outstanding work checked out to workers with the same hostname that no longer exist. In this case, I believe multiple processes are starting up simultaneously, and each of them is cleaning up after the abandoned work, resulting in duplicates.

**Comment by steveklabnik** [comment]
Can you help me find a way to reproduce this behavior pleases?

**Comment by ponny** [comment]
I've only seen it in my production environment which has four boxen each with about 15 workers.   This only happens when I do an upstart restart on the jobs.  The upstart conf has a kill signal SIGQUIT and a kill timeout 60.  I hope this helps.

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
