### ISSUE TITLE
Rails active job set wait: not working with resque?

### ISSUE THREAD

**Issue by roma86** [resque/resque#1313]
Hello! Thank you for library.

```
gem 'resque', '~> 1.24'
```

```ruby
class CheckDevicesJob < ActiveJob::Base
  queue_as :low_priority

  def perform
    puts 'CheckDevicesJob start task'
    sleep 5
    puts 'CheckDevicesJob complete after 5 seconds'
  end
end
```

Run by default:
```ruby
CheckDevicesJob.perform_later
```

Its work!
```
worker.1 | [ActiveJob] [CheckDevicesJob] [6ae86a4f-e0ae-4a40...
worker.1 | CheckDevicesJob start task
worker.1 | CheckDevicesJob complete after 5 seconds
worker.1 | [ActiveJob] [CheckDevicesJob] [6ae86a4f-e0ae-4a40...
```

The problem:

Rails active job guid says i can use ```MyJob.set(wait: time_interval)```

But 
```ruby
CheckDevicesJob.set(wait: 10.seconds).perform_later
```

Output nothing. Resque-web do not show activity for this command too.

```ruby
CheckDevicesJob.set(queue: :another_queue).perform_later
```
Works again. So passing options is fine as i can see.

Big chance i am doing it something wrong. I need the point.

**Comment by yaauie** [comment]
your bug is probably with either [`activesupport`](https://github.com/rails/rails/tree/master/activesupport) or [`resque-scheduler`](https://github.com/resque/resque-scheduler), both of which are extensions on top of the resque gem, and neither of which we can fix here :smile:

**Comment by kaninfod** [comment]
You need to run resque-scheduler for the delayed jobs to work
