### ISSUE TITLE
BACKGROUND mode issue

### ISSUE THREAD

**Issue by curbsaleem** [resque/resque#1314]
BACKGROUND=yes, is not working  using 'resque', '1.24.1'

**Comment by steveklabnik** [comment]
Can you define what "not working" means? Some kind of error message? A way to reproduce this? Thanks!

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
