### ISSUE TITLE
Use LPUSH to add job to front of queue

### ISSUE THREAD

**Issue by thenovices** [resque/resque#1323]
I would love to have the ability to add a job to the front of the queue. In particular, I currently want to do this in conjunction with resque-retry: in certain cases, I want to have the job immediately re-run after an Exception, but without having to go to the end of the queue.

Here is a Resque plugin that does this by using LPUSH instead of RPUSH on the queues:
https://github.com/coupa/resque-priority_enqueue

It's not really maintained though, and I would love to see it included in the main Resque project. It's only a couple lines of code.

**Comment by yaauie** [comment]
If you'd like to create a pull-request, I'll consider it against 1-x-stable as long as it comes with good test coverage; since the project is also MIT-licensed, there won't be a problem with copying code from it wholesale.

**Comment by Jacobkg** [comment]
@steveklabnik Looks like there was a PR for this feature that was closed https://github.com/resque/resque/pull/1324#issuecomment-155817070. Should we retag this as 'feature request'?

**Comment by steveklabnik** [comment]
:+1:

**Comment by chrisccerami** [comment]
It sounds to me like #1324 was closed with the idea that Resque isn't interested in a feature to use LPUSH because you can just add jobs to a higher priority queue. If that's the case, then should this issue also be closed?

**Comment by fw42** [comment]
Has this been addressed by https://github.com/resque/resque/pull/1425? Can this issue be closed?

**Comment by chrisccerami** [comment]
Seems like it to me.

**Comment by nathantsoi** [comment]
@fw42 & @steveklabnik, unless i'm missing something here, lpush is necessary to implement a LiFo queue and cannot be implemented w/ a "higher priority queue." If I submit a pr against the latest branch, would the Resque team consider merging again? As noted in https://github.com/resque/resque/pull/1425, this feature has been lost in the latest release.

**Comment by thenovices** [comment]
@nathantsoi Not sure what the concern is.
1) They had previously mentioned using a higher priority queue as an imperfect solution without having to patch resque with a lpush option. Now that we have a lpush option via #1425 no higher priority queue is needed.

2) I'm not sure why another merge is needed? #1425 got merged in, just after the latest release was cut (and this was done on purpose). It'll be included when the next release is cut.

**Comment by nathantsoi** [comment]
you're totally right @thenovices, i looked in the release gem, not on master. seems to be there and all is well! looking forward to the next release :)

**Comment by scomma** [comment]
I'm sad that this got rejected. Neither higher priority queues or enqueue_front solves our use case. We have a queue that needs to work like enqueue_front, without changing the behavior of other queues.
