### ISSUE TITLE
New schedules are not executed

### ISSUE THREAD

**Issue by astudnev** [resque/resque#1331]
resque-scheduler (4.0.0)

New  schedules added to resque_schedule.yml are not executed.

They are shown OK in UI - look attached schedule
![sch](https://cloud.githubusercontent.com/assets/1385046/9711034/f33ea88c-5548-11e5-8bfe-b81da86da3e2.png)

When starting, the new schedule appears in log as "Scheduling cbki_conversion_reader":

studnev@leadads:/var/www/leadada-tracker/current$ bundle exec rake resque:scheduler RAILS_ENV=production
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Starting
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Loading Schedule
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling cbki_conversion_reader 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling leads_conversion_reader 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling publisher_postback_sender 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling etl_log_writer 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling cpahub_conversion_reader 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling etl_log_reader 
resque-scheduler: [INFO] 2015-09-07T10:15:33+03:00: Scheduling leadada_monitor_unprocessed_worker 
resque-scheduler: [INFO] 2015-09-07T10:15:34+03:00: Scheduling leadada_info_update_job 
resque-scheduler: [INFO] 2015-09-07T10:15:34+03:00: Schedules Loaded

but then in never executes.

Manually executing it works OK.

**Comment by hoffmanc** [comment]
This probably belongs in https://github.com/resque/resque-scheduler, no?

**Comment by astudnev** [comment]
Yes, sorry for the wrong topic here... i thought it is the same project.
I sumbmitted to scheduler, please close it here!

**Comment by hoffmanc** [comment]
I wish I could.
