### ISSUE TITLE
redis showing way more keys than in resque queues

### ISSUE THREAD

**Issue by jblauer** [resque/resque#1333]
I'm processing a large number of jobs and running into OOM issues in Redis with maxmemory-policy set to volatile-lru.

The major problem appears to be that redis is reporting a number of keys close to the total number processed by resque, well in excess of the total number pending in the queues. It's as if keys for processed jobs are never being deleted.

The resque stats show:

failed	578
pending	87403
processed	2118372

while redis info command shows:

db0:keys=1810656,expires=1,avg_ttl=176611

Any help troubleshooting this would be much appreciated!

**Comment by yaauie** [comment]
Are you using any third-party extensions or plugins, perhaps something to help you keep track of work performed or give you the status of jobs by id? While 1.8MM KEYS may be too large to enumerate with redis' `KEYS` command, perhaps using redis' `RANDOMKEY` a few times will help you clue in on what type of data is being stored.

**Comment by hoffmanc** [comment]
Redis also offers [scan](http://redis.io/commands/scan), which can be used to iterate over the keys in a nonblocking way.  The ruby client adds a [scan_each](http://www.rubydoc.info/gems/redis/3.2.1/Redis%3Ascan_each) method, to make it easier to use `scan`.

**Comment by jblauer** [comment]
Ok, I used redis-dump and grep to find that resque-scheduler is the culprit that is not deleting it's keys after enqueuing them.

I guess I should take this over to the resque-scheduler issues forum, but was wondering if anyone here might have seen this before, and know of a solution.

Thanks!

**Comment by jblauer** [comment]
Problem solved. 

I had two applications using resque to communicate between themselves, and they were running incompatible versions of resque-scheduler (2.0 vs 2.2).
