### ISSUE TITLE
Is this type of gradual up and then fast down, normal? 

### ISSUE THREAD

**Issue by offordscott** [resque/resque#1336]
<img width="764" alt="screen shot 2015-10-09 at 11 06 05 am" src="https://cloud.githubusercontent.com/assets/920439/10399011/cfb0cbca-6e75-11e5-9ae8-799303b3c3a7.png">

Is this type of gradual up and then fast down, normal?

**Comment by offordscott** [comment]
<img width="742" alt="screen shot 2015-10-09 at 11 08 44 am" src="https://cloud.githubusercontent.com/assets/920439/10399071/25d8ed84-6e76-11e5-978c-87e3ad404156.png">

**Comment by Rockstar04** [comment]
Its been a while since I set up my Resque server, but are you using something to keep the process running (like God) that will kill workers after a certain number of requests or if they use too much memory? I am using God to kill any workers that consume over 350mb of memory

**Comment by steveklabnik** [comment]
I don't believe it is, @offordscott . It looks like you have a memory leak, maybe? @Rockstar04 's intuition seems right.

Also, since you're using `bin/resque`, was this behavior in 2.0 or 1.x?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
