### ISSUE TITLE
Worker failing to create worker even though it states it in terminal

### ISSUE THREAD

**Issue by damienh** [resque/resque#1339]
Hello,

I am setting up resque `1.25.2` on a Rails 3.2 install. I am using a procfile to start up my resque process and I can see this in the logs `16:11:18 resque.1 | started with pid 19787` and later on `16:11:56 resque.1 | Worker theappname:19787:default starting`

procfile:

`resque: bundle exec rake environment resque:work QUEUE=default`

but when I view the web ui or via rails console it doesnt show any workers have been created. `Resque.info
=> {:pending=>1, :processed=>0, :queues=>1, :workers=>0, :working=>0, :failed=>0, :servers=>["redis://127.0.0.1:6379/0"], :environment=>"development"}` I can see new jobs get added to the queue. 

I have `resque.rake`

```
require 'resque/tasks'

task 'resque:setup' => :environment
```

Does anyone know of a reason why?

**Comment by steveklabnik** [comment]
Does this reproduce on a new repository?

**Comment by damienh** [comment]
@steveklabnik I dont have access to the repository with resque now. I know that I was never able to get around it. Sidekiq was implemented in the end.

**Comment by steveklabnik** [comment]
Okay! Sorry about that.
