### ISSUE TITLE
Wait for completion of a jobs group or list of job ids.

### ISSUE THREAD

**Issue by phlegx** [resque/resque#1349]
Hi!

How can I start e.g. 10 jobs and wait that all jobs has completed to continue with other instructions. I want to use resque to populate the database. Thx!

**Comment by yaauie** [comment]
You can use a combination of plugins to achieve this (but there are some gotchas):
 - `resque-status`: gives jobs unique ids, and tracks status of those jobs
 - `resque-scheduler`: provides the ability to schedule work to happen after a future point-in-time

1. build the jobs as status'd jobs, kick off the 10 jobs & get their status ids
2. kick off another job that takes those status_ids as part of its input & has a `before_perform` hook that will prevent performing if they're not all done and use `resque-scheduler` to schedule the job for a future time (say, 30s in the future).

Ok, now the gotchas:

1. resque-scheduler adds the overhead of a running process to watch the schedules and put items into the queue at the appropriate time; if this process dies, scheduled work does not get queued.
2. while yours is a simple use-case, state-coordination is hard at scale; individual jobs failing can cause the dependent job to get stuck in an indefinite loop, and without proper logging/alerting this kind of a setup makes things pretty hard to debug.

**Comment by phlegx** [comment]
@yaauie thx! :)

**Comment by yaauie** [comment]
I'm closing the ticket, as I believe the question/issue has been resolved by my response
