### ISSUE TITLE
Resque::Worker.unregister_worker should clear the "processing" job if there's an exception in `job.fail`

### ISSUE THREAD

**Issue by jason-o-matic** [resque/resque#1353]
If a worker dies on a job, and that job causes an exception in `job.fail`, then the worker will die. This worker will never be able to restart because the same thing will happen in `unregister_worker` when the worker starts up again.

Perhaps `redis.del("worker:#{self}")` should happen before `job.fail`, or perhaps better the exception should be caught and logged.

**Comment by RochesterinNYC** [comment]
This should be addressed by #1360.
