### ISSUE TITLE
"Stack level too deep" when passing a Class as an argument to Resque.enqueue

### ISSUE THREAD

**Issue by mikemarsian** [resque/resque#1365]
If ActiveRecord is required in my gem project, than calling ```Resque.enqueue``` with a Class object as an argument produces the following error:
```
SystemStackError:
       stack level too deep
     # /home/mike/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.11/lib/active_record/scoping.rb:130
```

To avoid the bug, all is needed is to make sure we don't pass Class object to ```Resque.enqueue``` as argument, and instead pass a String (by calling ```Resque.enqueue(Serially::Worker, item_class.to_s, item_id)``` instead of: https://github.com/mikemarsian/serially/blob/v0.1.0-resque_bug/lib/serially/worker.rb#L44

Here's the project tag, which demonstrates the issue (after cloning and running bundle, simply run 'rake' to run tests, and see the problem): https://github.com/mikemarsian/serially/releases/tag/v0.1.0-resque_bug

**Comment by Jacobkg** [comment]
@mikemarsian @steveklabnik I did some work to reproduce this error. I was able to reproduce it with this test within the serially project:

```
require 'spec_helper'

describe 'Simple class that includes Serially' do
  it 'is a simple test' do
      MultiJson.dump({ foo: SimpleClass })
  end
end
```

Moreover, when I tried doing ```SimpleClass.to_json```, I got an exception:
```
ActiveSupport::JSON::Encoding::CircularReferenceError:
       object references itself
     # /home/vagrant/.rvm/gems/ruby-2.1.6@serially/gems/activesupport-3.2.22/lib/active_support/json/encoding.rb:75:in `check_for_circular_references'
     # /home/vagrant/.rvm/gems/ruby-2.1.6@serially/gems/activesupport-3.2.22/lib/active_support/json/encoding.rb:46:in `encode'
...
```

What this tells me is that the problem likely lies outside of `Resque` and is either in `Serially` itself, or in on of the `JSON` gems.

**Comment by steveklabnik** [comment]
Okay! I'm going to give this one a close, then.
