### ISSUE TITLE
Hook for the main loop?

### ISSUE THREAD

**Issue by jchatel** [resque/resque#1367]
Any plan to add a hook in main loop ( def work(interval = 5.0, &block) ) ?

This will remove the need for me to rely on an extra process for the scheduler.

**Comment by steveklabnik** [comment]
No such plans right now, but I might take a patch for it.

**Comment by RochesterinNYC** [comment]
@jchatel What do you mean by hook in this case?

**Comment by RochesterinNYC** [comment]
What is meant by hook in this case?
