### ISSUE TITLE
Extract airbrake to another gem

### ISSUE THREAD

**Issue by josedonizetti** [resque/resque#1368]
I was thinking if having airbrake inside the core, make sense. What do you think?

**Comment by steveklabnik** [comment]
:+1:

**Comment by amorphid** [comment]
@steveklabnik I can handle this.  Feel free to assign to me.

**Comment by steveklabnik** [comment]
I can apparently only assign people who have commit, i dunno.

**Comment by amorphid** [comment]
I just started working on this.  Quick question...  I'm poking around the code, and I see Ruby 1.8.7 mentioned in `travis.yml`, and there's a separate Gemfile for 1.8.7 in `/Gemfiles`.  Do I need to be thinking about 1.8.7 that when working on extracting the Airbrake functionality into a gem, or would 1.9.3 be good enough?

**Comment by steveklabnik** [comment]
Generally, we still support 1.8, yes. I would suggest just doing the work for 1.9, and then we can see what Travis says and go from there.

**Comment by chrisccerami** [comment]
I think I'm confused by this one. Isn't [Airbrake](https://github.com/airbrake/airbrake) already its own gem?

**Comment by amorphid** [comment]
@chrisccerami The main idea is that the airbrake gem is included in Resque by default, and it shouldn't be.  I'm (working on today actually) an update of the airbrake-resque gem.

**Comment by chrisccerami** [comment]
Gotcha. That makes sense. :+1:

**Comment by jeremy** [comment]
Airbrake now provides [their own Resque failure handler](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/resque.rb).
