### ISSUE TITLE
Are you on a fork of Resque? I'd like to get you back on releases

### ISSUE THREAD

**Issue by steveklabnik** [resque/resque#1372]
Hey there! So Resque hasn't gotten any updates in a long time, but I've been doing some work, trying to get ready for `1.26.0`.

One thing that I would like to do is get people who are on forks back to master. Said forks are my fault for stepping away from Resque :sob: 

If you're one of those people, would you mind leaving a comment with

1. what stuff you've fixed in forks
2. if you're interested in moving those patches upstream
3. any other bugs that you consider high-priority.

Thanks!

**Comment by steveklabnik** [comment]
@rbroemeling sent in PR https://github.com/resque/resque/pull/1371

**Comment by steveklabnik** [comment]
Fixing https://github.com/resque/resque/issues/1074 is important.

**Comment by steveklabnik** [comment]
@dylanahsmith mentioned that Shopify is interested, and that @fw42 might be helping figure it out.

**Comment by steveklabnik** [comment]
https://github.com/resque/resque/issues/552 is at least one thing @github would need to get back on mainline, but it's a biggie. I'd still like to make it happen, though it might take till a 1.27.0

**Comment by fw42** [comment]
Just out of curiosity: Why are you going back to 1.x instead of continuing work on 2.x? What's wrong with 2.x?

**Comment by arthurnn** [comment]
i mentioned to @technoweenie that I am interested in helping with resque

**Comment by steveklabnik** [comment]
@fw42 I blogged about it http://words.steveklabnik.com/rescuing-resque-again

@arthurnn that would be fantastic! Maybe a good first step is figuring out what @github needs here?

**Comment by steveklabnik** [comment]
Okay! I think that this is about all the response we're gonna get on this issue. I am still quite interested in this overall, and we've integrated a lot of Shopify's changes. :+1: 

Thanks everyone! And to future googlers, I am still interested in making this happen if you're on a fork. :smile:
