### ISSUE TITLE
Perform with named params throws exception "wrong number of arguments"

### ISSUE THREAD

**Issue by d4rk5eed** [resque/resque#1388]
hi guys
for example, I have job with perform

``` ruby
def perform(a, b, c, d: true, e: false)
  #...
end
```

I successfully enqueue the task `Reque.enqueue(MyJob, 1,2,3, d: false)`

And finally I  have job failed with  `wrong number of arguments (4 for 3)`
I think problem with named arguments, they're skipped.

Does it look like bug?

**Comment by steveklabnik** [comment]
It does, but I'm not sure if it's a ruby thing or a resque thing. Like, we don't support named arguments in `enqueue` because we support Rubies that do not support named arguments.

So I think it's a bug in the sense that we should somehow reject this at enqueueing time.

**Comment by d4rk5eed** [comment]
@steveklabnik  how about  to force named arguments to hash at enqueueing?

**Comment by steveklabnik** [comment]
Yeah, something like that might work. To be honest, I'm not as up on the exact details of keyword arguments in Ruby these days.

**Comment by d4rk5eed** [comment]
ok, I'll work on issue

**Comment by d4rk5eed** [comment]
@steveklabnik think that throwing warning on named params or symbolic keys should be sufficient. What d'u think?

**Comment by steveklabnik** [comment]
:+1:

**Comment by chrisbloom7** [comment]
So is the consensus now that `enqueue` will not support `perform` method definitions that use keyword arguments? FWIW, passing in keyword arguments as a single hash argument still triggers the error.

**Comment by jeremy** [comment]
Supporting keyword args would require 1. introspection on the perform method to deduce whether an argument is *meant* to be a keyword arg or an options hash and 2. specialized args serialization to distinguish the two. That poses significant backward compatibility & interoperability challenges. Much simpler to stick with basic JSON-serializable args and require method signatures to match.

(Note that Active Job does support keyword args by implementing specialized args serialization itself.)
