### ISSUE TITLE
Resque worker paused?

### ISSUE THREAD

**Issue by jpbullalayao** [resque/resque#1391]
Hi everyone, 

I'm new to Resque and am trying to get my first Resque job to work correctly. I believe I have my Resque job written correctly and placed in the queue, however I am confused after I run the following:

```
$ PIDFILE=./resque.pid BACKGROUND=yes QUEUE=scheduled_deliveries rake environment resque:work
```

It seems that my worker is paused? I say this because I can't do anything in the command line anymore except for `control+c` (which would stop the worker). 

**Thus, one of my assumptions for why my Resque job isn't working correctly is because of this.** I can call my `perform` method manually in the rails console and my job works correctly, but when I enqueue it with Resque, it doesn't work. 

Is it normal for this 'pause' to happen? 

Screenshot below:

![screen shot 2016-01-22 at 9 56 35 am](https://cloud.githubusercontent.com/assets/3538024/12518666/b1acb3ca-c0ee-11e5-904a-08908ec0ed46.png)

Thanks so much for the help!

**Comment by jpbullalayao** [comment]
Actually, never mind I might close this for now, I just read through the GitHub docs more and it looks like this is normal; I should be running this worker in the background instead of the foreground (duh)

**Comment by steveklabnik** [comment]
Hm, so this issue was edited. this is still happening with `BACKGROUND=yes`?

**Comment by jpbullalayao** [comment]
Yes it was edited; my original question was about running the worker without `BACKGROUND=yes`, then I realized that there was a way to run the Resque job using `BACKGROUND=yes`. However, when I try `BACKGROUND=yes`, it still pauses and doesn't return to the command line. 

Any ideas on what might potentially be wrong? Maybe some Resque configuration on my end isn't correct?

**Comment by jpbullalayao** [comment]
Actually Steve, we can close this issue, it's actually not a bug or anything because I was able to type `rails c` afterwards and get the console running (I must be too tired!)

**Comment by steveklabnik** [comment]
It is not super obvious to me. It should be working...

Does this reproduce outside of your application? That should help narrow it down.

**Comment by steveklabnik** [comment]
ah, i see. Great!
