### ISSUE TITLE
Resque not fetching ActiveRecord object with updated values?

### ISSUE THREAD

**Issue by jpbullalayao** [resque/resque#1392]
Hello,

Second time posting an issue here, hoping to get some guidance as to what I may be doing wrong.

I have the following fixture in my test DB:

![screen shot 2016-01-22 at 1 15 46 pm](https://cloud.githubusercontent.com/assets/3538024/12523238/77a24408-c10a-11e5-86ec-d21c30e34dda.png)

I'm currently testing a method that updates attributes to this fixture, and afterwards makes a call to `Resque.enqueue(PlaceDelivery, asap_transaction.id)`. 

In the `self.perform` method of the `PlaceDelivery` class, I have the following code:

```ruby
def self.perform(asap_transaction_id)
  asap_transaction = AsapTransaction.find(asap_transaction_id)
  puts "#{asap_transaction.to_json}"
end
```

The problem here is that the retrieved `asap_transaction` contains the values from the original fixture, rather than the new values.

**I want to be able to use the most-updated ActiveRecord object, but fetching it through `self.perform` is giving me the old one. Is there something I'm doing wrong?**

I hope this made sense!

**Comment by steveklabnik** [comment]
Are you sure that you're calling `save` on the model after you update it? That's the first thing I'm thinking of.

**Comment by Jacobkg** [comment]
@jpbullalayao Can you make a gist (gist.github.com) of the full test file that you are running as well as the file containing the method you are calling

**Comment by jpbullalayao** [comment]
Hey guys,

Sure, I'll be happy to create a Gist. This issue comes up only when I'm running my code in the test environment, but works in the development environment. I'll let you both know when I'm done!

**Comment by Jacobkg** [comment]
@jpbullalayao Are you still experiencing this issue?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
