### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by chrisccerami** [resque/resque#1406]
I almost dread opening this issue, due to certain recent events, but it's something that I think is important to discuss. With Resque coming up on 7 years old, I think it's as good of a time as any to talk about adopting a Code of Conduct for contributors/maintainers. Personally, I like [Contributor Covenant](http://contributor-covenant.org/version/1/3/0/) as a good starting point.

**Comment by steveklabnik** [comment]
Not a dread at all. I was going to add this after the next release :+1: 

(this is only because the release is coming soon, and it's a good chance to talk about policy changes for the next version, like modifying support for certain rubies.)

**Comment by chrisccerami** [comment]
I figured it was something you were thinking about already. Shall we leave this issue open as a space for discussion?

**Comment by steveklabnik** [comment]
Yup, gonna leave it open until it's actually merged.

**Comment by jart** [comment]
I'd like to propose the following code of conduct, which is politically neutral: https://gist.github.com/jart/f274d8dc156811a46b22

**Comment by steveklabnik** [comment]
Just for an update on this: I am going to cut 1.26.0 tonight or tomorrow, and a CoC will be the first commit of 1.27.0.

**Comment by chrisccerami** [comment]
:rainbow: :fireworks: Thanks @steveklabnik !

**Comment by jart** [comment]
@steveklabnik It's possible that, by adopting these restrictive covenants, you may be increasing your organization's litigation risk. I would strongly recommend speaking with a lawyer before adopting something like the Contributor Covenant.

**Comment by chrisccerami** [comment]
I disagree that having a Code of Conduct opens one up to litigation risks, and I also believe it's an important part of creating a welcoming community.

**Comment by jart** [comment]
Just to reiterate @steveklabnik, I encourage you to seek the opinion of a legal professional. Matz has been resisting the CC for a reason. Also, thank you for your hard work and contributions to the Ruby community.

**Comment by chrisccerami** [comment]
Fear of legal action was not a stated reason for the rejection of the Contributor Covenant by the Ruby language project. Excuse me if I feel like your stated concern is disingenuous, but it seems like a scare tactic meant to discourage the use of Codes of Conduct.

**Comment by steveklabnik** [comment]
@jart your concern trolling isn't welcome. You like to suggest that those in favor of a COC aren't programmers who do real work, yet you have never contributed a patch to resuqe. Stop being a hypocrite.
