### ISSUE TITLE
Processing jobs in the background (using Resque and Resque-scheduler)

### ISSUE THREAD

**Issue by jpbullalayao** [resque/resque#1417]
Hey guys,

I'm not sure if GitHub issues is the place to ask this question; so feel free to point me somewhere else (such as an email or IRC channel) if this isn't the right place!

I need help with an issue while trying to use Resque and Resque-scheduler to run a delayed job in the future (using a 'deliveries' queue).

**Basically, my jobs work correctly when I run both Resque and Resque-scheduler in the foreground, but the jobs don't process in Resque when I run them in the background (using `BACKGROUND=yes`).** 

If you see the screenshot below, you can see Resque-scheduler processing 'Delayed Items', but Resque doesn't actually process it. I have `VERBOSE=1` set for Resque, so that I can see the logs.

![screen shot 2016-02-17 at 11 56 02 am](https://cloud.githubusercontent.com/assets/3538024/13123100/5c078798-d56f-11e5-993e-09e72f92fdad.png)

**Any idea what I'm doing wrong? Could it be my configuration settings being incorrect?** Here's my configuration:

![screen shot 2016-02-17 at 12 07 16 pm](https://cloud.githubusercontent.com/assets/3538024/13123125/8908e2a0-d56f-11e5-8795-34f8fd52666d.png)

Thanks so much! Feel free to ask for more information if necessary.

**Comment by steveklabnik** [comment]
Looks reasonable to me. Any chance this works on a new/small application so we can try to debug it?

**Comment by avecchio** [comment]
I am having a similar issue with resque and resque scheduler.

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!

**Comment by avecchio** [comment]
Apologies. I figured out my issue. The redis dump file became corrupted during merge conflicts which halted all jobs.

**Comment by steveklabnik** [comment]
Ah, no worries! Glad you got it sorted :)
