### ISSUE TITLE
Is Resque::Job.queued a future or deprecated method?

### ISSUE THREAD

**Issue by patakijv** [resque/resque#1421]
I was searching for a method that I can use to find queued jobs and according to the documentation, the class method [`Resque::Job.queued`](http://www.rubydoc.info/github/resque/resque/Resque/Job#queued-class_method) seems to be what I am looking for however this class method doesn't exist in 1.25.2 which I have nor does it show up when I search the repo or go hunting for it in the `1-x-stable` branch in github. Is this a deprecated method or is it a future method to be available later? Confused...

**Comment by steveklabnik** [comment]
It looks like Rubydoc.info has old documentation.

`master` used to be Resque 2.0, which is where that method existed. But 2.0 is cancelled. So it _was_ going to be, but is not anymore.

Off the top of my head, I don't remember if such a thing exists in 1.x, so I'm gonna tag this as "feature request" for now.

**Comment by chrisccerami** [comment]
@patakijv I would recommend looking into the [resque-status](github.com/quirkey/resque-status) for this and similar functionality.
