### ISSUE TITLE
Is there a recommended way to find related/associated jobs for a model object?

### ISSUE THREAD

**Issue by patakijv** [resque/resque#1422]
I need to be able to find and destroy queued and/or working jobs for a model object, say for example when the model object is destroyed. Is there a recommended way to do this before I reinvent the wheel? 

Example: 

If you want to create a before_destroy callback that destroys all jobs when the object is destroyed (both queued and working jobs)

pseudo code of what I am thinking to do ...

```
class Report < ActiveRecord::Base
  before_destroy :destroy_queued_and_working_jobs

  def destroy_queued_and_working_jobs
    queued_report_processing_jobs = ProcessReportWorker.find_queued_jobs_by_report_id(self.id) 
    working_report_processing_jobs = ProcessReportWorker.find_working_jobs_by_report_id(self.id) 
    (working_report_processing_jobs + queued_report_processing_jobs).each do |job| 
       # destroy the job here
    end
  end

end

class ProcessReportWorker
  def self.find_queued_jobs_by_report_id(id)
     # find the jobs by report id which is first argument for the job... parse all to find?
  end 
  def self.find_working_jobs_by_report_id(id)
     # find the jobs by report id which is first argument for the job... parse all to find?
  end 
end
```

Is this approach on track with what needs to happen? What are the missing pieces above to find the queued or working jobs? Are there already methods in place to find and/or destroy by associated model object id?

**Comment by steveklabnik** [comment]
Please post questions to StackOverflow, I'd like to keep the issue tracker for just bugs and feature requests. Thanks!

**Comment by patakijv** [comment]
Ok. In case others find it useful who come across this post, here is the subsequently created StackOverflow question: http://stackoverflow.com/questions/35636861/how-to-find-associated-resque-jobs-for-an-activerecord-model-object
