### ISSUE TITLE
start resque worker error with jruby rails app

### ISSUE THREAD

**Issue by GKZX** [resque/resque#1423]
I create a rails app by jruby(version 9.0.4.0, resque 1.25.2) ,when I run `env RESQUE_TERM_TIMEOUT=1 TERM_CHILD=1 QUEUE=critical bundle exec rake resque:work` it returns "The signal QUIT is in use by the JVM and not work correctly on this platform" How can I fix this error?

**Comment by steveklabnik** [comment]
This is a warning, not a hard error. That said, it might cause problems; the JVM implements its own signal handling, so applications can't use those signals, and resque makes heavy use of signals.

**Comment by GKZX** [comment]
I started resque-web  and find that the work is running, but my jobs still pending.

**Comment by thbar** [comment]
@GKZX did you ultimately had success with JRuby + Resque?
