### ISSUE TITLE
PG::UnableToSend error on Puma ( works in development )

### ISSUE THREAD

**Issue by hadinishad** [resque/resque#1426]
Hi,

Yesterday, I set up Resque on our project and it worked beautifully locally. Pushing the same to the test server brought up a ton of issues which were all fixed except this. 

( Resque was always using development environment. We had to export $RAILS_ENV=staging on our staging server's .bash_profile for it to use correct redis. Using RAILS_ENV=staging QUEUE=\* bundle exec rake environment resque:work didnt work and it was still using development redis ).

Now, Jobs which don't access Postgres work completely fine. Jobs which access mongodb also work. Just seems to be an issue with postgres. The error returned is as so -

>  PG::UnableToSend: server closed the connection unexpectedly.  This probably means the server terminated abnormally before or while processing the request.

Googling this issue led to pages where people asked to put this in resque.rb

`task "resque:setup" => :environment do`

`Resque.before_fork = Proc.new { ActiveRecord::Base.establish_connection }`
`end`

There were also a  few places which asked to do it in an after_fork. We have tried both of these and it still doesn't work. 

We believe its picking an empty connection but are unsure of how to debug further

**Comment by steveklabnik** [comment]
Hm, yes, this seems very strange. I am extra suspicious of it working in dev, but not staging.

**Comment by chrisccerami** [comment]
Was this issue ever resolved?

**Comment by jeremy** [comment]
Due to forking with an active db connection.
