### ISSUE TITLE
Airbrake handler calls .notify_or_ignore, which was removed from the airbrake gem

### ISSUE THREAD

**Issue by seanwalbran** [resque/resque#1428]
[This code](https://github.com/resque/resque/blob/0debc8193d7a26715cd55aa382b18ab5695fab6f/lib/resque/failure/airbrake.rb#L24) calls Airbrake.notify_or_ignore, which was [removed in the 5.x versions of the Airbrake gem](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#notify-or-ignore), in favor of simply `Airbrake.notify`.

**Comment by steveklabnik** [comment]
We've been wanting to remove the airbrake integration and make it a separate gem anyway.

**Comment by kitop** [comment]
@steveklabnik I'm glad to help here, as I have the same issue.
Would you prefer a PR fixing this (to account for both cases) or to create a separate gem now?

**Comment by steveklabnik** [comment]
Whichever works for you, frankly. Thanks so much for offering to pitch in!

**Comment by kitop** [comment]
Oh, actually the new airbrake already seems to provide this: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/resque/failure.rb

The tricky part, I guess, is how to tell your app to require that one and not the one provided by resque when you have airbrake >= 5.

**Comment by kitop** [comment]
Oh, spoke too soon. It's actually documented: https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#resque

I think that solves the issue, without doing anything :)
@seanwalbran does that work for you?

**Comment by seanwalbran** [comment]
Looks like it, thanks!

**Comment by steveklabnik** [comment]
Oh rad, even better :)

> The tricky part, I guess, is how to tell your app to require that one and not the one provided by resque when you have airbrake >= 5. 

I was planning on saying "This release removes airbrake support, but please drop in this gem and it will work". So if it's functionally equivalent, we can just do that.
