### ISSUE TITLE
Coveralls results seem...incorrect

### ISSUE THREAD

**Issue by chrisccerami** [resque/resque#1432]
According to the Coveralls results that were recently added, every method is uncovered by the test suite. I'm not sure what the deal is, but it seems like Coveralls isn't analyzing the test suite correctly. I'm going to attempt to look into this, but at the moment, ¯\ _ (ツ)_/¯

**Comment by crazymykl** [comment]
I bet it's to do with all the forking going on.

**Comment by chrisccerami** [comment]
This was caused by `Coveralls.wear!` not being placed at the top of `test_helper.rb`
