### ISSUE TITLE
Heroku: Redis::CommandError: ERR max number of clients reached

### ISSUE THREAD

**Issue by sajjadmurtaza** [resque/resque#1445]
Hello

Am facing Redis::CommandError: ERR max number of clients reached error on heroku. kindly guide me how i can fix it.

**Comment by chrisccerami** [comment]
Hi, unfortunately you haven't provided very much information to go on, but I'd suggest looking at https://github.com/resque/resque/issues/1226 first. Essentially what's happened is exactly what the error message says. You've reached the maximum number of Redis connections allowed by your Heroku plan. This is unlikely to be an issue with Resque.

**Comment by sajjadmurtaza** [comment]
Thank you so much lol, after 10 months

**Comment by fw42** [comment]
better late than never! Thanks for cleaning up @chrisccerami ❤️
