### ISSUE TITLE
Calling Worker.all or Worker.working causes workers to overwrite PIDFILE

### ISSUE THREAD

**Issue by jeremywadsack** [resque/resque#1446]
We just upgraded from resque 1.25.2 to 1.26.0 and suddenly some of our workers are overwriting the PIDFILE with each fork:

```
$ cat tmp/pids/resque_worker_prefetcher.pid
17278
$ ps aux | grep [1]7278
deploy   17278  4.5  0.7 605992 180332 ?       Sl   10:55   0:01 resque-1.26.0: Processing prefetcher since 1460656561 [MinimumPrefetcher]                                                                                                                        
deploy   31520  1.0  0.6 588980 171968 ?       Sl   10:15   0:25 resque-1.26.0: Forked 17278 at 1460656561                                                                                                                                                        
```

In this example, the recorded PID should be 31520, not 17278.

As we use monit to manage our workers this caused monit to continually launch new workers each time the fork terminated (after finishing the job). 

What's troubling me is that this only happens for some workers. I _think_ it's workers for which the queue has jobs in it when the workers start. Although it also seems to also be limited to jobs that run quickly (under a minute). This is making it hard for me to debug this, much less come up with a specific reproduction (but I will work on that).

I see that there was a [change to where PIDFILE was written](https://github.com/resque/resque/commit/7d0b20ee00986b749b03d4407af199039b504cc2) between 1.25.2 and 1.26.0, however, the code to write the pid is in the `initialize` method which shouldn't be called after `fork` which is called from `#work`. So I'm confused as to how this could even happen.

We are not using `BACKGROUND` and are depending on the shell (`&`) to background the workers.

I am going to keep digging into this to come up with a reproduction of the issue but I wanted to post this here in case anyone else has seen it or has thoughts of where I can look further for how this would happen.

**Comment by jeremywadsack** [comment]
I've narrowed this down to the use of `Worker.all` or `Worker.working`.

This only happens for some workers. Those workers are using an "inspector" class we wrote to check on the state of existing workers. This called `Reque.all` and `Reque::Worker.working`.

The code in those methods [call `#new` on the worker](https://github.com/resque/resque/blob/0d5389cb21744f59993af8f24d855a20d0e7b9ae/lib/resque/worker.rb#L57) which rewrites the PID file. Because we are calling those class methods from _within_ the running fork, they write the PID file. In fact, they end up writing the PID file many many times as they create a new instance of the worker from the _current_ process for each registered worker.

My suggested solution is that we remove all the BACKGROUND and PIDFILE code from `initialize` leaving it clean and simple, and make that a separate `prepare` method or something, that we can call from the rake task. Does that sound reasonable?

**Comment by chrisccerami** [comment]
I haven't been able to spend too much time looking at this yet, but reading your follow up clarifies a lot of things. I definitely think the approach you've brought up makes a lot of sense (again, with the limited amount of time I've spent looking into this so far).

**Comment by jeremywadsack** [comment]
Thanks for the quick follow up. I really appreciate that.

I'll put together a patch, test it in our environment, and open a pull request.

**Comment by chrisccerami** [comment]
:+1: I appreciate it.

**Comment by jeremywadsack** [comment]
I think we can close this as the PR has been merged.
