### ISSUE TITLE
Honeybadger possible severe impact on resque performance

### ISSUE THREAD

**Issue by paneq** [resque/resque#1451]
This is not exactly `resque` bug and you can close it immediately as `resque` developers cannot do anything to prevent it from happening. But I wanted people searching resque issues list to be able to find this problem easier in the future.

* http://blog.arkency.com/2016/04/how-i-hunted-the-most-odd-ruby-bug/
* https://github.com/honeybadger-io/honeybadger-ruby/issues/186
* https://bugs.ruby-lang.org/issues/12298

**Comment by steveklabnik** [comment]
Awesome, great story! Well done.

Since it's not a real bug, I'm going to give it a close, but thanks for filing the issue; I hope it helps others in the future.

**Comment by chrisccerami** [comment]
👍 That was great thinking @paneq.
