### ISSUE TITLE
Put task in the top of the queue

### ISSUE THREAD

**Issue by quolpr** [resque/resque#1453]
Is it able to put new task at the top of the queue? Or, may be, is there any functionalities which connected with job priority?

For now I have class `InstagramStatisticJob` - it grabs all data about instagram account, one `InstagramStatisticJob` per account. This task is running every 24 hours(if we have 1000 accounts, we will have queue with 1000 jobs). Also, it is running after user registration - only one job. So when user has registered in our system when all this 1000 jobs are running he would wait too many time. But if we will put job in the top of the queue - he will get result immediately. So how can I do it?

**Comment by chrisccerami** [comment]
I believe a similar issue/pull request has been opened previously and it was dismissed. I think currently the best/easiest way to accomplish something similar would be to have separate queues. You can add a high priority queue with more workers available and place these high priority workers there, or a nightly queue for your nightly jobs, this way they won't interfere with each other.

**Comment by quolpr** [comment]
Ok, I thought about that idea, thanks @chrisccerami . 
Will resque support in future job priority?

**Comment by chrisccerami** [comment]
I can't speak for everyone on the Resque team, but I believe this request was shot down recently, so probably not.

**Comment by Eunoia** [comment]
It's something that comes up fairly often, but it's not going to be part of resque. I saw an earlier issue asking for this feature, and wrote it, but I didn't see it's not going to get merged. 

Check out [this commit](https://github.com/Eunoia/resque/commit/25ee5b7f6bddd000f8fc7c128058a6268f1bbedc) to see how  `priority_push` is implemented. 

In the mean time, best thing to do is have a priority queue.
