### ISSUE TITLE
Resque::NoQueueError when there is a queue

### ISSUE THREAD

**Issue by EdmundLeex** [resque/resque#1460]
It happens pretty random. It goes away when I retried the failed job.

we are using 1.26.0 and have been having quite a bit of these recently. Initially it was limited to jobs there were on scheduler. So I suspected it was the bug on resque-scheduler.
https://github.com/resque/resque-scheduler/issues/169

But we have first seen one from a job that's not on scheduler.

**Comment by chrisccerami** [comment]
@EdmundLeex Would you be able to provide any more information? A stacktrace would be great, and any extra context you think might help someone look into this.

**Comment by EdmundLeex** [comment]
@chrisccerami I caught that from the cleaner. Unfortunately, it's not showing any stack trace there.

**Comment by jeremy** [comment]
Caused by job classes not being loaded when Resque scheduler is loaded, resulting in it enqueuing by class name and hence not being able to deduce which queue to use. To fix, ensure job classes are loaded at startup, or specify an explicit queue name for scheduler jobs.

**Comment by Uysim** [comment]
@jeremy How to ensure the job classes loaded at start up?

**Comment by Uysim** [comment]
Did anyone manage to fix it?
