### ISSUE TITLE
PIDFILE env variable causing conflict in Resque::Server

### ISSUE THREAD

**Issue by jweir** [resque/resque#1462]
Resque was recently upgraded and Resque::Server was returning an Internal Server Error. The problem is the `ngnix.conf` file has 

````
env PIDFILE=/var/run/nginx.pid
````

When Resque::Server initializes the worker, the worker is trying to write to `nginx.pid` which errors.

I believe this is the commit which introduced the error:
https://github.com/resque/resque/commit/7d0b20ee00986b749b03d4407af199039b504cc2

I reckon there is some initialization going on in the Resque::Worker which shouldn't occur when just trying to find a Worker.  https://github.com/resque/resque/blob/master/lib/resque/worker.rb#L132-L150

As a workaround I am just renaming the env variable in the nginx.conf.

Here is a portion of the trace

````
resque-1.26.0/lib/resque/worker.rb: 146:in `initialize'
resque-1.26.0/lib/resque/worker.rb: 146:in `open'
resque-1.26.0/lib/resque/worker.rb: 146:in `initialize'
resque-1.26.0/lib/resque/worker.rb:  94:in `new'
resque-1.26.0/lib/resque/worker.rb:  94:in `find'
resque-1.26.0/lib/resque/worker.rb:  56:in `block in all'
resque-1.26.0/lib/resque/worker.rb:  56:in `map'
resque-1.26.0/lib/resque/worker.rb:  56:in `all'
resque-1.26.0/lib/resque/worker.rb:  62:in `working'
resque-1.26.0/lib/resque.rb: 468:in `working'
tilt-1.4.1/lib/tilt/template.rb: 170:in `call'
tilt-1.4.1/lib/tilt/template.rb: 170:in `evaluate'
tilt-1.4.1/lib/tilt/template.rb: 103:in `render'
sinatra-1.4.6/lib/sinatra/base.rb: 822:in `render'
sinatra-1.4.6/lib/sinatra/base.rb: 666:in `erb'
resque-1.26.0/lib/resque/server.rb: 128:in `partial'
tilt-1.4.1/lib/tilt/template.rb: 170:in `call'
tilt-1.4.1/lib/tilt/template.rb: 170:in `evaluate'
tilt-1.4.1/lib/tilt/template.rb: 103:in `render'
sinatra-1.4.6/lib/sinatra/base.rb: 822:in `render'
sinatra-1.4.6/lib/sinatra/base.rb: 666:in `erb'
resque-1.26.0/lib/resque/server.rb: 147:in `show'
````

**Comment by chrisccerami** [comment]
I think #1448 should fix this.

**Comment by jweir** [comment]
Yes it should.  Thank you.
