### ISSUE TITLE
how to write a resque service with systemd? 

### ISSUE THREAD

**Issue by melotusme** [resque/resque#1467]
In /usr/lib/systemd/system/resque.servce, i wrote 
![image](https://cloud.githubusercontent.com/assets/10104231/15667817/c2c21476-274a-11e6-8fbd-cd6d4926e475.png)
But in the front end of resque-web, only one workers connected, while I start rake resqeu with four workers. I tried `Type=forking` and `Type=simple` in `[service]` in resque.service  and `BACKGROUND=yes` in the rake command, but it seems not working!

**Comment by melotusme** [comment]
In the terminal:
![image](https://cloud.githubusercontent.com/assets/10104231/15668010/c6710ce8-274b-11e6-9a72-ba4a8b04d041.png)

In the resque-web:
![image](https://cloud.githubusercontent.com/assets/10104231/15668053/e55571e4-274b-11e6-8f03-7713348257dc.png)

**Comment by goofansu** [comment]
This works.

```
[Unit]
Description=Resque jobs
After=redis.service

[Service]
# Foreground process (do not use --daemon in ExecStart or config.rb)
Type=simple

# Preferably configure a non-privileged user
# User=

# Specify the path to your puma application root
WorkingDirectory=/app/myapp

Environment=COUNT=2
Environment=QUEUE=*

EnvironmentFile=/etc/environment

# The command to start Puma
# Here we are using a binstub generated via:
# `bundle binstubs puma --path ./sbin`
# in the WorkingDirectory (replace <WD> below)
# You can alternatively use `bundle exec --keep-file-descriptors puma`
# ExecStart=/root/.rbenv/shims/bundle exec puma -b tcp://0.0.0.0:3000 -b ssl://0.0.0.0:9293?key=key.pem&cert=cert.pem

# Alternatively with a config file (in WorkingDirectory) and
# comparable `bind` directives
ExecStart=/root/.rbenv/shims/bundle exec rails resque:workers

Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by budmc29** [comment]
@goofansu answer is good if you are fine with hard coding the count and queue name, but if you need something dynamically assigned from rails use something like the service below.

**!!!** `Type=forking` is extremely important since each resque worker will create child processes.

```
[Unit]
Description=X Resque
Wants=mysqld.service
After=redis.service mysqld.service

[Service]
Type=forking
User=user_name
WorkingDirectory=/home/path_to_app
Environment=RAILS_ENV=production
SyslogIdentifier=x-resque

ExecStart=/home/user_name/.rvm/bin/rvm 1.9.3@gemset_name do rake environment resque:start_workers
ExecStop=/home/user_name/.rvm/bin/rvm 1.9.3@gemset_name do rake environment resque:stop_workers

Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by goofansu** [comment]
@budmc29 Thanks, nice job.

**Comment by jeremy** [comment]
Cool. Good one for the wiki!
