### ISSUE TITLE
Bundle broken

### ISSUE THREAD

**Issue by sepastian** [resque/resque#1475]
Hello,

I have updated resque and now I'm getting:

```
Fetching git://github.com/resque/resque.git
fatal: Could not parse object '6d35ee1d7d8e2498793393ae30b48dead8762755'.
Git error: command `git reset --hard 6d35ee1d7d8e2498793393ae30b48dead8762755` in directory
/home/admin/viddyoze.com/vendor/bundle/ruby/2.3.0/bundler/gems/resque-6d35ee1d7d8e has failed.
If this error persists you could try removing the cache directory
'/home/admin/viddyoze.com/vendor/bundle/ruby/2.3.0/cache/bundler/git/resque-841a12220f681ab6c7edba71d186ddfb64ee193f'
```

I'm using:

```
bundle show resque
/home/sebastian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/resque-6d35ee1d7d8e
```

Seems similar to https://github.com/stitchfix/resque-brain/issues/23

**Comment by sepastian** [comment]
And where did `1-x-stable` go??

I have production systems depending on this, and I may not be the only one... :/

**Comment by sepastian** [comment]
After reading [this](http://words.steveklabnik.com/rescuing-resque-again), I came across #1473.

Does this mean `1-x-stable` is gone and I simply have to switch to `master`?

**Comment by fw42** [comment]
> Does this mean 1-x-stable is gone and I simply have to switch to master?

yep!
