### ISSUE TITLE
Problem with resque performance on Rails 4.1

### ISSUE THREAD

**Issue by k1w1** [resque/resque#1482]
We are upgrading a Rails 3.2 app to 4.1 and we are seeing a dramatic reduction in resque performance.

It appears that the problem is because Rails 4 doesn't eager load classes in rake jobs (https://github.com/rails/rails/pull/11389/files) - so resque started from a rake job only loads classes on demand. This happens after the fork and so each job reloads the same classes, which in a large app can add seconds to the time for each job to run.

I am surprised that I haven't seen anyone else report this problem. Which makes me think that we must be missing something simple. I would love any ideas.

**Comment by jeremy** [comment]
The `preload` task explicitly eager-loads the app to work around this issue.
