### ISSUE TITLE
Cannot use with Rack 2.0 because of Sinatra.

### ISSUE THREAD

**Issue by ioquatix** [resque/resque#1492]
```
    resque was resolved to 1.26.0, which depends on
      sinatra (>= 0.9.2) was resolved to 1.1.0, which depends on
        rack (~> 1.1)
```

I guess we just need to either 1/ remove sinatra to a separate gem, or 2/ bump the sinatra dependencies.

**Comment by steveklabnik** [comment]
Gah. I've thought about moving resque-web out to a separate gem, but never got around to it.

**Comment by gbonfant** [comment]
Same issue with Rails 5.x 😭

**Comment by jairovm** [comment]
Same, I was trying to migrate my Rails 4 app to Rails 5 but I got stuck here :(

**Comment by fw42** [comment]
@rafaelfranca, how are we solving this?

**Comment by rafaelfranca** [comment]
Sinatra is really close to a release, so we can just way, until it is not released people can use the Sinatra master branch just fine (this is what we are doing in our application)

**Comment by MrHubble** [comment]
>until it is not released people can use the Sinatra master branch just fine

I believe to do this you simply use:
````
gem 'resque'
gem 'sinatra', github: 'sinatra/sinatra', branch: 'master'
````

as discussed in this issue: https://github.com/resque/resque/issues/1436

**Comment by rafaelfranca** [comment]
Yeah, exactly that.

**Comment by chrishough** [comment]
just checking in but this is still an issue in rails 5, wanted to keep everyone in the loop :)

**Comment by chrisccerami** [comment]
Do we still think Resque web should be extracted into its own gem?

**Comment by Tonkpils** [comment]
> Do we still think Resque web should be extracted into its own gem?

I feel that the web portion is essential for working with Resque. We would end up with always having to add the new web gem into the project anyway. We could remove the Sinatra dependency and go straight with rack. Any thoughts on that?

**Comment by rafaelfranca** [comment]
Sinatra 2 was released so this issue is now fixed.

I do think that using straight rack is a good idea, but I'm not maintainer of this gem to make this call since it will increase the work they will have to do.

**Comment by jesperronn** [comment]
What is the actual blocking code in resque-web, which prevents it from using Sinatra 2? 

I briefly looked into https://github.com/resque/resque/blob/master/lib/resque/server.rb and https://github.com/sinatra/sinatra/blob/master/CHANGELOG.md but couldn't see any obvious breaking changes.

Who is up to make an attempt for updating to Sinatra 2 (which could be a step in the direction of going to Rack directly)

**Comment by Tonkpils** [comment]
> What is the actual blocking code in resque-web, which prevents it from using Sinatra 2?

As far as I can tell, there's no issues on `resque-web` running Sinatra 2.

> Who is up to make an attempt for updating to Sinatra 2 (which could be a step in the direction of going to Rack directly)

I think the issue here was prior to Sinatra 2 being released. Now that this is released, the original issue is fixed. 

However, the original issue pointed out that using `resque` ties the user to the specific `rack` release the current Sinatra version is on. This can only be fixed if we move the gem out of using Sinatra and straight into Rack. 

I'm not a maintainer of this gem but I think this issue can be closed and, if necessary, an issue to move to rack can be opened.
