### ISSUE TITLE
LoadError: No such file to load -- application_cable/channel

### ISSUE THREAD

**Issue by stowns** [resque/resque#1498]
Using rails 5.0.0 and attempting to run `QUEUE=* rake resque:work` it's not picking up the scaffolded Channel. Any idea of what is happening here?

``` ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end
```

```
l/gems/bundler-1.7.6/lib/bundler/runtime.rb:76)
** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Execute resque:setup
** Execute resque:preload
rake aborted!
LoadError: No such file to load -- application_cable/channel
```

**Comment by ewollesen** [comment]
I had to add the `environment` rake task to get mine to work, so: ```$ QUEUE=* rake environment resque:work```

**Comment by fw42** [comment]
Doesn't sound like a resque bug to me... can we close this?

**Comment by vovkats** [comment]
@stowns I have got this error too

**Comment by brndn4** [comment]
I was seeing the same error with this command: 
`COUNT=5 INTERVAL=0.3 VERBOSE=1 QUEUE=* rake environment resque:workers`

I fixed it by adding
```
require 'resque/tasks'
task 'resque:setup' => :environment
```
to lib/tasks/resque.rake

ruby 2.2.2, rails 5.0.0.1, redis 2.8.19, resque 1.27.1

**Comment by chrisccerami** [comment]
@brndn4 That worked for me as well when trying this in a Rails 5.0.1 app. I'll add this info to the Readme and we can close this issue.

**Comment by hahmed** [comment]
Just in case it helps anyone else, I am using rails 5.1.0.rc1 and wanted this to work on heroku.

In my Procfile i added:
resque: env TERM_CHILD=1 RESQUE_TERM_TIMEOUT=7 bundle exec rake QUEUE=* environment resque:work
