### ISSUE TITLE
Suggestion: Detach from Rakefile

### ISSUE THREAD

**Issue by DannyBen** [resque/resque#1504]
Are there any thoughts about removing the dependency in a Rakefile to run?

I mean, Resque is nicely designed to run as a standalone tool, without forcing any Rails environment or anything, but still the need to run in a folder with a Rakefile seems unnecessary and more like a remnant from older design, when it was more coupled with Rails (just a guess...).

I saw there is a `resque` binary installed with the gem, and I expected it to have `resque work` instead of the need to run `rake resque:work`

For context, I opened this StackOverflow question: [Running resque without Rakefile](http://stackoverflow.com/questions/39083764/running-resque-without-rakefile).

As far as I understand, it would just mean copying/moving the code from [`lib/resque/tasks`](https://github.com/resque/resque/blob/master/lib/resque/tasks.rb#L9) to [`bin/resque`](https://github.com/resque/resque/blob/master/bin/resque)

**Comment by steveklabnik** [comment]
With the now-defunkt Resque 2, I wanted to switch to its own binary, but never finished the work.

**Comment by chrisccerami** [comment]
I'm not sure what the benefit would be here. What problem is it that you'd like solved?

**Comment by DannyBen** [comment]
> I'm not sure what the benefit would be here. What problem is it that you'd like solved?

Well... I think the question should be the other way around: What is the benefit in keeping a dependency in Rake?

But, to still try and answer (to the best of my knowledge):

1. I do not know of any other (non-rails) gem that provides its CLI interface exclusively through Rake
2. A dependency in having a Rakefile means that I have to "roll my own" CLI if I am to use resque outside of a Rails context.
3. If I want to maintain all of the tasks that you have already defined in your rake tasks, means I have to have a folder with a Rakefile that includes your tasks, which in turn means that this CLI of mine can only be executed from the same folder that holds the Rakefile.

When you want to use resque as a standalone job server, without rails, you currently have to create your own Rakefile, and include the tasks and what not. A snippet of this solution is in my [self-answered question on StackOverflow](http://stackoverflow.com/a/39101502/413924).

If resque is intended to also support standalone use - outside of rails - then the common behavior of such gems is to provide a binary (or rather an executable 'bin' script) of their own that controls all aspects of the application.

It looks like resque is not far from providing it, and as @steveklabnik mentioned, he thought the same and just never finished it.

For additional context I will say that my use case is this:

I have developed a job server for our internal use, which is in fact a simple command line wrapper around resque, with commands copied (and adjusted) from your rake tasks. 

This CLI is capable of starting/stopping the web server, and adding jobs. This way all my other apps can simply push jobs to this server, no matter what language they are written in.

The usage of this CLI interface is this:

```
$ jobserver
Usage:
  jobserver start [--port N]
  jobserver stop
  jobserver work [QUEUE]
  jobserver add JOB [PARAMS...]
  jobserver (-h|--help|--version)
```

**Comment by jeremy** [comment]
A CLI wrapper is welcome, though we'd likely just invoke Rake tasks for compatibility (and hookability) 😊
