### ISSUE TITLE
Pessimistic version constraint on sinatra dependency

### ISSUE THREAD

**Issue by njam** [resque/resque#1505]
Currently the version constraint in the gemspec is:

```
s.add_dependency "sinatra", ">= 0.9.2"
```

Yesterday [sinatra 2.0.0.beta1](https://rubygems.org/gems/sinatra/versions/2.0.0.beta1) was released, which will be installed when installing resque.

This is problematic because this "sinatra 2.0.0.beta1" requires a new gem "mustermann 1.0.0.beta2" which requires "Ruby >= 2.2.0".

Could the dependency be changed to something like `~> 1.0` or even `~> 1.4.7` here?

cc @kris-lab

**Comment by njam** [comment]
Master is still using `"sinatra", ">= 0.9.2"`, which I think is a bit dangerous.
What's the reason you don't want to use a pessimistic version constraint?

**Comment by chrisccerami** [comment]
As, I saw the merged PR and didn't look very closely at it. I agree we should probably use `~> 1.0`.

**Comment by timpbrenner** [comment]
Is there any update on this versioning?

**Comment by jeremy** [comment]
If Resque is compatible with Sinatra 2 beta, our version requirements should reflect that. Pessimistic versioning can sound good on paper, but in practice open-ended versioning has worked very well to date, avoiding the transitive dependency gridlock that so many foundational libraries find themselves mired in.

If a dependency pulls in another dep with an unsatisfiable Ruby version requirement, we should be looking to RubyGems and Bundler for resolution. The interim workaround is for Resque users to explicitly limit Sinatra to a version that's compatible with their Ruby version.
