### ISSUE TITLE
resque:workers doesn't work

### ISSUE THREAD

**Issue by fuminori-ido** [resque/resque#1507]
Dear,

I have two questions.

1) When I run resque:workers as folow:
`$ COUNT=3 QUEUES=critical,high,low bundle exec rake environment resque:workers`
   Then, following erros are displayed:

```
rake aborted!
NoMethodError: undefined method `require_dependency' for #<MyApp::Application:0x00559529efcf40>
…
```

  version and environment is as follows:
- resque: 1.26.0
- os: CentOS 6.7

2) To run multiple workers, Using COUNT=\* is just for development mode as lib/resque/tasks.rb comment says as follows:

```
  desc "Start multiple Resque workers. Should only be used in dev mode."
  task :workers do
    …
```

Could you let me know how to run multiple workers in production mode?

Thank you for your feedback.

**Comment by chrisccerami** [comment]
Is this a Rails 5 app? If so, can you try using the latest version of Resque?

**Comment by celesteking** [comment]
yes it is. 1.27.4. same err.

**Comment by jeremy** [comment]
See #1265.
