### ISSUE TITLE
any plans to cut version 1.27.0 of gem soon?

### ISSUE THREAD

**Issue by MishaConway** [resque/resque#1509]
The current master revision includes this fix (https://github.com/resque/resque/pull/1480/commits/bfd6b5a37c2d9a4d3bab30e793c7d5d25d8445d7)  that addresses a pretty annoying issue in 1.26.0

Additionally, there is a resque plugin I am working on that depends on what is currently in master.

If you don't feel comfortable releasing in the near time frame, that is fine and I can work around for the time being. Was just curious if there were plans before I set out on that path.

**Comment by martinstuecklschwaiger** [comment]
Also in #1469 fixes an ugly bug in the resque-web, a new release would be highly appreciated.

**Comment by jeremywadsack** [comment]
Or even a 1.26.1 release, because #1448 also fixes a bug which was introduced in 1.26.0.

**Comment by rhymes** [comment]
Any news?

**Comment by rx** [comment]
We are in need of a new release to fix: #1429
Bump.

**Comment by oehlschl** [comment]
Also in need of new release to fix requeue_all behavior for multiple failure backends.

Regression introduced in 1.26: https://github.com/resque/resque/commit/84a0ce41df90922526ec8a70f0e4c5afcec517c3#diff-f384147196b88f2c83e38e710f7bf041R208

Fix only in master:
https://github.com/resque/resque/commit/0bdcdb466e73f3dd68527b29c3a1c51b8e5516cc

**Comment by kstevens715** [comment]
I'm in the same boat. I'm having to parse `Worker#to_s` myself because of #1304. I don't really like having to reply on being able to parse that in my code. Using `Worker#hostname` would definitely be preferable.

**Comment by chrisccerami** [comment]
1.27.0 was released a few days ago.
