### ISSUE TITLE
mount multip redis-server's to an app

### ISSUE THREAD

**Issue by srklonaris** [resque/resque#1513]
It is possible to `mount Resque::Server.new, :at => "/resque"'` multiple times in an app with different redis servers?

I have `Resque.redis` set to one instance of redis which the server dashboard uses, but I want to mount a second dashboard pointing at a different instance of redis.

**Comment by fw42** [comment]
yes, it's possible, we are doing the same thing at Shopify. We are mounting to a controller which then calls into `Resque::Server.new` "manually" (after switching `Resque.redis` to the connection that we want).

**Comment by srklonaris** [comment]
Can you show a small example?  How do I mount to a controller?

**Comment by fw42** [comment]
Something like this:
```ruby
mount YourRailsController.action(:index), at: '/resque'
```
and then
```ruby
class YourRailsController
  @@resque = Resque::Server.new

  around_action :with_resque_redis

  def index
    status, headers, body = @@resque.call(request.env)
    buffer = ""

    headers.each { |name, value| response[name] = value }
    body.each { |chunk| buffer << chunk }

    render :status => status, :text => buffer
  end

  private

  def somehow_decide_which_redis_you_want(params)
    # ...
  end

  def with_resque_redis
    old = Resque.redis
    Resque.redis = somehow_decide_which_redis_you_want(params)
    yield
  ensure
    Resque.redis = old
  end
end
```

Haven't tested this exact code, and it's a bit hacky, but something very similar to this works well for us.

**Comment by srklonaris** [comment]
Thank you! This is helpful!

**Comment by srklonaris** [comment]
@fw42 Does this solution not cause a race condition for the time in between switching Resque.redis connections and queueing Resque tasks on the default connection?

**Comment by fw42** [comment]
if you are using multiple threads then yes, it does. but we aren't. sorry, I should have mentioned that.

**Comment by srklonaris** [comment]
Thanks
