### ISSUE TITLE
Missing workers in web ui

### ISSUE THREAD

**Issue by nextofsearch** [resque/resque#1519]
Hi,

My 7 resque workers run fine and I can see them in web-ui after deployment. I have configured monit to watch the workers and start them if something goes wrong. I use the same scripts I use when deploying the code, which look like ones below:

To start a worker
`/bin/su - deployer -c 'cd /home/deployer/apps/worker-rails3/current && /usr/bin/env nohup ~/.rvm/bin/rvm ruby-1.9.3-p551@rails3.1 do bundle exec rake RAILS_ENV=production QUEUE=\"*\" PIDFILE=/home/deployer/apps/worker-rails3/shared/pids/resque_work_1.pid BACKGROUND=yes INTERVAL=5 environment resque:work >> /home/deployer/apps/worker-rails3/shared/log/resque.log 2>> /home/deployer/apps/worker-rails3/shared/log/resque.log'`

To stop a worker
`/usr/bin/env kill -s QUIT $(/usr/bin/env cat /home/deployer/apps/worker-rails3/shared/pids/resque_work_1.pid); rm /home/deployer/apps/worker-rails3/shared/pids/resque_work_1.pid`

When monit revives a dead worker, a weird thing happens . In web-ui, nothing but the newly started worker is displayed. Others are all gone from web-ui but they work just fine.

FYI, there are 2 rails apps: one for dashboard with resque web-ui and the other for resque workers.

resque 1.26.0 | redis 3.3.1

Any idea?

**Comment by davegudge** [comment]
@nextofsearch I was experiencing an issue with multiple resque workers (for the same queue) in resque 1.26.0. Hopefully my [comment](https://github.com/resque/resque/issues/1357#issuecomment-255968915) on [issue #1357](https://github.com/resque/resque/issues/1357) will help?

**Comment by nextofsearch** [comment]
@davegudge Thanks for the comment. I will try 1.25.2 and/or #1480 since I have another open issue #1521
