### ISSUE TITLE
What Ruby versions should we continue supporting?

### ISSUE THREAD

**Issue by chrisccerami** [resque/resque#1526]
I figured I'd open an issue for this since it's probably the easiest way to track discussion on it. I've been trying to decide if I think it makes any sense for Resque to continue actively supporting some of the older EOL Rubies. I feel like 1.8.7 is so far past its prime that it's probably putting more of a burden on contributors and maintainers than any potential benefit of pushing upgrades to 1.8.7 users, so in my opinion, dropping 1.8.7 seems pretty reasonable.

1.9.3 is similarly EOL, but I'm not sure how large of a base there is of people still using it, and a similar point can be made about 2.0.x, which was EOL'd in February of this year.

So the main point of contention, I suppose, is do we keep updating Resque for EOL Rubies, or do we just allow those users to lock their version at `1.26.0` and move on to focusing on supported versions?

**Comment by rjhancock** [comment]
I'd suggest dropping support for any version of Ruby that is no longer being supported.

**Comment by steveklabnik** [comment]
Historically speaking, a lot of resque's value is in legacy. That doesn't mean that every Ruby till the dawn of time should be supported, but it'd be nice to try and figure out some way to figure out what Rubies resque users use.

I'd also recommend that moving to a 2.x is a good idea if 1.8 support is gonna be dropped.

**Comment by rjhancock** [comment]
Then I'd stop at 2.0. Granted I'm working on a project that still runs on 1.8.7, but it's slowly moving to 2.0 (then newer after that).

**Comment by chrisccerami** [comment]
Yeah, I'm certainly not trying to argue that Resque should only support latest and greatest. I agree Steve, that it would be great if we had some kind of stats on what Rubies Resque users are on.

**Comment by IAMALLWE** [comment]
I Know WHY family, I Forgive IGNORANCE. PRIDE is a mocker, strong drink a brawler, and whoEvEr is led astray by them Is A FOOL too. Bf4ore Wise there First must be Fool (Jester) Be ALL things to ALL people. You SEE NAMASTE PEACE

**Comment by pboling** [comment]
I have a large resque installation on ruby-2.0.0, and will likely be for another few months.  I think stopping at 2.0.0 is reasonably (biased!).

**Comment by wjessop** [comment]
+1 for Ruby 2 minimum. Anything older is ancient.

**Comment by IAMALLWE** [comment]
🎹

**Comment by claui** [comment]
I’d love for Resque to continue supporting **Ruby 2.0.0 and above.**

A large number of macOS users is basically locked into Ruby 2.0.0 today as it’s baked into all recent macOS versions including the latest one, Sierra. Apple also made Ruby 2.0.0 undeletable via System Integrity Protection. The average end user hardly has a chance to install and manage a second Ruby version in parallel while keeping his or her sanity.

While nothing of the above is obviously Resque’s problem in any way, and I think it’s fair to argue that Apple is 100 % responsible for exposing their customers to an insecure legacy mess like this, it would still simply affect too many end users if Resque were to drop support for Ruby 2.0.0, despite the latter being hopelessly outdated.

**Comment by wjessop** [comment]
I'd be surprised if there were many people running system Ruby when [rbenv](https://github.com/rbenv/rbenv#homebrew-on-mac-os-x) is available and easy to install. From my Sierra machine:

    $ ruby -v
    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

The instructions are [readily available out there](http://guides.railsgirls.com/install#setup-for-os-x) and could just be linked to in the README in the same section as the minimum version of Ruby is discussed.
