### ISSUE TITLE
Not able to login in Heroku CLI

### ISSUE THREAD

**Issue by mukeshdutt** [resque/resque#1529]
I'm using Heroku first time. I got tutorial and first I've installed CLI then i tried to login but following issue was occured then i set HTTP_PROXY and HTTPS_PROXY but i'm still not able to login.
 
Enter your Heroku credentials.
Email: mukeshdutt5@gmail.com
Password (typing will be hidden): 
 ▸    Post https://api.heroku.com/login: http: error connecting to proxy https://api.heroku.com:53: dial tcp: lookup api.heroku.com on 127.0.1.1:53: read udp 127.0.0.1:47890->127.0.1.1:53: i/o timeout

**Set values**
export HTTPS_PROXY="http://golangexample.herokuapp.com"
export HTTPS_PROXY="https://golangexample.herokuapp.com"

**Tried again**
Enter your Heroku credentials.
Email: mukeshdutt5@gmail.com
Password (typing will be hidden): 
 ▸    Post https://api.heroku.com/login: unexpected EOF

**Comment by fw42** [comment]
what does this have to do with resque?

**Comment by liaodalin19903** [comment]
@mukeshdutt  Have you solved it ?
