### ISSUE TITLE
Can't query failed jobs on specific queue

### ISSUE THREAD

**Issue by toppy42** [resque/resque#1532]
The [documentation](http://www.rubydoc.info/gems/resque/Resque%2FFailure.all) for getting failed jobs says that it accepts "queue" as an argument.  My assumption was that it would only return failures from the queue I specified, but it doesn't seem to do that.

Apparently, it only accepts "failed" as a valid queue argument which seems a bit silly: 
https://github.com/resque/resque/blob/master/lib/resque/failure/redis.rb#L118

Any chance of changing the queue argument to be a filter?  If not, it would probably be good to remove queue as an argument from the "all" method

Thanks!

**Comment by chrisccerami** [comment]
I agree it's a bit silly, and probably left over from a previous design, but we can't safely remove that argument without breaking backwards compatibility. Also, as far as I can tell, the queue is only limited to "failed" for the Redis failure backend. I'm not entirely sure how the `queue` argument is used in other backends, like Airbrake.

**Comment by chrisccerami** [comment]
If I think about it, I'm not entirely sure the request here makes sense either, because I believe a Failed job isn't in any queue anymore besides "Failed", so I don't think you can filter by any sort of queue.

**Comment by toppy42** [comment]
My request was more along the lines of querying failed jobs by originating queue.  For instance, when polling a queried job to present the status to the user, if I want to see if a job has failed I have to query all failed jobs and filter them for the ones relevant to the user.
