### ISSUE TITLE
Redis 2.4: Redis::CommandError: ERR unknown command 'time'

### ISSUE THREAD

**Issue by tf** [resque/resque#1537]
[This recent change](https://github.com/resque/resque/commit/47bce253ebc23df93329de4979392a065b701b3b#diff-102541f6f2ba476fceb8e45917e63420R93) by @fw42 appears to be breaking Resque on Redis 2.4 for me.  Though I do not know the details of the change, the `time` command is [only available as of Redis 2.6](https://redis.io/commands/time). Has support for Redis 2.4 been dropped? Where do find out more about Resque's supported Redis versions?

**Comment by chrisccerami** [comment]
Hm, I don't think support was intentionally dropped but Redis 2.4 is a pretty old Redis. Redis 2.6 was released in 2012, and Redis generally doesn't support for more than one stable release back. Current stable Redis is 3.2, which means that back to 3.0 is supported by the Redis team.

We should probably keep track of what versions of Redis will work with Resque, but I don't think anyone has done that work.

**Comment by tf** [comment]
Engine Yard provides Redis 2.4 by default as part of their v4 stack, so I
guess it is still in use. We will probably have to use an old resque
version then.

Chris C Cerami <notifications@github.com> schrieb am Di., 14. Feb. 2017,
21:35:

**Comment by chrisccerami** [comment]
If Redis 2.4 is still widely used, we can also attempt to fix that problem in a future patch version of Resque. I don't know what exactly a potential solution would be, but I'd think @fw42 would know if there is a fix.

**Comment by danbernier** [comment]
I'm currently seeing this with Redis 3.2.6, using the redis gem 3.3.3.

**Comment by chrisccerami** [comment]
That's interesting. There is definitely a TIME command as of Redis 2.6.0, as seen [here](https://redis.io/commands/time), so if this issue is happening on newer Redis then something is clearly wrong. I'll try to take a look at it today.

**Comment by danbernier** [comment]
Ah - I stand corrected, apologies. The server I'm seeing this issue on is, in fact, running 2.4. Urgency downgraded.

**Comment by chrisccerami** [comment]
That's a relief 😆 this almost became a much weirder issue.

**Comment by chrisccerami** [comment]
I've been thinking about this some more, and I'm not even really sure how we could guarantee that we don't break things for older versions of Redis. I can't think of a reasonable way to have Travis test Resque across multiple Redis versions, since our tests don't run on an actual Redis connection anyway. This may just be the kind of issue that we'll need to catch after the fact, or be more careful about ahead of time. This also raises the question of "what Redis versions do we want to support?", which is something I don't think anyone's talked about before.

**Comment by chrisccerami** [comment]
This has now been fixed in Resque 1.27.2.
