### ISSUE TITLE
support calling select on redis

### ISSUE THREAD

**Issue by allenlsy** [resque/resque#1549]
`Resque.redis.select` method does not work

If I call `Resque.redis.select(1)`, the code goes to `data_store.rb`. The `sym` is `:select`, and `args` is `["1"]`. Then the error is:

```
TypeError: wrong argument type String (expected Array)
```

So my quick solution is to change the `method_missing` method. This is a monkey patch, and it should be a long-term solution. 

I'm using Ruby 2.3.1, and also tried on 2.4.0. They both have this issue.

```
    def method_missing(sym,*args,&block)
      # TODO: deprecation warning?

      if sym == :select
        @redis.select(args.first)
      else
        @redis.send(sym,*args,&block)
      end
    end
```

**Comment by chrisccerami** [comment]
I have to admit I don't understand this proposed fix. If `sym` is select, then calling `@redis.select` or `@redis.send(sym)` should do the same exact thing, and if `args` is `["1"]` then `*args` and `args.first` will both send `"1"`. I don't see how this change to method missing can fix the problem you describe.

**Comment by jeremy** [comment]
`Resque#redis` returns a `Redis::Namespace` wrapper, so if a Redis client method is not working via `Resque.redis.methodname`, then it's a [redis-namespace](https://github.com/resque/redis-namespace) issue.

Could you try with current redis-namespace library and raise the issue there if it still fails?

**Comment by jeremy** [comment]
Ah, not quite! The Redis::Namespace wrapper is again wrapped by Resque::DataStore, whose method_missing is intending to deprecate its usage as an actual Redis instance. Quite confusing.

We're better off visibly deprecating this usage rather than tweaking this awkward proxy.
