### ISSUE TITLE
resque jobs queue during deployment

### ISSUE THREAD

**Issue by NidhiArien** [resque/resque#1553]
What happens to queued resque jobs during a deployment? We have a RoR4 app that uses resque and resque_scheduler. I see that in dev and test environments if you redeploy the app to the server, the queued jobs are getting lost. Am I missing a config files somewhere? Is there a way I can programmatically pause jobs being processed?

**Comment by fw42** [comment]
> queued jobs are getting lost

That should never happen. It might depend on how you deploy, but I think a common strategy is to send a signal to the resque process, asking it to terminate. That will lead resque to continue working on the job that it's currently working on, and then quit after that (and not pick up new jobs, even if the queues aren't empty). Usually the deploy would then bring up a new worker (with the new version of the code) which will start working on the queue again.

So worst case, if you are doing it wrong and your deployment might shoot the worker in the head, in which case you might lose the job that it's currently working on, but the jobs in the queue that haven't been popped yet should not be affected by that at all.

**Comment by NidhiArien** [comment]
@fw42 Thank you for the prompt reply. Would it be possible to share the 'terminate a resque process' command? From whatever I have read so far, seems like a shell script is the way to go: 


sudo kill -9  `ps aux | grep [r]esque | grep -v grep | cut -c 10-16` from http://www.kensodev.com/2011/09/17/kill-all-resque-workers-with-a-single-command/ is that the only option we have?

**Comment by fw42** [comment]
Use `kill`, not `kill -9`, otherwise the worker has no chance to react to the signal in order to shut down gracefully.
