### ISSUE TITLE
[Question] Update the Readme + Heroku instructions about the signals

### ISSUE THREAD

**Issue by Erowlin** [resque/resque#1554]
Hi, 

Not really an issue, more like a question and a suggestion to improve the readme. 

We're struggling about the fact that Heroku kills our workers before they can gracefully finish their job (It seems that the `RESQUE_TERM_TIMEOUT` is not working for us, for an unknown reason). That's when we found the awesome blog post from **Grouper** and their fix that's been merged (https://github.com/resque/resque/pull/1514). 

1- The readme is not really clear on what are the differences between `RESQUE_PRE_SHUTDOWN_TIMEOUT` and `RESQUE_TERM_TIMEOUT`. 
- Can you explain me what is their goal ? Even by reading the code, I can't figure it out clearly. 
- Should I use both or only one of them? 
- I've read multiple experience of people that cannot make their worker not be killed after 8 seconds by Heroku, is `RESQUE_PRE_SHUTDOWN_TIMEOUT` gonna increase that delay?

2- The mailing list indicated in the Wiki is not working anymore. We should update it to remove the reference / update it to a new one. 

3- The [Heroku page](https://devcenter.heroku.com/articles/queuing-ruby-resque) about Resque is outdated, it does not include the `RESQUE_PRE_SHUTDOWN_TIMEOUT` variable. How can we update it? I would love to contribute but I don't know how to do it. 

Thank you!

**Comment by Erowlin** [comment]
Hey, is Resque still maintained? Thx :).

**Comment by chrisccerami** [comment]
Resque is indeed still maintained. This comment from `lib/resque/worker.rb` I feel adequately explains the difference between `RESQUE_PRE_SHUTDOWN_TIMEOUT` and `RESQUE_TERM_TIMEOUT`:

```ruby
    # Kills the forked child immediately with minimal remorse. The job it
    # is processing will not be completed. Send the child a TERM signal,
    # wait <term_timeout> seconds, and then a KILL signal if it has not quit
    # If pre_shutdown_timeout has been set to a positive number, it will allow
    # the child that many seconds before sending the aforementioned TERM and KILL.
```

I can remove the reference to the mailing list from the wiki, but we have no control over Heroku's documentation. I don't know who you would contact over there about getting it updated.

**Comment by Erowlin** [comment]
Ah awesome comment, thank you for linking it. 
I will see with Heroku if there is any way to update the documentation.
