### ISSUE TITLE
Connect to a REDIS server with password

### ISSUE THREAD

**Issue by stringo** [resque/resque#1564]
Hi,

I'd like to connect to a REDIS instance with password protection.

I've found this answer for the same scenario. Is this answer still valid?

https://github.com/resque/resque/issues/148

Thanks.

**Comment by Tonkpils** [comment]
How are you attempting to connect currently? Resque allows you to connect through a connection string or an object to re-use an existing connection.

You could do something like

```
Resque.redis = 'redis://username:password@localhost:port'
```

or 

```
Resque.redis = Redis.new(...)
```

as the PR you linked mentions.

Have you tried any of these options or are you running into any issues?
