### ISSUE TITLE
Error when attempting to run the first time

### ISSUE THREAD

**Issue by jackjackattack** [resque/resque#1565]
I just installed pow and resque and I am getting this error

Redis::CannotConnectError at /overview
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
file: client.rb location: rescue in establish_connection line: 345

**Comment by fw42** [comment]
Is your Redis server running (on that port)?

**Comment by jackjackattack** [comment]
Duh, I guess it would be helpful if I actually read the error.  Thanks.

**Comment by Tonkpils** [comment]
@jackjackattack can this be closed?
