### ISSUE TITLE
Possible XSS for web panel

### ISSUE THREAD

**Issue by icotanchev** [resque/resque#1569]
Web panel does not sanitise URL inputs for FireFox browser. For example:
```
/resque_proxy/overview/<img src="x" onmouseover="alert('XSS')">
/resque_proxy/queues/<img src="x" onmouseover="alert('XSS')">
```
cause execution of the JS
![screen_shot_2017-06-14_at_11 47 34](https://user-images.githubusercontent.com/1942419/27123943-106fed60-50f8-11e7-98e6-d5e5f10094e7.png)

**Comment by jeremy** [comment]
https://github.com/resque/resque-web issue.
