### ISSUE TITLE
can't access external binaries from Resque job

### ISSUE THREAD

**Issue by ayb** [resque/resque#1576]
I'm trying to access an external binary file from my Rails app via a Resque job.  Specifically, to parse mjml files.

MJML has a binary and I am able to use it within my Rails app to parse templates.  Basically the server saves a temp file and runs it through the parser, which generates HTML and is then sent as an e-mail.

I have it set up to deliver e-mails via `deliver_now` etc. and it works fine in my app in production.

However if I try to use `deliver_later` (which is set to use Resque) or use `deliver_now` within a Resque worker, it blows up.

Seems like my Resque environment is not able to access/find the mjml binary which my main Rails app is able to access just fine.

When I do a simple test such as run `which mjml` or `/usr/bin/which mjml` and message me the response via Slack, it returns null.  So it seems like it cannot access the external resource.

Is this a configuration issue on my part?  Or is this a limitation for how the Resque workers operate?

**Comment by chrisccerami** [comment]
I don't have a lot of insight into this problem, but I have some questions that might help us to get to a solution. Do you have this problem when you're trying to access the binaries from a Resque worker even when running in development? Do you typically run your Resque workers on a different server/machine from your app code?

If you could create a minimal reproduction repo that makes it easy to see this issue, I could take some free time and try to fix it.

**Comment by ayb** [comment]
Thanks for the response:

Production is an Ubuntu 14.04 box

Resque workers operate on the same machine as the main Production Rails app

Everything seems to work fine in development, including via Resque (i.e. `deliver_now` and `deliver_later`)

In production it works fine without Resque (i.e. `deliver_now`) but NOT when sending via Resque (`deliver_later)

I will work on a minimal production repo

**Comment by chrisccerami** [comment]
Hm, interesting, so you're able to access to binaries from within your Resque workers in your development environment but not in production?

**Comment by ayb** [comment]
Yes

Also I did a test this morning running my Rails environment and Resque workers in Production on my local machine (Macbook) and everything worked fine

Added a bunch more verbose logging and from what I can see I am getting no response back when trying to execute shell commands from within Resque workers

General flow is:
- queue message via `deliver_later`
- Resque takes it and runs it as `deliver_now`
- email template gets saved
- worker tries to execute a command such as this:  `/home/rails/.nvm/versions/node/v8.3.0/bin/mjml /home/rails/releases/20170821111608/tmp/mjml-in-20170821-07:17:26:239-617.mjml -o /home/rails/releases/20170821111608/tmp/mjml-out-20170821-07:17:26:239-688.html`
- command does not run / gets no response
- job fails

I've been testing different ways to run the commands from within Resque to see if one works vs others

For example, backticks don't seem to work

I just tested using `system()` i.e. `system("/home/rails/.nvm/versions/node/v8.3.0/bin/mjml /home/rails/releases/20170821111608/tmp/mjml-in-20170821-07:17:26:239-617.mjml -o /home/rails/releases/20170821111608/tmp/mjml-out-20170821-07:17:26:239-688.html")` and the worker got FALSE as a response

Now if I try that same line in production console on the production server (either using backticks or `system()`) it works fine.

Could this be some sort of Ubuntu 14.04 constraint/issue?  The environments between my local machine and production are very similar but the OS is the biggest differentiator.

**Comment by ayb** [comment]
Did a test this morning where I setup a job to with a queue_adapter of :async

I was able to run that job and send an e-mail via `deliver_now` and it worked fine via the external adapter

So pretty sure I've isolated this behavior to:
- Rails 5.1 ActionMailer via ActiveJob (deliver_later)
- via Resque
- on Ubuntu 14.04

**Comment by jeremy** [comment]
Looks like your commands are executing fine—they're just failing 🙃

`Kernel#system` returns false when it gets a nonzero exitstatus from the process. That happens when it hit an error.

Dig in and troubleshoot why the process you're spawning isn't working. Resque is only involved insofar as that's where you're spawning the process.
