### ISSUE TITLE
Unable to override Redis configration from resque.yml, picking up default host & port

### ISSUE THREAD

**Issue by vgarg231** [resque/resque#1578]
Here are the gem versions I am using

```
    redis (3.3.3)
    redis-namespace (1.5.3)
      redis (~> 3.0, >= 3.0.4)
    resque (1.27.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-scheduler (4.3.0)
      mono_logger (~> 1.0)
      redis (~> 3.3)
      resque (~> 1.26)
      rufus-scheduler (~> 3.2)
    resque-web (0.0.9)
      coffee-rails
      jquery-rails
      resque
      sass-rails
      twitter-bootstrap-rails
```

This issue is similar to[ resque-is-not-picking-up-redis-configuration-settings ](https://stackoverflow.com/questions/10922197/resque-is-not-picking-up-redis-configuration-settings)

**Comment by om-nishu-trantor** [comment]
You must be using an older version of resque-web.
They fixed this issue in the latest build, also mentioning the issue in comment [here](https://github.com/resque/resque-web/blob/master/config/initializers/resque_config.rb#L3)

**Comment by om-nishu-trantor** [comment]
Just upgrade to the latest version (0.0.11 while writing this reply), and you will be sorted.

**Comment by vgarg231** [comment]
yes it works thanks
