### ISSUE TITLE
Resque-Scheduler

### ISSUE THREAD

**Issue by dimasusername** [resque/resque#1579]
Guys, what's up with resque-scheduler project? There is a bunch of pull requests and issues and latest release was out last June? After upgrading to latest resque my tasks aren't even run and I get error starting the script.

Is there an active maintainer for the project? Is there an alternative?

**Comment by fw42** [comment]
Not sure about active maintainer, but fwiw at Shopify we are using the latest release of resque together with the latest release of resque-scheduler in production and it works fine.

Please open an issue for the error you are getting when "starting the script" (and describe what that means exactly and how to reproduce it).

**Comment by dimasusername** [comment]
@fw42 thanks for the reply. I'll open the issue there. As it turned out the error I was getting at startup was a minor one, and the current version works fine for us, too (although it failed to process delayed items completely under high load and insufficient resources several times). The state of the repo is nonetheless worrying.

**Comment by carsonreinke** [comment]
@dimasusername I have been just helping out with some issues on resque-scheduler.  There are several PRs pretty much ready to go, but really need another set of eyes on some of this stuff (really just a comfort level).

Even though you may say a lot of issues/PRs, I think the project is still quite stable (well hopefully), but still needs some work.  Put your issue in and I can help see what is going on.
