### ISSUE TITLE
Airbrake.notify is now asynchronous causing jobs to not notify Airbrake

### ISSUE THREAD

**Issue by joaodiogocosta** [resque/resque#1580]
Since version 5, Airbrake gem [sends error notifications asynchronously by default](https://github.com/airbrake/airbrake/blob/910814b8b6d5c169e29ee85c646ac03a6deb2f1e/docs/Migration_guide_from_v4_to_v5.md#notify). `Airbrake.notify_sync` should be used in its place.

`Airbrake.notify` now returns a promise, which may or may not be fulfilled within the life span of a Resque Job being processed. If the job runs fast enough and exits immediately, Airbrake's servers are never notified.

The following failing app is provided:
```ruby
Gem.install 'airbrake', '>= 5'
require 'airbrake'

airbrake_version = Airbrake::AIRBRAKE_VERSION

if Airbrake::AIRBRAKE_VERSION.to_i < 5
  raise "Airbrake version must be >= 5. You're using #{airbrake_version}"
end

Airbrake.configure do |config|
  config.project_id = 1 # fake project id
  config.project_key = 'invalid project key'
end

# Prevent airbrake from sending the response
# It's either this or fake poor network conditions.
# I think this is enough for demonstration purposes
class Airbrake::AsyncSender
  def send(_, promise)
    promise
  end
end

# Async
promise = Airbrake.notify('FooBar')
promise.then do
  puts "Notification sent!"
end
promise.rescue do
  puts "Error sending notification."
end

# Sync
result = Airbrake.notify_sync('Foobar')
puts result # => { ... airbrake response as an hash... }
```

Notice that neither "Notification sent!" nor "Error sending notification" are printed to the console, as it happens if your network is slow at the moment (the promise is never resolved or rejected).

As can be seen [here](https://github.com/resque/resque/blob/master/lib/resque/failure/airbrake.rb), `Resque::Failure::Airbrake` still relies on the (now asynchronous) `Airbrake.notify` method, being susceptible to failure if the ruby process exits fast enough.

I found this issue in an existing project after migrating airbrake gem to version `7` and noticing that errors from a specific environment in which this change was deployed stopped coming through. Kudos to @eidge who helped me debugging this one.

I'm preparing a pull request with a change that ensures that the synchronous version of `notify` is used, which solved the issue for us.

**Comment by gerardc** [comment]
@joaodiogocosta nice work submitting a PR for this. Can this issue be closed?

**Comment by joaodiogocosta** [comment]
@gerardc sure! Thanks
