### ISSUE TITLE
Use termsig (instead of stopsig) when a thread is killed

### ISSUE THREAD

**Issue by supersam654** [resque/resque#1588]
In [`worker.rb#perform_with_fork`](https://github.com/resque/resque/blob/master/lib/resque/worker.rb#L909), jobs can fail if they receive an unhandled signal:

    job.fail(DirtyExit.new("Child process received unhandled signal #{$?.stopsig}", $?)) if $?.signaled?

I'm seeing some failed jobs in my queue with an error of "Child process received unhandled signal" (note the lack of a signal on the end of the message).

I believe this is because `stopsig` is the wrong method to call and Resque should actually check `termsig` instead. According to [the docs](https://ruby-doc.org/core-2.2.0/Process/Status.html), the source of `signaled?` (in C), is running:

```
if (WIFSIGNALED(status))
        return Qtrue;
```

However, `stopsig` is checking:

```
if (WIFSTOPPED(status))
        return INT2NUM(WSTOPSIG(status));
```

and `termsig` is checking:

```
if (WIFSIGNALED(status))
        return INT2NUM(WTERMSIG(status));
```

I honestly don't know exactly what `WIFSTOPPED` and `WIFSIGNALED` do, but I assume that we should use `termsig` because its analogous to `signaled?`.

**Comment by jeremy** [comment]
Nice catch! `Process::Status#to_s` nice handles these cases internally, so we could even simplify to
```ruby
job.fail(DirtyExit.new("Child process received unhandled signal: #{$?}", $?)) if $?.signaled?
```
Resulting in friendlier output:
```
Child process received unhandled signal: pid 12766 SIGQUIT (signal 3)
```
