### ISSUE TITLE
What do I do with stuck workers?

### ISSUE THREAD

**Issue by dimasusername** [resque/resque#1590]
I'm sure this question has been asked a million times. And there are a bunch of solutions on the web, like `worker.unregister_worker`, killing processes, etc. However, there are problems with unregistering workers: you unregister the worker and it's lost and not regained until I restart the process. Same with killing child processes.

So the question remains: what do I do if I get a number of workers stuck in `:working` state but not really doing anything. Why does this happen to begin with? And is it better to handle it from inside the Job class? Or should I have another job that unregisters the workers? (a solution I employed for couple of years, but it's flaky at best). What is the official solution and why can't I find anything about it in the Docs?

**Comment by jeremy** [comment]
Could you share a brief rundown of the issue, common solutions on the web, and why they work/don't work?

**Comment by dimasusername** [comment]
@jeremy Some jobs remain hanging for minutes / hours. A common solution on the web is to loop through the workers and unregister them:

      unregistered_workers_num = 0
      Resque.logger.info("Total workers: #{Resque.workers.count}")
      interval = 900
      Resque.workers.each do |worker|
        next unless worker.processing['run_at'] &&
                    Time.now - worker.processing['run_at'].to_time > interval
        worker.unregister_worker
        unregistered_workers_num += 1
      end
      Resque.logger.info("Unregistered workers: #{unregistered_workers_num}")

If you do a google search on resque stuck workers you'll see similar solutions.

However, the problem with this approach is that the workers unregistered are lost. This is a big problem, because if you expect to have 400 workers performing some task and you systematically unregister the ones that get stuck, you might actually end up with just a 100 workers that are actually servicing the queue. And the only way to bring back the unregistered 300 is to restart the server that's running the process (in case with Heroku).

So what do you do about the workers that get stuck performing a task?

**Comment by jeremy** [comment]
By "stuck" do you mean the status in Redis hasn't updated, or that the worker process itself is hung?

Smells like your worker processes may be getting killed by Heroku and hence aren't unregistering themselves on exit. Check out the Heroku signal handling gem: https://github.com/resque/resque/blob/master/README.markdown#signals-on-heroku

**Comment by jeremy** [comment]
Understood! Have you troubleshooted to see what those processes are doing when they hang there, or are we limited to machine restarts on Heroku?

**Comment by dimasusername** [comment]
@jeremy actually, I moved to AWS a couple of days ago and I see the same picture. Not really sure how I could troubleshoot these - no info found, everyone seems to stick to just unregistering them.

**Comment by jeremy** [comment]
> Not really sure how I could troubleshoot these

Log in to the host and inspect the status of the worker processes, perhaps?

**Comment by dimasusername** [comment]
@jeremy thanks! Actually found some of the issues that made the code run long without throwing an error. However, there are still some occasional dead workers that appear on the list, even after restarting the host. I just kill those with `Process.kill`. Is this normal?

**Comment by justinperkins** [comment]
Why was this closed out? I run into this regularly on a variety of jobs. When I kill the zombie job and run by hand, it inevitably runs quickly - not an expected long running job.

From my experience and talking to piers over the years, Resque is well-known as having an issue with seemingly "stuck" jobs that need to be manually killed. Is there a reason for this? Something we're doing wrong in our code to create this issue? //cc @jeremy

**Comment by sandipsubedi** [comment]
Wish there was a better way to fix this, but I use docker and this is how I clean them:

<id> is the worker id.

```
docker stop <id> 

docker start <id>
```
