### ISSUE TITLE
Jobs not processing

### ISSUE THREAD

**Issue by array42** [resque/resque#1595]
resque 1.27.4

I am new to resque, so maybe i don't use it correctly.

I can enqueue jobs. I am using the ActiveJob.set(wait: or wait_until:).perform_later syntax.

I have redis and multiple resque workers running.

But only jobs scheduled closely to the current time will execute. I am testing it with a simple job creator like (0..100).each {  then schedule a job every minute  }

But resque only executes one, and only sometimes. So why does resque not pick up or execute all the later scheduled jobs? Since it does execute *sometimes* i do have the basic setup to run jobs with resque, but the workers do not pick up the jobs when they are due to be performed.

So, what should i do? I have many jobs in the queue. Scheduling something *later* or at a specific time does not work.

**Comment by jeremy** [comment]
Sounds like you need to set up https://github.com/resque/resque-scheduler as well 👍

**Comment by nozpheratu** [comment]
resque-scheduler does not support wait_until either, in fact, it doesn't support ActiveJob, period.
