### ISSUE TITLE
worker failure causes job to be lost...

### ISSUE THREAD

**Issue by skippy** [resque/resque#16]
The job is popped directly from the queue, so if the worker fails, the job is totally lost.  if the job fails, then it is put on the error queue, which is awesome, but the worker has no failsafe.

I'm not sure what the best approach is, but a thought is:
- pop/push jobs onto a processing queue, and have each item tied to a worker and the original queue
- every now and then, a worker checks the processing queue to make sure that each processing job's worker still exists (and hasn't been killed off by god for being too stale)
- if so, great, if not, put it back onto its original queue

It looks like the worker is already doing some admin work anyway; is this too much for all workers to do?

**Comment by hackhowtofaq** [comment]
Why is this closed? 

Did you find a solution on the problem? 

Is there a best practice for this?

**Comment by Dianne087** [comment]
return
