### ISSUE TITLE
Outdated documentation on README

### ISSUE THREAD

**Issue by JeffLuckett** [resque/resque#1601]
No mention of Rails 5.x, and still referring to long-dead Rails 2.x. ActiveJob (although simple) is practically a footnote.

While I personally haven't run into specific issues with my implementation, I think you should consider a thorough review of your documentation.  It doesn't inspire confidence in would-be users when the latest versions of Rails aren't mentioned, and the docs harken all the way to the dark ages of 2.x.  

Redis and Resque have been around a long time now, and have gone through much evolution.  As such, it's a little bit of an adventure hacking your way through the detritus of outdated information both in the README, and in other guides and sources on the internet.  Your README should be the "source of truth" for a "basic" installation and configuration.  It's probably time to move the 2.x references off into the archives somewhere, de-emphasize 3.x (and possibly store next to 2.x)  and focus on 4.x and 5.x and ActiveJob relevancy.

Anyway ... thanks for your hard work, and this excellent product!

**Comment by jeremy** [comment]
Agreed on all counts, @JeffLuckett! Such are the blessings & curses of stable "keeps the lights on" software. Pull requests very welcome ❤️
