### ISSUE TITLE
Support for redis-rb > 4, NoMethodError: undefined method `connect' for Redis:Class

### ISSUE THREAD

**Issue by bbuchalter** [resque/resque#1611]
Resque does not have an explicit dependency on `redis` although it does on `redis-namespace ~> 1.3` which in-turn depends on `redis (>= 3.0.4)`. With 4.x series of redis-rb released, we're being hit by [the replacement of Redis.connect with Redis.new](https://github.com/redis/redis-rb/commit/895cc3211e335a8fd9ba9322cd311c09eea9621f#diff-54fab56a3b12825ac3ed9243b67fd459).

I'd like to propose adding an explicit dependency on `redis ~> 4` and correcting [this line](https://github.com/resque/resque/blob/v1.27.4/lib/resque.rb#L116). Any objections?

**Comment by bbuchalter** [comment]
See https://github.com/bbuchalter/resque/commit/2141a7ffb677ec5bcc88391801feb0f5e2521859

**Comment by bbuchalter** [comment]
Per a great suggestion from @rafaelfranca I've reduced the scope of the change to just use `Redis.new` instead of forcing use of v4: https://github.com/bbuchalter/resque/commit/213be07a6581644795dddec531e7bda246ea2450

**Comment by rafaelfranca** [comment]
Sounds good. Can you open a PR?

**Comment by bbuchalter** [comment]
Looks like this was fixed by https://github.com/resque/resque/commit/59a7d6190152b073c8fbecdfab1af54264a2ae1c but this change was never released. I think all we need is a new release.

**Comment by rafaelfranca** [comment]
Cool. We are going to do a release soon. Thanks

**Comment by jeremy** [comment]
#1593
