### ISSUE TITLE
Redis.connect should NOT be used because it prevents newer versions of redis-rb from being used

### ISSUE THREAD

**Issue by joelpresence** [resque/resque#1613]
Hi,

Thanks for all of your hard work on resque!

The 1.27.4 version of resque uses `Redis.connect` in two places in `lib/resque.rb`, in the 'redis=` and `redis` methods.  The most popular redis gem 'redis-rb' does NOT support `Redis.connect` from version 4.0.0 onwards.  So can we get a release of resque that does not use `Redis.connect`?  :-)

If not, we are forced to use version 3.3.3 of `redis-rb` which is more than a year old and doesn't have important patches.

We'd prefer to use an officially released version of resque not pull a gem from a particular git sha.

Any ideas?  :-)

Thanks!

**Comment by jeremy** [comment]
Fixed by #1593. Coming in next gem release. Bundle from master in the meantime for redis-rb 4 support.

**Comment by joelpresence** [comment]
Thanks for the quick response @jeremy .  Any idea when the next gem release is coming?  :-)

We don't feel entirely comfortable bundling from master and prefer to use tagged releases ...

Thanks again!

**Comment by jeremy** [comment]
Hopefully™ real™™ soon™™™! 😂

**Comment by joelpresence** [comment]
Thanks @jeremy !  :-)
