### ISSUE TITLE
New Version of Resque 2.0

### ISSUE THREAD

**Issue by tmedford** [resque/resque#1622]
When are you going going to deploy resque 2.0 to ruby gems? The new changes with redis namespace need to be brought in and all supporting libraries for resque need to be updated as well.

**Comment by jeremy** [comment]
Unresolved yet. Resque 2 was previously a much larger upgrade. Now it's due to a Ruby 2.1+ version bump. May see about releasing a 1.28.0 that pulls in these updates without breaking compat.

**Comment by FreekingDean** [comment]
Since this is unresolved can we keep this ticket open?
