### ISSUE TITLE
Support Redis library's SSL abilities

### ISSUE THREAD

**Issue by eshicks4** [resque/resque#1626]
https://github.com/resque/resque/blob/eadb02a7a3afb63fe926cd59e3e943a1b3dab547/lib/resque.rb#L115

Any chance we can make this a little smarter so it detects rediss:// lines and enables SSL on the connection?  Maybe `/rediss?\:\/\//` instead?  Thanks

**Comment by rafaelfranca** [comment]
Sure. Mind to open a PR?

**Comment by toomanyjoes** [comment]
Is this enough to support ssl? In the event the server url starts with rediss don't you also need to pass in `ssl: true`, when Redis is instantiated? Like so:

```
if server =~ /rediss?\:\/\//
  redis = Redis.new(:url => server, ssl: server =~ /rediss\:\/\// ? true : false)
else
```
