### ISSUE TITLE
Possible bug in Failure::Multiple backend

### ISSUE THREAD

**Issue by NobodysNightmare** [resque/resque#1632]
Hey there,

while implementing my own failure backend I stumbled upon [this part of code in the `Failure::Multiple` backend](https://github.com/resque/resque/blob/1d85f7c705ee8a609531c29035f8cf7cc6d67b19/lib/resque/failure/multiple.rb#L63-L65):

```ruby
def self.remove(index, queue)
  classes.each { |klass| klass.remove(index) }
end
```

This backend is supposed to delegate its calls to its "descendant"  backends. What strikes me here is, that the method accepts two arguments: `index` and `queue`, but only passes the `index` argument along, when calling the `remove` method of the descendant backends.

The mismatch seems to have been introduced here: https://github.com/resque/resque/commit/dcf22610949122bceb489a9306bedee78f50b565

Maybe I am overlooking a reason that this is the correct behaviour. I did **not** observe any misbehaviour because of this. I merely reviewed the code by accident and saw this.

Best regards

**Comment by iloveitaly** [comment]
@NobodysNightmare this seems like a bug to me! Could you submit a PR with a test case for this?

Thanks for the report!
