### ISSUE TITLE
Failed jobs can't be cleared

### ISSUE THREAD

**Issue by typhoon2099** [resque/resque#1633]
My application uses Resque for managing jobs, which sometimes fail. I regularly clear these out but suddenly the "Clear Failed jobs" button has stopped working. I've recently upgraded some packages and moved my Rails app to a pure API app. I can see that the button performs a POST action but the endpoint itself requires a DELETE action. Has Rails been lenient up until this point? Has a package been upgraded which could interfere with this functionality?

**Comment by rafaelfranca** [comment]
It can be a package upgrade. Rails could be the culprit but the resque dashboard it is written using sinatra. Can you try to reproduce this problem in a new application?

**Comment by typhoon2099** [comment]
Yes, I've created a new API only application with no other endpoints, models or controllers configured. After injecting a failed job list into Redis I've attempted to clear the failed jobs using the "Clear Failed Jobs" button and get a standard Rails routing error:

```
No route matches [POST] "/resque_web/failures/destroy_all"
```

I've also just realised I've posted this in resque rather than resque_web, which may be where the issue actually lies.

**Comment by tylerkahn** [comment]
If you add these two lines to your application.rb it will work

    config.middleware.use Rack::MethodOverride
    config.middleware.use ActionDispatch::Flash

**Comment by rafaelfranca** [comment]
@tylerkahn is right. Because this is an API application Rails don't know how to send the `DELETE` action to the controller. You need to add the `Rack::MethodOverride` middleware back to the stack.
