### ISSUE TITLE
No easy way to check if a job is currently running

### ISSUE THREAD

**Issue by lucas-ibotta** [resque/resque#1643]
There isn't an easy interface to check whether a certain job is *currently* running.

As a work around, we're currently querying Redis directly (as outlined [here](https://stackoverflow.com/questions/21904445/how-to-view-a-resque-job)).

```ruby
jobs = Resque.redis.lrange('queue:MY_QUEUE', 0, -1)
jobs.each do |job|
	decoded = Resque.decode(job)
	if decoded["args"].include?(MY_ARGS)
		# do something
	end
end
```

It would be nice to have a more abstracted interface to this information. Something like:

```ruby
# @returns boolean
Resque.job_on_queue?("MY_QUEUE", MY_ARGS)

# @returns JSON of decoded jobs
Resque.jobs_on_queue("MY_QUEUE")
```

I'm happy to put in a PR for it, but wanted to check if there is interest in this feature.

**Comment by jeremy** [comment]
Go for it! Good fit for trying out as a Resque plugin.
