### ISSUE TITLE
Logging each Done & working process 

### ISSUE THREAD

**Issue by abdoutelb** [resque/resque#1645]
Iam try to get all resque working process that i done working, I query throw redis that is used by resque and i find that i only get 2 or 3 keys and i can't find what is done working after that 
ex:
```
worker:Jobs:21951:test:started
worker:Jobs:21940:test:started
```

I am try to get number of how many test worker is done working and is it working right now or not from the redis

**Comment by rafaelfranca** [comment]
You can't after a job is done the information is not on redis anymore.
