### ISSUE TITLE
Database Ports

### ISSUE THREAD

**Issue by arianf** [resque/resque#1649]
I'm using Postgres and we have a finite limit of ports. Is there any way to run Resque where it could possibly use less database ports per worker?

We've started having to limit our worker numbers based off of max port counts

**Comment by rafaelfranca** [comment]
Resque has no knowledge about your database so I don't think this is an issue with Resque. What is opening those database ports?

**Comment by iloveitaly** [comment]
I've run into this issue myself and I don't believe there is a workaround beyond increasing the connection limit of PG.

You could look into [resque pool](https://github.com/nevans/resque-pool) which may enable you to share a DB & Redis connection on the master worker with any children in the same process. There are probably some gotchas with that approach though.
