### ISSUE TITLE
Question about removing jobs from a queue

### ISSUE THREAD

**Issue by monicao** [resque/resque#1655]
Hi!

When running the test suite for my Rails app I want to ensure that the Resque queues are all cleared after each test executes. For this reason I am running this in the MiniTest teardown method.

```ruby
def after_teardown
  DatabaseCleaner.clean
  Resque.queues.each{ |q| Resque.remove_queue(q) }
  super
end
```

But when I run the test suite, some tests are failing, because the queue is not empty. When I use the debugger to inspect the state of the Resque queue, there is indeed a job from another test case in there.

When I try to use the `remove_queue` method to remove the queue manually, the method fails, which explains why my teardown code doesn't work...

```
(byebug) Resque.queues
{:test_queue=>["{\"class\":\"Services::BackgroundJob::EnqueueTest::TestJob\",\"args\":[{\"value\":1}]}"]}
(byebug) Resque.remove_queue(:test_queue)
[false, 0]
(byebug) Resque.queues
{:test_queue=>["{\"class\":\"Services::BackgroundJob::EnqueueTest::TestJob\",\"args\":[{\"value\":1}]}"]}
```

I tried using `pop`, but that also doesn't work.

```
(byebug) Resque.pop(:test_queue)
nil
(byebug) Resque.queues
{:test_queue=>["{\"class\":\"Services::BackgroundJob::EnqueueTest::TestJob\",\"args\":[{\"value\":1}]}"]}
```

What am I doing wrong? How can I clear the queue between tests?

Thank you for your help!

**Comment by rafaelfranca** [comment]
I don't see anything wrong on your code. I'd recommend you to try to understand why `remove_queue` is failing.

**Comment by rafaelfranca** [comment]
I think you had something monkey patching (or maybe an old version of resque running). `Resque. queues` returns an array, not a hash like in your example.

I just tried to remove a queue and I could remove it. So this problem you had may be related to this monkey patch.

Thank you for opening the issue
