### ISSUE TITLE
segfaulting with 1.27.4+ (including 2.0) and ruby 2.5.3

### ISSUE THREAD

**Issue by michaelglass** [resque/resque#1675]
After upgrading from 1.26.0 to 1.27.4, we started seeing segfaults when calling `ConditionVariable#signal`, introduced in https://github.com/resque/resque/pull/1484.

Looks like [this is a known bug in Ruby 2.5](https://bugs.ruby-lang.org/issues/14659). Perhaps it should be publicized as a warning in the readme.

[Status of ruby 2.5 fix looks like it's being tracked here.](https://bugs.ruby-lang.org/issues/14852)

**Comment by michaelglass** [comment]
Appears this also affects Resque 2.0 ([the buggy-in-ruby-2.5 code is still there](https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/thread_signal.rb#L11))

**Comment by iloveitaly** [comment]
@michaelglass It looks like the [this was fixed](https://github.com/ruby/ruby/commit/63d9ab33fe419167382fc03be2c00413a78c05cb) in ruby 2.5.4. Going to close this out, it's safe to assume users are going to use the latest minor patch version of ruby.
