### ISSUE TITLE
Running a resque worker once

### ISSUE THREAD

**Issue by code-bunny** [resque/resque#1678]
I have a AWS ECS application running Rails 5.2. It has several tasks that are currently using resque however I am now wanting to move these to a sort of scheduled tasks setup. Is there a configuration for resque I can set for when `QUEUE=some-long-task-queue bundle exec rails environment resque:work` runs it picks up the task(s) in the queue, executes, then shuts down when it is is out of the queue therefor allowing the docker instance on ECS to shutdown with it?

**Comment by iloveitaly** [comment]
@code-bunny there's no built-in task for this, and I don't see us adding this functionality in to the core library. 

You'd want to model your script after a modified version of the `work` loop here:

https://github.com/resque/resque/blob/4e388e1ba4aa1d3b53d54277f25cfc0089d36570/lib/resque/worker.rb#L233
