### ISSUE TITLE
Specs are failing with the latest Airbrake

### ISSUE THREAD

**Issue by jeremywadsack** [resque/resque#1684]
I'm re-posting [my comment on 1682](https://github.com/resque/resque/pull/1682#issuecomment-495736359) as an issue because I don't know how to address it but thought the details might help someone else.

All the recent PRs have failed in Travis with errors like this:

```
rake tasks::resque:work#test_0001_requires QUEUE environment variable [/home/travis/build/resque/resque/test/rake_test.rb:19]:
--- expected
+++ actual
@@ -1 +1 @@
-"attempted to build set QUEUE env var, e.g. $ QUEUE=critical,high rake resque:work with closed Airbrake instance"
+"set QUEUE env var, e.g. $ QUEUE=critical,high rake resque:work"
```

This is related to an update to Airbrake. I can reproduce it on master with the latest Airbrake. I've narrowed the issue down to a change in `airbrake` gem between 8.1.4 and 8.2.0 which changed the dependency of `airbrake-ruby` from 3.2.6 to 4.1.0. My guess is it has something to do with airbrake/airbrake-ruby#429 or airbrake/airbrake-ruby#443. I tried configuring Airbrake to ignore the environment for the rake tests, but even though it accepts the configuration it still reports as being "closed".

**Comment by jeremy** [comment]
Fixed by #1708
