### ISSUE TITLE
Adress family not supported

### ISSUE THREAD

**Issue by roulili** [resque/resque#1685]
Hi

I've been using resque quite happily for some time now, but since a few days it's broken and I can't figure out why.
I cannot start new workers, here's the errors being thrown:

rake aborted!
web_1    | Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:39:in `initialize'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:39:in `initialize'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:195:in `new'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:195:in `connect_addrinfo'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:239:in `block in connect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `each'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `each_with_index'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `connect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:313:in `connect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:336:in `establish_connection'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:101:in `block in connect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:364:in `ensure_connected'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:306:in `logging'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:504:in `block in exists'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `block in synchronize'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:58:in `synchronize'
web_1    | /usr/local/bundle/gems/redis-3.3.5/lib/redis.rb:503:in `exists'
web_1    | /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace'
web_1    | /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing'
web_1    | /usr/local/bundle/gems/resque-scheduler-3.1.0/lib/resque/scheduler/scheduling_extensions.rb:55:in `schedule='
web_1    | /app/lib/tasks/resque.rake:28:in `block (2 levels) in <top (required)>'
web_1    | /usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
web_1    | Tasks: TOP => resque:scheduler => resque:setup_schedule
web_1    | (See full trace by running task with --trace)

I've tried reverting my code to an earlier point in time but to no avail. I've also checked the config multiple times but everything looks correct. yet, there's something wrong, somewhere.

Does anyone have a clue? Any other file or command I could try to gather more info?
Thanks in advance!

**Comment by gerardc** [comment]
According to https://ruby-doc.org/stdlib-2.0.0/libdoc/socket/rdoc/Socket.html, `Errno::EAFNOSUPPORT - the specified sockaddr is not a valid address for the family of the calling socket`. The issue appears to be related to the redis client opening connection with invalid configuration. Has your config or environment changed?

**Comment by iloveitaly** [comment]
This is most likely a redis config issue, closing this out.
