### ISSUE TITLE
Why the @child is nil?

### ISSUE THREAD

**Issue by brunoocasali** [resque/resque#1688]
Hello guys!

I'm trying to create a script to run every x seconds killing stucked workers for specific queues.

I'm tried to use the resque API, to kill a child but it returns `nil`. I've checked the source code and I see a `if @child` in the `kill_child` method  https://github.com/resque/resque/blob/master/lib/resque/worker.rb#L459
```rb
irb(main):001:0> Resque.working.first.instance_variable_get :@child
=> nil
irb(main):002:0> Resque.working.first
=> #<Worker dash-worker-7bbfd75448-phx2h:30:*>
```

But if the `@child` is nil it never destroy the forked process, right?

So, to solve my problem I'm using this (ugly way):

```rb
pid = `ps -f -p #{w.pid} | grep [r]esque`[/Forked (.*?) at/m, 1]
`kill -9 #{pid}`
```

Could you please tell me what if I'm wrong in this case?

Thanks!

**Comment by jeremy** [comment]
Because `@child` is only set in the parent process that forked the child: https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/worker.rb#L895-L899
