### ISSUE TITLE
Feature request: Use CDN for Resque::Server

### ISSUE THREAD

**Issue by danlo** [resque/resque#1692]
Greetings,

Would it be possible to migrate or allow the option of using 
```
https://github.com/resque/resque/tree/master/lib/resque/server/public
```

These files from a CDN server?  This would greatly reduce the total number of requests to the rails server, allowing more HTTP 304 + expiration dates; perhaps something along the lines of in config/initializers/resque.rb.  

```
Resque::Server.cdn="https://public package.cdn/(resque-version)/(resque/server/public files go here)"
```

Thank you for producing resque!

**Comment by danlo** [comment]
This was also very useful!

```

**Comment by iloveitaly** [comment]
I'd opt to _not_ use a CDN because of CSP issues that will cause with many Rails configurations. 

Your caching snippet is useful—added this to the FAQ https://github.com/resque/resque/wiki/FAQ
