### ISSUE TITLE
Rescue workers should, but do not, attempt to reconnect when Redis goes down

### ISSUE THREAD

**Issue by weiyunlu** [resque/resque#1693]
Hello,

This is an issue that has a precedent from 2012, in the following issue and PR (see comments on the PR in particular):
https://github.com/resque/resque/issues/37
https://github.com/resque/resque/commit/d39046fd568e38c43ab049dcd21832ee87633e0e

It would appear that `reconnect` in `resque/worker.rb` is intended to rescue any Redis connection errors and attempt 3 reconnects over ~6 seconds before re-raising, but this appears to not work in practice.

We have observed issues where when Redis is even momentarily unavailable, Resque will panic and the workers die right away, for example the following (locally this can be simulated by stopping or restarting the redis server with the same result):

Redis::ConnectionError · Connection lost (ECONNRESET) Original Exception (Redis::ConnectionError): Connection lost (ECONNRESET) /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:267:in `rescue in io' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:259:in `io' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:271:in `read' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:125:in `block in call' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:241:in `block (2 levels) in process' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:384:in `ensure_connected' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:230:in `process' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:125:in `call' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/instruments/redis.rb:32:in `block in call_with_scout_instruments' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/tracer.rb:34:in `instrument' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/tracer.rb:44:in `instrument' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/instruments/redis.rb:31:in `call_with_scout_instruments' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:107:in `block in connect' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:105:in `connect' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:381:in `ensure_connected' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:230:in `process' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis/client.rb:125:in `call' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/instruments/redis.rb:32:in `block in call_with_scout_instruments' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/tracer.rb:34:in `instrument' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/tracer.rb:44:in `instrument' /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.5.2/lib/scout_apm/instruments/redis.rb:31:in `call_with_scout_instruments' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis.rb:1447:in `block in smembers' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize' /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize' /app/vendor/bundle/ruby/2.6.0/gems/redis-4.1.2/lib/redis.rb:1446:in `smembers' /app/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace' /app/vendor/bundle/ruby/2.6.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/data_store.rb:144:in `queue_names' /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `queue_names' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque.rb:317:in `queues' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:206:in `glob_match' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:202:in `block in queues' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:202:in `map' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:202:in `queues' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:317:in `reserve' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:251:in `work_one_job' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:234:in `block in work' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:231:in `loop' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/worker.rb:231:in `work' /app/vendor/bundle/ruby/2.6.0/gems/resque-1.27.4/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute' /app/vendor/bundle/ruby/2.6.0/gems/bugsnag-6.12.1/lib/bugsnag/integrations/rake.rb:19:in `execute' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain' /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling' /app/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run' /app/bin/rake:9:in `<main>'

Locally, we have been able to get around this by monkey-patching the first point of contact with Redis in `method_missing` in `Redis::Namespace` to have the `rescue Redis::BaseConnectionError` with `retry`s just like the code in `worker`.  However, this is quite sketchy and we are not comfortable using this workaround in production.

Another similar issue from some time ago; at least the `work` method seems to need exception handling: https://github.com/resque/resque/issues/1531

Furthermore, we're using Rails' built-in Redis store which has been available as of Rails 5.2, and already is configured to make reconnect attempts and drop all Redis exceptions, yet it seems Resque isn't playing nicely with it (see, e.g., https://guides.rubyonrails.org/caching_with_rails.html, https://www.briankephart.com/redis-is-letting-you-down).

Can you please re-investigate the issue?  It appears to not have been fully resolved.  Many thanks in advance.

Retagging the original people involved: @steveklabnik  @trevorturk

**Comment by iloveitaly** [comment]
@weiyunlu I believe this is fixed in the latest release with https://github.com/resque/resque/commit/b739f835105511270200f5037ddb368d676f297e and a combination of some previous PRs. Please reopen if you are still having trouble here!
