### ISSUE TITLE
Resque 2 breakes eager loading in workers

### ISSUE THREAD

**Issue by micke** [resque/resque#1698]
In #1597 resque started respecting the `eager_load` config in rails, which sounds great!
The problem is that `eager_load` is always false when rails is running in rake because of rails/rails#11389

This breaks applications that require that all classes are loaded.

**Comment by jiikko** [comment]
duplicate of https://github.com/resque/resque/issues/1680

**Comment by wwahammy** [comment]
Wanted to let folks know that an option for using eager loading in Rake tasks was recently merged to Rails with rails/rails#28209
