### ISSUE TITLE
Best way to prevent a job from running on a certain environment (e.g. staging)

### ISSUE THREAD

**Issue by toomanyjoes** [resque/resque#1701]
I have a job that pulls transactions from a bank api that charges per transaction pulled. Obviously I don't want this task running in staging, but I have some other resque jobs that I do want to run in staging. 

Now I know that I could do a conditional check inside the job itself to check the environment before running but is this the best way?

Does resque have a built in way to handle this or is just wrapping the job in a conditional check the right way to accomplish this? Thanks!

**Comment by jiikko** [comment]
If you want to hide conditionals logic, you may be able to use hooks. thanks.
https://github.com/resque/resque/blob/master/docs/HOOKS.md

**Comment by toomanyjoes** [comment]
Thanks! I definitely used hook, here's what I ended up doing incase anyone else is interested.

```ruby
module ResqueHooks::ProductionOnlyJob
  def before_perform(*args)
    if ENV['RAILS_ENV'] != 'production'
      Resque.logger.info "Will not perform job on this environment: (#{ENV['RAILS_ENV']})"
      raise Resque::Job::DontPerform
    end
  end
end
```
```ruby
class DownloadBankTransactions
  extend ResqueHooks::ProductionOnlyJob

  @queue = :download_bank_transactions

  def self.perform
    Wrappers::TransactionDetailClient.retrieve_bank_transactions
  end
end
```
