### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by milanvanzanten** [resque/resque#1702]
The latest commit on master was a year ago and the last release in 2018. It still uses jQuery 1.12.4, which is vulnerable to a XSS attack (#1690).

This raises the question, is this still being maintained?

**Comment by junaruga** [comment]
This ticket is related to https://github.com/resque/resque/issues/1705 .

**Comment by jeremy** [comment]
It's sporadically maintained and needs more active contributors. Please do contribute pull requests to address issues you encounter.
