### ISSUE TITLE
Getting blank page /resque/overview

### ISSUE THREAD

**Issue by ravindra9278** [resque/resque#1703]
I am noticing very strange with Resque web interface, I am getting a blank page every time when I open the `resque/overview` url but when I tried to open the failed jobs (`resque/failed`) it is showing perfectly fine.

gem details are below:
  * resque (1.27.4)
  * resque-retry (1.5.0)
  * resque-scheduler (4.3.1)
  * resque_spec (0.17.0)

I can also see in case of `resque/overview` : CSS and JS are not loading but in case of `resque/failed` its loading. I am not sure where is the issue because I did not updated resque gem.

**Comment by jweir** [comment]
@ravindra9278 are you using NewRelic or some other instrumentation that might inject code into the response body?

I noticed the `Content-Length` and response body were wrong.  NewRelic injects some javascript and that appears to be breaking the response for the `Resque::Server`

In our Rails application the Resque::Server is mounted like so

```ruby
  constraints resque_constraint do # resque_contraint is a lambda to ensure an admin user, not important here
    mount Resque::Server, :at => "/path/to/resque"
  end
```

I have opted to disable the Resque paths from the New Relic instrumentation:

In `newrelic.yml` I added:

```yml
rules:
  ignore_url_regexes: ["^/path/to/resque"]
```

This has fixed the issue for us.  I will open a ticket with NewRelic to see what they think of this.

**Comment by s-lee-kwong** [comment]
> @ravindra9278 are you using NewRelic or some other instrumentation that might inject code into the response body?
> 
> I noticed the `Content-Length` and response body were wrong. NewRelic injects some javascript and that appears to be breaking the response for the `Resque::Server`
> 
> In our Rails application the Resque::Server is mounted like so
> 
> ```ruby
>   constraints resque_constraint do # resque_contraint is a lambda to ensure an admin user, not important here
>     mount Resque::Server, :at => "/path/to/resque"
>   end
> ```
> 
> I have opted to disable the Resque paths from the New Relic instrumentation:
> 
> In `newrelic.yml` I added:
> 
> ```yaml
> rules:
>   ignore_url_regexes: ["^/path/to/resque"]
> ```
> 
> This has fixed the issue for us. I will open a ticket with NewRelic to see what they think of this.

This fixed the issue for me as well. Thanks!

**Comment by ravindra9278** [comment]
Yes, it's working. Thank you 🎉🎉

**Comment by jweir** [comment]
An update for this issue.  I reached out to NewRelic and they will be releasing a fix with the next release of the NewRelic agent.

**Comment by janis-vitols** [comment]
`ignore_url_regexes` didn't work for us, but as we do not use `Browser` features workaround for us was to set:

```
browser_monitoring:
  auto_instrument: false
```
