### ISSUE TITLE
Suggestion: About using Vegas as a runtime dependency

### ISSUE THREAD

**Issue by junaruga** [resque/resque#1706]
Hello,

I see vegas is used in `bin/resque-web`. And it is runtime dependency.
My concern to use vegas is that vegas has not been updated on the latest 8 years, when Ruby, rack and sinatra has been updated. During the time, rack has been updated from version 1.X to 2.X. Sinatra from from version 0.X to 2.X.

My suggestion to use vegas is if you think vegas is really necessary for resque, vegas needs your helps, considering to move vegas repository to resque organization, then maintaining it by not a maintainer but team of maintainers is one of the way to maintain vegas sustainably.

If you think vegas is not really necessary for resque, think about the alternative might be good.

How do you think?

For detail context, see https://github.com/quirkey/vegas/issues/27 .

**Comment by jeremy** [comment]
Thanks @junaruga. I think we should remove it. It's a convenience for bin/resque-web only. We can use any other Rack-ready server.

**Comment by krzysiek1507** [comment]
Any idea how to replace it?

**Comment by junaruga** [comment]
I have no idea. Anyone? @jeremy?

**Comment by junaruga** [comment]
Could you anyone send pull-request for that?

**Comment by cork** [comment]
What command line arguments should be kept from today's resque-web?

(Not sure if it will be looking into this, but the answer is needed to even evaluate how much work it would be.)

**Comment by iloveitaly** [comment]
@cork I'm not too familiar with the resque-web logic. Can you point me to where the CLI arguments are exposed?

**Comment by cork** [comment]
I don't know much about it either, only option i use is -F to run it in forground as a service. The options are in here though

https://github.com/resque/resque/blob/master/bin/resque-web#L19

https://github.com/quirkey/vegas/blob/master/lib/vegas/runner.rb#L299

**Comment by iloveitaly** [comment]
@cork I think we could use stdlib (`OptionParser`) to parse CLI arguments and replace the vegas logic with the sinatra DSL. Hard to tell what options folks are using, but I think we pull over the basics (port, redis namespace, etc) that's good enough for now and if folks report issues we can add in additional options.

**Comment by JollyRoger8X** [comment]
Running into this problem in a Docker container running ruby 3.0.3p157. 😖 And I wash ping to be able to work around it while we wait for closure.

I tried importing the web_runner branch from [varyonic](https://github.com/varyonic) in my Gemfile:

`gem 'resque', git: 'https://github.com/varyonic/resque.git', branch: 'web_runner'`

But when I try to launch resque-web, I get this error:

```
/usr/local/lib/ruby/3.0.0/rubygems.rb:278:in `find_spec_for_exe': can't find gem resque (>= 0.a) with executable resque-web (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/3.0.0/rubygems.rb:297:in `activate_bin_path'
	from /usr/local/bundle/bin/resque-web:25:in `<main>'
```

My Gemfile.lock doesn't specify resque (>= 0.a) though:

...
GIT
  remote: https://github.com/varyonic/resque.git
  revision: dca604cf60dc08dbe8ddec9243e34fed73bb5af5
  branch: web_runner
  specs:
    resque (2.2.0)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.6)
      sinatra (>= 0.9.2)
...

Maybe I'm doing something wrong here. Any helpful ideas, appreciated! 🤞🏼🙂
