### ISSUE TITLE
*** Failed to start worker : #<ThreadError: can't be called from trap context>

### ISSUE THREAD

**Issue by relchar** [resque/resque#1714]
Hi, we rely on Resque v1.26.0 in production and upon stopping workers, we get the following error `*** Failed to start worker : #<ThreadError: can't be called from trap context>` en masse.

This is directly because we configure our instance of Resque with Syslogger, which we use for all our ruby-based services, and trying to log using Syslogger is not thread safe under signal handling contexts e.g. when sending `SIGQUIT` to workers. So when Resque tries to log right before it attempts graceful shutdown, Ruby poops the bed.

It would be great if Resque supported other loggers outside of non-locking loggers like Monologger when logging from trap contexts. The fix for this is pretty straightforward and would look something like this https://gist.github.com/relchar/9e4a3b8a5dc30345d85fb7cc4fbc719e, which works for us in production. It'd be great to have this in Resque without some sort of monkey patching on our end :)

For reference, see https://github.com/zendesk/racecar/issues/86, for how others have patched this.

**Comment by iloveitaly** [comment]
@relchar I believe you should be able to set `Resque.logger` to use whatever logger you'd like, as long as it has methods for various severity levels.

Does that not work for your use case?

**Comment by iloveitaly** [comment]
I discovered that this error is caused but _not_ using monologger as your Resque logger. You need to use that logger to avoid this error.

More discussion here: https://github.com/resque/resque/pull/1729
