### ISSUE TITLE
[Question] What happens when a worker is hard killed?

### ISSUE THREAD

**Issue by mockdeep** [resque/resque#1725]
I'm curious how the job is stored in Redis. Right now we're using Sidekiq, but we have issues when a server is shut down where jobs might just get lost. Sidekiq mostly tries to shut down gracefully and push jobs back into the queue, but we are still losing several jobs a day. Most of our jobs are pretty critical so reliability is key. We tried upgrading to Sidekiq Enterprise and using the `super_fetch` feature, but that traded one problem for another, where we would see jobs getting duplicated several times throughout the day. Our jobs a pretty transactional and handle retries gracefully, but they are definitely not idempotent. We would essentially need to wrap each one of them in a database lock to prevent them from running more than once.

What does resque do to prevent jobs from getting lost or duplicated?

**Comment by hackhowtofaq** [comment]
I am still working on the former https://github.com/hackhowtofaq/resquex/issues/1 the second might be solved with this https://github.com/hackhowtofaq/resquex/issues/5

**Comment by jeremy** [comment]
Resque worker processes fork a child process to perform each jobs. Resque worker processes also use a heartbeat to indicate that they're alive and working on a job.
* If the child process is killed, the parent worker is signaled and it [fails the job with a DirtyExit exception](https://github.com/resque/resque/blob/d780aa4cb9bc2239abb026ac483aadb6bccf9640/lib/resque/worker.rb#L929).
* If the worker is signaled to terminate while its child process is processing, the job is [failed with a DirtyExit exception](https://github.com/resque/resque/blob/d780aa4cb9bc2239abb026ac483aadb6bccf9640/lib/resque/worker.rb#L681).
* If the worker is SIGKILLed with no chance to handle the signal, the worker heartbeat ceases. When the next worker boots up, it prunes dead workers and fails the job it was working on [with a PruneDeadWorkerDirtyExit exception](https://github.com/resque/resque/blob/d780aa4cb9bc2239abb026ac483aadb6bccf9640/lib/resque/worker.rb#L620).

> We would essentially need to wrap each one of them in a database lock to prevent them from running more than once.

FWIW that may be appropriate when the ACID properties of your database are precisely the characteristics you need.
