### ISSUE TITLE
problem running resque worker with ruby 3.0.0

### ISSUE THREAD

**Issue by widjajayd** [resque/resque#1737]
I tried to upgrade my rails app using ruby 3.0.0 from 2.7.2 

running **bundle exec rake environment resque:work QUEUE='*'** with ruby 2.7.2 has no problem, but running same command with ruby 3.0.0, the worker is not running and back to prompt, I tried to trace it with running **bundle exec rake environment resque:work QUEUE='*' VERBOSE=1** and get an error message 

```
*** Starting worker main
*** Failed to start worker : #<ArgumentError: wrong number of arguments (given 3, expected 2)>


```

**Comment by shunsugai** [comment]
We had the same issue.
This seems to be caused by redis gem.
v4.2.0 and above didn't work, but v4.1.4 is works fine for me.

**Comment by widjajayd** [comment]
thank you @shunsugai , I just downgrade redis gem and it's work
I'll close the ticket

**Comment by SahSantoshh** [comment]
it worked for me with `4.1.4`
