### ISSUE TITLE
kill -s QUIT does not kill worker

### ISSUE THREAD

**Issue by braindeaf** [resque/resque#1742]
I am struggling to solve a problem whereby kill fails to kill the resque process at all.

Kill works locally, but on the remote staging or production Ubuntu servers. Not sure how to proceed with troubleshooting. This appears to have started happening in the last month or so and the only major upgrade weve done is upgrade Mongoid a d our MongoDB

Any hints on how to troubleshoot the kill failure?

**Comment by eriko-de** [comment]
I'm not a contributor, but used and worked with signaling in resque a bit.

How are you sending the signal to the worker and are you sending it to the forked (child) or the parent process?

**Comment by iloveitaly** [comment]
@braindeaf is this still an issue for you? What infrastructure are you running your application on?

**Comment by braindeaf** [comment]
If I recall the answer in the end was it was caused by an upgrade to miniracer 0.3.1. it didnt seem likely at all but downgrading it solved our problem and subsequently we realised we didn't need it anyway.

So solved but an oddity to say the least. Thank you for following up.

**Comment by iloveitaly** [comment]
@braindeaf Huh, that's strange! Thanks for following up. I'll close this one out.
