### ISSUE TITLE
resque-web fails to start

### ISSUE THREAD

**Issue by john-999** [resque/resque#1746]
$ resque-web
    [2021-04-25 15:01:13 +0200] Starting 'resque-web'...
    [2021-04-25 15:01:13 +0200] trying port 5678...
    /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `initialize': No such file or directory @ rb_sysopen - http://0.0.0.0:5678 (Errno::ENOENT)
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `open'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `port_open?'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:132:in `find_port'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:109:in `start'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/vegas-0.1.11/lib/vegas/runner.rb:77:in `initialize'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/resque-2.0.0/bin/resque-web:13:in `new'
	    from /home/user/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/resque-2.0.0/bin/resque-web:13:in `<top (required)>'
	    from /home/user/.rbenv/versions/3.0.0/bin/resque-web:23:in `load'
	    from /home/user/.rbenv/versions/3.0.0/bin/resque-web:23:in `<main>'

My environment:
- resque (2.0.0)
- resque-scheduler (4.4.0)
- redis (4.2.5)
- ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
- Rails 6.0.3.6

**Comment by knmrftw** [comment]
Hello!
@fatihgenc , @john-999 did u manage this issue?

**Comment by john-999** [comment]
@knmrftw - Sorry, not on my side. I have temporarily stopped using it.

**Comment by knmrftw** [comment]
As for me, moving to ruby-2.7.2 helped me, but it's not an your average way of managing problems :D

**Comment by imfuna** [comment]
I'm seeing this error with ruby 2.6.7

**Comment by iloveitaly** [comment]
If anyone has a fix, PRs are welcome!

**Comment by iloveitaly** [comment]
@john-999 were you using resque-scheduler by chance? A new version was recently released which fixed some issues with ruby3

**Comment by cork** [comment]
`/usr/local/rvm/gems/ruby-3.0.2@global/gems/vegas-0.1.11/lib/vegas/runner.rb:146: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open`
```
    def port_open?(check_url = nil)
      begin
        check_url ||= url
-        options[:no_proxy] ? open(check_url, :proxy => nil) : open(check_url)
+        options[:no_proxy] ? URI.open(check_url, :proxy => nil) : URI.open(check_url)
        false
      rescue Errno::ECONNREFUSED, Errno::EPERM, Errno::ETIMEDOUT
        true
      end
    end
```

Seams to be the fix. So needs to be fixed in vegas not in resque.

**Comment by cork** [comment]
https://github.com/quirkey/vegas/issues/29

**Comment by iloveitaly** [comment]
@cork vegas looks dead. I think the ultimate solution here is removing vegas completely. This is discussed here #1706. We just need someone to submit a PR to remove it.
