### ISSUE TITLE
Lost job after enqueueing it

### ISSUE THREAD

**Issue by ArtsiomMusin** [resque/resque#1749]
we noticed one strange behavior when a job is enqueued from the application but not seen on the resque side in logs. 

From the rails application logs we can see messages like:
[ActiveJob] Enqueued Job (Job ID: 9cbaf743-b163-48e2-b4d2-428f4bc2c123) to Resque(ticket) with arguments

And from the resque logs there is no performing log statement for one job for some reason. 
So we sent jobs like 1,2,3,4,5 and resque performed like 1,2,4,5. The 3rd job is no performed it seems. 

`Resque.info` is not showing any pending jobs to be executed and there is no failed job in `Resque::Failure.all`. Looks like a job was lost somewhere and it's not clear what could be a reason and where to search for it.

Has anyone seen the same case? Note that this happened just for one job and others are fine.

**Comment by Manjunatha-cloud-cell** [comment]
We are also facing the same issue.

Could you please help with this anyone?

Thanks

**Comment by Manjunatha-cloud-cell** [comment]
@ArtsiomMusin, I'm managed to solve the issue, 
Resolution.
We have hosted redis and ruby on one instance, I have restarted the Instances, hence Redis restarted. the issue has been resolved.

Thanks

**Comment by ArtsiomMusin** [comment]
Just for the record. We haven't found any reasons why it happened. In the past we had similar issues but in that case all tickets were not executed due to some issues on redis. What we saw happened just for one ticket and others were fine. Anyway, we triggered the job once again and it worked.
