### ISSUE TITLE
Content Security Policy triggers on Resque frontend

### ISSUE THREAD

**Issue by peret** [resque/resque#1756]
We're testing a new nonce-based Content Security Policy for our Rails app. The CSP does not contain 'unsafe-inline', which seems to break some inline script in the Resque frontend of our app. In Firefox, I get the error `Content Security Policy: The page's settings observed the loading of a resource at inline ("script-src"). A CSP report is being sent. Source: t.`. The CSP is in "report-only" mode for now.

Is there any way for me to work around this? I already tried finding out whether there's a way for me to disable/change the CSP for the resque-related routes, but so far didn't find a way to e.g. trigger a before_action for the routes of the Engine.
Or is this maybe something that can be fixed in the gem? I've seen another gem offering a config option to override the CSP, although I'm not sure that's the best option. I think the ideal solution would be to not use any inline-scripts in the views at all.

**Comment by peret** [comment]
I just realized that this might actually be caused by an outdated jQuery version. Upgrading the jquery version that is packaged with the frontend might actually be the easiest solution.

**Comment by iloveitaly** [comment]
Yup, most likely this is the ancient jQuery version that is in use. There's a WIP PR to fix this, would love your help on the PR: https://github.com/resque/resque/pull/1736

**Comment by peret** [comment]
I could confirm that some of the CSP reports we're seeing are resolved by upgrading jQuery. There are some instances of inline click-handlers though, that are also being reported with our configuration (i.e. no "unsafe-inline"). I'll try to provide a PR that solves these as well.

**Comment by iloveitaly** [comment]
@peret awesome, thank you!
