### ISSUE TITLE
Rails 5 - NameError:Uninitiazed constant <JobClass>

### ISSUE THREAD

**Issue by mmarinaccio** [resque/resque#1767]
Hey there -

I've been struggling all day trying to resolve a Resque / Rails issue. In short, it seems that my Resque background processes aren't invoking my Rails environment and modules. I must have misconfigured something in my Rails stack, but as far as I can tell all my config matches the documentation, as well as my previously working build under Rails 4.

Any help would be hugely appreciated!

Error (from Redis):
The below shows a NameError for `CreateContactsFromCsvJob`, which is a class defined in `<rails_root>/app/jobs`.
```
=> ["{\"failed_at\":\"2021/09/15 19:32:45 UTC\",\"payload\":{\"class\":\"CreateContactsFromCsvJob\",\"args\":[123]},\"exception\":\"NameError\",\"error\":\"uninitialized constant CreateContactsFromCsvJob\",\"backtrace\":[\"/home/railsapps/public_html/my_app/shared/bundle/ruby/2.5.0/gems/resque-2.1.0/lib/resque.rb:98:in `block in constantize'\",\"/home/railsapps/public_html/my_app/shared/bundle/ruby/2.5.0/gems/resque-2.1.0/lib/resque.rb:92:in `each'\",\"/home/railsapps/public_html/my_app/shared/bundle/ruby/2.5.0/gems/resque-2.1.0/lib/resque.rb:92:in `constantize'\"],\"worker\":\"sandbox:12622:create_contacts_from_csv\",\"queue\":\"create_contacts_from_csv\"}",
```

I can manually run this via `QUEUE=* bin/rake resque:work`. It's just the background process that fails.

I'm in the middle of upgrading from Rails 4 to 5. Everything in Rails 4 works fine. Here are the latest config files I'm working with:

**lib/tasks/resque.rake**
```ruby
require 'resque'
require 'resque/tasks'
require 'resque/scheduler/tasks'

task 'resque:setup' => :environment
```

**config/resque.yml**
```ruby
development: <redis endpoint>
staging: <redis endpoint>
sandbox: <redis endpoint>
production: <redis endpoint>
```

**Rakefile**
```ruby
require_relative 'config/application'

Rails.application.load_tasks
```

**My system:**
* Ubuntu 18.04
* Apache Passenger 6.0.10
* Ruby 2.5.8
* Rails 5.2.6
* Resque 2.1
* resque-scheduler 4.4.0
* Capistrano for deployment

**Comment by mmarinaccio** [comment]
I downgraded to Resque version `1.27.2`, which fixed my issue.

**Comment by iloveitaly** [comment]
@mmarinaccio which environments do you run into this error? Do you have eager_load enabled on these environments?

My guess is something changed between rails 4 => 5 with eager loading and that's causing the issue.

**Comment by richardkmiller** [comment]
FYI, I ran into this issue too, with a similar stack to @mmarinaccio. It looked intermittent. It turned out that the Resque worker wasn't being restarted after each deploy. My hypothesis is that after deploying more times than Capistrano's `:keep_releases`, the code being used by the long-running Resque process is deleted, resulting in this "uninitialized constant" error for the job's class. I didn't confirm this, but I'm going to restart the Resque worker process after each deploy and see if that solves it.

I'm using an `after :deploy` hook in Capistrano to kill the Resque worker process:

```ruby
desc "Stop Resque worker, so it can be restarted (via cron)"
task :stop_resque do
  on roles(:all) do |host|
    execute %q(ps ax | grep [r]esque- | sed -re 's/^[ ]*([0-9]+) .*$/\1/g' | while read PID ; do echo "Stopping Resque running as PID $PID" ; kill -s TERM $PID ; done)
  end
end

after :deploy, :stop_resque
```

I use a cron job with `run-one` to restart Resque and keep it running:

```
* * * * * production cd /var/www/app/current && run-one bundle exec rails resque:work QUEUE=* 
```

**Comment by mmarinaccio** [comment]
I ended up coming back to this issue, since I needed some of the new failure hooks introduced in Resque 2+. The problem seems to only occur for job classes defined in files in a subdirectory to `<rails_root>/app/job`. For example, all of my jobs located in `<rails_root>/app/job/subdir` will fail with this error.

I'm sure there's a way to fiddle with autoloading paths and [enable rake eager loading](https://github.com/rails/rails/pull/28209), but simply moving the files up a directory was the simplest fix for me.
