### ISSUE TITLE
FATAL: prematurely zombied

### ISSUE THREAD

**Issue by swistak** [resque/resque#1779]
Sorry but I can't provide anything more because despite setting logger to debug nothing gets logged.

```
QUEUE=default rake resque:work --trace
** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute resque:setup
** Execute resque:preload
** Invoke resque:setup
** Execute resque:work

FATAL: prematurely zombied

FATAL: prematurely zombied

FATAL: prematurely zombied
```

I've set up the initializer with:

```
  Resque.logger = Logger.new(Rails.root.join('log', "resque_#{Rails.env}.log"))
  Resque.logger.level = Logger::DEBUG
```

But it does not seem to add any backtrace or other error information.

Verison: 2.0.0

**Comment by varyonic** [comment]
I don't have an answer, but you might get better help asking on StackOverflow, eg. https://stackoverflow.com/questions/60784255/i-have-this-error-when-i-try-to-run-rails-s

**Comment by swistak** [comment]
It looks like it might be unrelated to the resque, it just manifets then, so I'm going to close it.

The question you posted seems completely unrelated
