### ISSUE TITLE
Question about how to handle a pipe when forking

### ISSUE THREAD

**Issue by estolfo** [resque/resque#1782]
Hi Resque team, I also opened this in the [Puma repo](https://github.com/puma/puma/issues/2776), as it also forks processes. I thought maybe you would have some ideas too.
This isn't a bug report but rather a request for advice. I'm dealing with a "bug" in the [Elastic Ruby APM agent](https://github.com/elastic/apm-agent-ruby) and I wanted to ask you if you've heard of someone having this issue in the past and how they resolved it. It's not exactly a bug in the agent, more like a limitation of Ruby and forking.

The Ruby agent is a singleton and uses a `IO.pipe` to send data to the APM server. When the parent process is forked, the child inherits the `reader`s and (gzip)`writer`s. I create new `reader`s and `writer`s in the child process so that I don't interfere with the parent's work.
When the fork exits, I close the child's `reader`s and `writers` but I see the follow error
```
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```
because the parent's `writer` is still considered living in the child process.
One option to address this error is to create a finalizer on the writer that closes it. But then I get intermittent errors from the APM server saying the gzipped data's header is invalid. I'm assuming this is because the (parent's) writer is closed by the child before the compression is complete in the parent.

Have you heard of an issue like this before? Do you have any ideas on how to handle it?
Thanks!

**Comment by iloveitaly** [comment]
I don't have experience with `IO.pipe` specifically, but this is the sort of thing that we've done for redis: https://github.com/resque/resque/commit/b739f835105511270200f5037ddb368d676f297e

We don't need to detail with IO streams directly in the resque logic, so not sure if we are too much help.
