### ISSUE TITLE
Stats page does not properly display redis server

### ISSUE THREAD

**Issue by rs-mfurlender** [resque/resque#1785]
`Resque.redis_id` used to return `Resque.redis.client.id`  which looks like `redis://127.0.0.1:6379/0`, but now it returns `Resque.redis.identifier` which looks like `<Redis::Namespace v1.7.0 with client v4.1.4 for redis://127.0.0.1:6379/0/resque>`

This causes the Redis server URL to not render properly in the `stats` page:

![image](https://user-images.githubusercontent.com/91906707/148284449-40932594-3148-4b42-93e8-845c3763c489.png)

Is there any workaround for this?

I am using version 2.2.0.

Thanks!

**Comment by iloveitaly** [comment]
@rs-mfurlender it looks like most of this info is sourced from `redis.info`:

https://github.com/resque/resque/blob/master/lib/resque/server/views/stats.erb

My guess is the data returned by the redis ruby gem has changed. Feel free to submit a PR for any improvements here.

**Comment by trapper-** [comment]
It just needs to be escaped properly.

**Comment by iloveitaly** [comment]
PRs are welcome to fix this!

**Comment by mishina2228** [comment]
#1832 and #1834 are merged, so this will be fixed in the next release.

**Comment by mishina2228** [comment]
@PatrickTulskie We can close this now that [v2.5.0](https://github.com/resque/resque/releases/tag/v2.5.0) has already been released.
