### ISSUE TITLE
redis gem has sort of deprecated redis.pipelined

### ISSUE THREAD

**Issue by danlo** [resque/resque#1794]
Greetings,

The redis gem is now deprecating the usage of redis.pipelined w/o a block being passed to it

Here is the warning: from this line of code:
https://github.com/redis/redis-rb/blob/master/lib/redis/pipeline.rb#L56 

```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

(called from .../redis-namespace-1.8.2/lib/redis/namespace.rb:530:in `namespaced_block'}
```

The resque code has the following usages of pipelined:

```
lib/resque.rb:    sizes = redis.pipelined do
lib/resque.rb:    samples = redis.pipelined do
lib/resque/data_store.rb:        @redis.pipelined do
... (several more)...
```

Thank you!

-daniel

I would try and fix this as it seams simple, however, I'm not confident in my ruby multithreading skills to attempt to create a fix that would work for everyone.  (Sorry!)

**Comment by jrochkind** [comment]
This isn't "sort of", this is deprecated, right?

These all over my logs are kind of annoying! 

It looks like there's already an open PR.  Are there any active maintainers who might want to assist on this?  @iloveitaly ?

**Comment by matthieubrau** [comment]
Hello,
There is a PR but nobody to merge it ?
https://github.com/resque/resque/pull/1796

**Comment by atruskie** [comment]
I think this was covered by https://github.com/resque/resque/pull/1806

**Comment by anacarolinacastro** [comment]
Do you have a prediction date for the new gem version release?

**Comment by iloveitaly** [comment]
@anacarolinacastro not yet! Unfortunately my time is limited to work on this. [Sponsoring me](https://github.com/sponsors/iloveitaly) would help me allocate more time here :)

**Comment by mishina2228** [comment]
@danlo (Cc: @PatrickTulskie, @iloveitaly)
resque [v2.3.0](https://github.com/resque/resque/releases/tag/v2.3.0) (the latest is [v2.4.0](https://github.com/resque/resque/releases/tag/v2.4.0)), which address this issue, has already been released.
So I believe we can close this issue (like https://github.com/resque/resque-scheduler/issues/745).

**Comment by PatrickTulskie** [comment]
@mishina2228 thanks!
