### ISSUE TITLE
Redis 5.0.0 Returning Integer message

### ISSUE THREAD

**Issue by yilmaz-burak** [resque/resque#1820]
Hey,
I am getting
```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /var/lib/gems/2.7.0/gems/redis-namespace-1.9.0/lib/redis/namespace.rb:479:in `call_with_namespace')
```
when running worker and enqueuing. However, application works as expected.

Is that just me or a general thing? If so, is that important and do you plan to do something about it?

Love the product btw. Thanks!

**Comment by burak-upstash** [comment]
Okay, at first i thought it was about Redis 6 vs Redis 5 kind of thing, but it seems that ruby-redis guys are about to release their v5...

**Comment by yilmaz-burak** [comment]
Okay, at first i thought it was about Redis 6 vs Redis 5 kind of thing, but it seems that ruby-redis guys are about to release their v5...

**Comment by PatrickTulskie** [comment]
Kind of a weird warning they are returning here. Resque isn't actually doing anything with the response, it just wants to add/remove from some sets so it will continue to function as expected.

In the interim if you want to silence the warnings, you can do this:
`Redis.sadd_returns_boolean = true`

I'll work through the code a bit and see if we need to apply a similar change, or if we need to change to the boolean method. It just feels un-ruby-like to add `?` to methods that are in fact making changes.

**Comment by PatrickTulskie** [comment]
@yilmaz-burak what version of the redis gem are you using? 4.8.0?

**Comment by yilmaz-burak** [comment]
Yeah, started getting these warnings when bumping to 4.8.0 from 4.7.1

**Comment by ozzyaaron** [comment]
@PatrickTulskie AFAICT from what we see it only happens at startup. Unlike the [previous pipelining deprecation](https://github.com/resque/resque/pull/1817) which happened every call, this only seems to happen once upon Resque initialization.

**Comment by PatrickTulskie** [comment]
Awesome thanks! Super helpful
