### ISSUE TITLE
Unknown keyword: thread_safe with redis 5.0.1

### ISSUE THREAD

**Issue by sl0thentr0py** [resque/resque#1821]
The `redis` gem just had a new breaking release which seems to cause this to fail.

```
      Failure/Error: Resque.redis.del "queue:default"

      ArgumentError:
        unknown keyword: thread_safe
```

Maybe we need to pin the `redis` dependency here to < 5
https://github.com/resque/redis-namespace/blob/master/redis-namespace.gemspec#L30

**Comment by casperisfine** [comment]
Would be easier to remove the `thread_safe` options here: https://github.com/resque/resque/blob/ba5a44294ba5f6c4593deb78612f78989445d83e/lib/resque.rb#L123

Which is a noop since over a decade.

**Comment by sl0thentr0py** [comment]
thx @casperisfine, I'll make a PR but this repo looks pretty dead, not sure what the maintenance status is and who's doing merges/releases.

**Comment by casperisfine** [comment]
I believe @iloveitaly recently took over maintenance.

**Comment by iloveitaly** [comment]
@PatrickTulskie can you take a look?

**Comment by casperisfine** [comment]
Honestly I looked a bit more, and Resque assumes a bunch of things on Redis internal in several places. So short term locking to `redis 4.x` is likely preferable.

**Comment by iloveitaly** [comment]
Want to submit a PR for this?

**Comment by sl0thentr0py** [comment]
@iloveitaly yea I'll submit a PR pinning redis in a bit.

**Comment by PatrickTulskie** [comment]
Yeah I just checked and can confirm @casperisfine is correct... redis has been `thead_safe: true` by default since 2.2.0. We can safely remove that option. If someone beats me to a PR for it, I'll get a patch release out today for resque.

That said, I haven't tested this against redis 5.0 since it just came out a few hours ago and it looks like there potentially other breaking changes. I'd prefer to not pin to < 5 if we can avoid it but depending on how ugly this is we may not have a choice. There's also a deprecation warning in #1820 that we probably need to fix for Redis 5 compatibility.

**Comment by sl0thentr0py** [comment]
@PatrickTulskie 
I'll make both PRs and leave it up to you to decide.

**Comment by DennisWormald** [comment]
I just got the following with ruby 2.7.2, Rails 5.2.8.1, and using Resque 2.3.0
when upgrading from redis 4.8 to 5.0.1 :

"ArgumentError: unknown keywords: :thread_safe, :reconnect_delay, :reconnect_delay_max"
I have now pinned to redis 4.8 which has worked for now - just thought I would let you know about the extra keywords on top of thread safe.

**Comment by PatrickTulskie** [comment]
@DennisWormald Awesome. If you can, would you mind filing a bug ticket and/or submitting a PR to fix? May just ship off a version today that pins to Redis < 5.0 to buy some breathing room until we can work through the other compatibility issues.

**Comment by DennisWormald** [comment]
> @DennisWormald Awesome. If you can, would you mind filing a bug ticket and/or submitting a PR to fix? May just ship off a version today that pins to Redis < 5.0 to buy some breathing room until we can work through the other compatibility issues.

@PatrickTulskie I think I figured out the issue, in my resque-pool.rb initializer file I have the following:

Resque.redis = Redis.new(:host => uri.host, :port => uri.port, :password => uri.password, :thread_safe => true, :reconnect_attempts => 10, :reconnect_delay => 1.5, :reconnect_delay_max => 10.0, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE })

Do you think I can safely remove the ":reconnect_delay => 1.5, :reconnect_delay_max => 10.0" keywords? I can't find why they are there or what they do!

**Comment by PatrickTulskie** [comment]
Hard to say. Might have to look into the redis config options for 5.0 to see if there is an equivalent or something. Personally I don't use those options in my projects.

**Comment by DennisWormald** [comment]
thanks @casperisfine - that did work, the app was able to successfully build itself now. However I am now having other issues with a different error that I posted about here: #1825

**Comment by casperisfine** [comment]
I fixed the remaining outstanding issues in https://github.com/resque/resque/pull/1828, the test suite is now green with 5.0 and 4.8.

**Comment by DennisWormald** [comment]
thanks @casperisfine - however I have one more question. As I am also using resque-pool, this update breaks its functionality for me. I have submitted a issue for it here: https://github.com/nevans/resque-pool/issues/207

I was able to get everything to load correctly I believe, by making a change to what the resque-pool readme.md suggests we put in the rake task config (/lib/tasks/resque.rake)

I have removed some code that was suggested to be included in the rake file, and everything _appears_ to be working fine now. Does this make sense to you that I would remove this code below? Any input appreciated thanks :)

```
task "resque:pool:setup" do
  # close any sockets or files in pool manager
  ActiveRecord::Base.connection.disconnect!
  # and re-open them in the resque worker parent
  Resque::Pool.after_prefork do |job|
    ActiveRecord::Base.establish_connection
  end
end
```

and 

```
task "resque:pool:setup" do
  Resque::Pool.after_prefork do |job|
    Resque.redis.client.reconnect
  end
end
```

**Comment by casperisfine** [comment]
Yeah, `resque-pool` would needs an update as well.

But maybe at this point it may make sense to introduce `_client.reconnect` back, it's just that to me `_client` always have been a private API, so I'm not really keen on adding it back.

**Comment by casperisfine** [comment]
Nevermind, reading the resque-pool issue, the problem isn't in resque-pool but int he code it suggest to add in your Rakefile. It's easily replaced by `Resque.redis.close`.
