### ISSUE TITLE
Redis 5.0 Private Method Reconnect

### ISSUE THREAD

**Issue by PatrickTulskie** [resque/resque#1825]
Working through some of the issues with redis-rb 5.0... when running the tests with github, the CI runner would hang as soon as it started running specs. I did some debugging and found it was erroring out here:

```
/home/runner/work/resque/resque/lib/resque/server.rb:121: warning: instance variable @partial not initialized
/home/runner/work/resque/resque/lib/resque/server.rb:121: warning: instance variable @partial not initialized
/home/runner/work/resque/resque/lib/resque/server.rb:121: warning: instance variable @partial not initialized
/home/runner/work/resque/resque/lib/resque/data_store.rb:82:in `reconnect': private method `connect' called for #<Redis::Client redis://localhost:9736/0> (NoMethodError)
Did you mean?  connected?
	from /home/runner/work/resque/resque/test/child_killing_test.rb:27:in `block in start_worker'
	from /home/runner/work/resque/resque/test/child_killing_test.rb:25:in `fork'
	from /home/runner/work/resque/resque/test/child_killing_test.rb:25:in `start_worker'
	from /home/runner/work/resque/resque/test/child_killing_test.rb:81:in `block (2 levels) in <top (required)>'
```
The method reconnect in resque data_store calls connect again in the child after forking without closing the connection in the parent. For some reason that method is now private so we gotta come up with a work around.

**Comment by DennisWormald** [comment]
Could this explain why this no longer works? I have the following code in my resque.rake task:

task "resque:pool:setup" do
  ActiveRecord::Base.connection.disconnect!
  Resque::Pool.after_prefork do |job|
    ActiveRecord::Base.establish_connection
    Resque.redis._client.reconnect
  end
end

**Comment by casperisfine** [comment]
Yeah, that method was private API and is no longer usable in 5.x. 

I looked at it, and I'm not 100% sure what Resque was doing here. I think it does reconnect all the clients after fork, but just discard old connections without closing them to avoid impacting the parent.

Which is a bit weird to me because Ruby GC will automatically close connections when it collect them, but maybe `auto_close = false` was set somewhere. I'll have to dig into that.
