### ISSUE TITLE
Redis 5.0 seems to break resque 

### ISSUE THREAD

**Issue by pawelkomarnicki** [resque/resque#1826]
I get the following exception: `TypeError: Unsupported command argument type: Resque::Worker` right after I upgrade Redis to 5.x

**Comment by gtstore** [comment]
I am getting the same exception. How to fix it?

**Comment by PatrickTulskie** [comment]
Are you using resque-pool by any chance? And does resque 2.4.0 fix this for you?

**Comment by ozzyaaron** [comment]
This error was fixed for us by updating to Resque 2.4.0. 

Also we fixed another issue where in development our Redis URLs had trailing slashes e.g. `REDIS_URL=redis://localhost:1234/` and we had to remove the trailing slash.

**Comment by PatrickTulskie** [comment]
Sweet! Alright I'll close this for now but if more issues pop up let's get some new tickets opened.
