### ISSUE TITLE
Cannot GET `localhost` but can GET `127.0.0.1`

### ISSUE THREAD

**Issue by juanca** [resque/resque#1845]
Hello. I encountered an issue with our resque jobs in our Rails application. I am making an HTTPS request to a service running on some port on `localhost`. And an error pops up.

```
uri = URI('https://localhost:3808/compiled/manifest.json')
data = Net::HTTP.get(uri)
Errno::ECONNREFUSED: Failed to open TCP connection to localhost:3808 (Connection refused - connect(2) for "fe80::1%lo0" port 3808)
from /Users/juanca/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
Caused by Errno::ECONNREFUSED: Connection refused - connect(2) for "fe80::1%lo0" port 3808
from /Users/juanca/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
```

I figured I could mess with my hosts file. Here are the relevant bits:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

fe80::1%lo0     localhost
```

If I comment out the `fe80::1%lo0     localhost` and `::1             localhost` then the GET request works. 

Has anyone encountered any weird domain resolution with resque before? FWIW, the same code works in an IRB or `rails console` session.

**Comment by PatrickTulskie** [comment]
Never seen that happen before. My resque instances are able to interact with localhost just fine. Are you sure this isn't a configuration issue on your machine?

**Comment by PatrickTulskie** [comment]
Thanks!
