### ISSUE TITLE
Unsupported command argument type: TrueClass.  Migration from redis gem v4 to v5

### ISSUE THREAD

**Issue by mikebewell** [resque/resque#1858]
Resque version: 2.4.0
Our application uses  Redis gem (4.7.1)  https://github.com/redis/redis-rb
Right after upgrades to Redis gem (5.0.6) many of our jobs start failing with the following error:

```
Unsupported command argument type: TrueClass
/artifacts/bundle/ruby/3.1.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:37:in `block in generate'
/artifacts/bundle/ruby/3.1.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `map!'
/artifacts/bundle/ruby/3.1.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `generate'
/artifacts/bundle/ruby/3.1.0/gems/redis-client-0.12.1/lib/redis_client.rb:222:in `call_v'
/artifacts/bundle/ruby/3.1.0/gems/redis-5.0.6/lib/redis/client.rb:73:in `call_v'
/artifacts/bundle/ruby/3.1.0/gems/redis-5.0.6/lib/redis.rb:167:in `block in send_command'
/artifacts/bundle/ruby/3.1.0/gems/redis-5.0.6/lib/redis.rb:166:in `synchronize'
/artifacts/bundle/ruby/3.1.0/gems/redis-5.0.6/lib/redis.rb:166:in `send_command'
/artifacts/bundle/ruby/3.1.0/gems/redis-5.0.6/lib/redis/commands/strings.rb:169:in `msetnx'
/artifacts/bundle/ruby/3.1.0/gems/redis-namespace-1.10.0/lib/redis/namespace.rb:558:in `wrapped_send'
/artifacts/bundle/ruby/3.1.0/gems/redis-namespace-1.10.0/lib/redis/namespace.rb:515:in `call_with_namespace'
/artifacts/bundle/ruby/3.1.0/gems/redis-namespace-1.10.0/lib/redis/namespace.rb:389:in `block (2 levels) in <class:Namespace>'
/artifacts/bundle/ruby/3.1.0/gems/resque-2.4.0/lib/resque/data_store.rb:65:in `method_missing'
/artifacts/bundle/ruby/3.1.0/gems/resque-workers-lock-2.0.1/lib/resque/plugins/workers/lock.rb:62:in `before_perform_workers_lock'
Worker
```

Please advise if Resque supports Redis gem v5 and above.

**Comment by mishina2228** [comment]
Hi, I believe this is the problem with resque-workers-lock gem.

https://github.com/bartolsthoorn/resque-workers-lock/blob/eca2db692d80880b646127deeed60c1607ed7837/lib/resque/plugins/workers/lock.rb#L62

```ruby
if Resque.redis.msetnx lock_result.zip([true]*lock_result.size).flatten
```

In redis-rb v5, it's no longer possible to pass Boolean values. A String must be passed instead.
Please refer to the following comments:
- https://github.com/redis/redis-rb/issues/1142#issuecomment-1279910777
- https://github.com/redis/redis-rb/issues/1173#issuecomment-1375585609

**Comment by mikebewell** [comment]
Hello @mishina2228,  thank you very much for the response.  Do you know if Resque provides functions to check whether the job is already running?  If it does, then I could exclude the resque-workers-lock gem.

**Comment by PatrickTulskie** [comment]
I don't think there is anything natively built in for that. You can use https://github.com/resque/resque-loner to prevent multiple insertions of the same job though. Typically I do state tracking in our relational databases and abort the job if it's marked in progress by something else though.

**Comment by mishina2228** [comment]
I'm using [`Resque.working`](https://github.com/resque/resque/blob/f8444d33ff5f34857168537d1d9d5adb35a68b05/lib/resque/worker.rb#L75-L77) and [`Resque::Worker#job`](https://github.com/resque/resque/blob/f8444d33ff5f34857168537d1d9d5adb35a68b05/lib/resque/worker.rb#L774-L778) to check running jobs.
I didn't know about [resque-loner](https://github.com/resque/resque-loner). Thanks for sharing! @PatrickTulskie

**Comment by mikebewell** [comment]
Thank you for your responses.  I am closing the issue as it is caused by another gem.
