### ISSUE TITLE
resque-status is not compatible with Resque > 2

### ISSUE THREAD

**Issue by alain-andre** [resque/resque#1870]
Hi there, we are looking to manage status and found in your plugin list `resque-status` but the gem is not compatible for Resque > 2. 

I could not figure how to do that with your actual code, any help ?

**Comment by PatrickTulskie** [comment]
Unfortunately it looks like that plugin hasn't been updated in a while. There is a pull request on the repo for 2.0. You could potentially try running a fork of that.

https://github.com/quirkey/resque-status/pull/135

**Comment by alain-andre** [comment]
Thank you @PatrickTulskie 
There is a fork using this PR: https://github.com/powerhome/resque-status 
We use it now.
