### ISSUE TITLE
DirtyExit VS PruneDeadWorkerDirtyExit - what is the difference?

### ISSUE THREAD

**Issue by idanab-simplee** [resque/resque#1877]
Hi
Is that accurate to say that when a job was killed with the `PruneDeadWorkerDirtyExit` exception, it means that it is **currently** not running any code inside `perform()`?  

I am assuming that from looking at the place where Resque raises those exceptions:
https://github.com/resque/resque/blob/ae3fe72d0c3c02340e9b5b9d5677c0bd7c733ba5/lib/resque/worker.rb#L627

**Comment by jeremy** [comment]
It's never raised, actually. It's recorded as the reason a job presumably failed when Resque detects that the worker process hasn't checked in with a recent heartbeat.

> If a server is killed by a hard shutdown, power failure, or something else beyond our control, the Resque workers will not die gracefully and therefore will leave stale state information in Redis.
> 
> By checking the current Redis state against the actual environment, we can determine if Redis is old and clean it up a bit.

https://github.com/resque/resque/blob/ae3fe72d0c3c02340e9b5b9d5677c0bd7c733ba5/lib/resque/worker.rb#L600-L609
