### ISSUE TITLE
Please publish security advisories for XSS vulnerabilities

### ISSUE THREAD

**Issue by G-Rath** [resque/resque#1888]
It seems like there have been a number of XSS vulnerabilities patched over the years:
   * v2.6.0: https://github.com/resque/resque/pull/1865
   * v2.2.1: https://github.com/resque/resque/pull/1790
   * v2.1.0: https://github.com/resque/resque/pull/1687 & https://github.com/resque/resque/issues/1679

However [no security advisories have been posted](https://github.com/advisories?query=resque) for these meaning they will not be reported by tools like dependabot or `osv-scanner` - we ourselves recently got pinged about this through a pentest on one of our applications.

Could you please post advisories for the above? This can easily be done through [GitHub](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/creating-a-repository-security-advisory), and once the advisories are published the community can suggest improvements for them so they don't have to be perfect right out the gate :)

(note I did previously post somewhere asking this for one of the above vulnerabilities, but I can't actually find that comment anymore and realised there's a couple of them anyway so decided to open this issue instead 😅)

**Comment by PatrickTulskie** [comment]
Thanks @G-Rath. I'm gonna take a look at that and see if I can get those in. Should have some time in the next week to take care of this and also take a pass through and deal with any other pending security-related items.

**Comment by PatrickTulskie** [comment]
Just wanted to update this really quick. I prepped security advisories for all of those issues you mentioned above and they are currently pending CVEs. Hopefully they will all hit the wire next week.
