### ISSUE TITLE
Dynamic queue choice

### ISSUE THREAD

**Issue by alg** [resque/resque#254]
Hi there. Thanks for the great tool!

I'm in the need (and plan to work on) the feature when the queue name isn't fixed, but is chosen on the job to job basis even though enqueued from the same class. Say I have multiple endpoints for message sending and I want to have separate queues for them, but the same job class -- SendMessage. Every endpoint has its own unique configuration of throughput etc etc, so it's definitely an endpoint-per-queue situation (unless I'm missing something).

My idea is to let the SendMessage class decide on the queue name. In the vein with current implementation when you can have self.queue method to return the queue name, I would like to let it have arguments, which would be the arguments passed to self.perform, and let it return the queue name basing on that. Of course, maintaining backward compatibility with parameter-less method and class variable (@queue).

What would you say? Useful and worth a pull request?

Cheers,
- A

**Comment by leoplct** [comment]
I have the same need. I would like to use a :slow queue for scheduled task and :urgent queue for in-demand task. Both sharing the same Job's code. How can achieve it?
