### ISSUE TITLE
Workers can't be killed

### ISSUE THREAD

**Issue by Bek** [resque/resque#299]
When I do "resque list" for workers, I see:

dn0a21b25e.sunet:4462:\* (idle)
Ulugbek-Baymuradovs-MacBook.local:6656:\* (idle)

However "ps -e -o pid,command | grep [r]esque" doesn't show anything. When I try to kill these workers, I get "No such process" error. The same workers show up in resque-web interface, but any attempt, kill -9 or Process.kill(0, pid) returns "No such process" error. I checked whether these were zombie processes but result is negative. It is happening locally in Mac, but not in production. It used to be only the first worker, but every time I start a worker in development environment, it seems to add another worker. How can I kill them?

Update: Redis server logs from the terminal shows 0 clients connected when this happens.

**Comment by deepsystm** [comment]
> 
> 
> Just wanted to add info for anyone else with this problem... The prune_dead_workers will not work if the workers were created under a different hostname. I have some that have stuck around under an old hostname that was there when the machine was being setup initially and I've been staring at them not existing yet listed for a while.
> 
> If this is the case you have to, as far as I can tell, kill them off individually in irb. I ended up doing:
> 
> ```
> require 'resque'
> Resque.workers[8].unregister_worker
> Resque.workers[9].unregister_worker
> ...
> ```

Worked fine!
