### ISSUE TITLE
When a Worker get a Job and crashes the Job should be retried by another Worker

### ISSUE THREAD

**Issue by Nerian** [resque/resque#300]
Hello,

Let say we have the queue Render. This queue Render has 2 Jobs. There are two Workers.

If one of the Workers starts working on a Job and the process is killed before completing its Job, then the Job should be retried by other Worker.  Currently the job just disappear when the worker start to work on it. So if the worker is killed prematurely the job is lost.

I think it would be better if Jobs were not removed from the queue but instead just marked with the Worker who is processing it. If that worker disappears then the Job is free again and another Worker can get to work on it. That way failures on Workers won't affect the completion of Jobs.

What do you think? Maybe I am misunderstanding something but it seems logical to me. I hope you can help me here.

**Comment by discordianfish** [comment]
I assume nothing has change in the *checks date* 11 years?
