### ISSUE TITLE
ActiveRecord::RecordNotFound problem

### ISSUE THREAD

**Issue by jer0m** [resque/resque#347]
Hello,

All is in the subject. Sometimes, I have this error in failed tasks. When I look on DB, the object exists, if I click on retry, the task works.

It happens sometimes but not all the time. Anyone has an idea about my problem?

Thank you
Jerome

**Comment by rajdeepbhatia** [comment]
I am facing the similar issue, is there any foolproof workaround/solution to this problem?

**Comment by chrisccerami** [comment]
What exactly is the issue? We'll need more information in order to help.
