### ISSUE TITLE
 unexpected EOF on client connection

### ISSUE THREAD

**Issue by gravis** [resque/resque#367]
Hello,

we have noticed a lot of :

```
2011-08-24 15:24:00 CEST LOG:  could not receive data from client: Connection reset by peer
2011-08-24 15:24:00 CEST LOG:  unexpected EOF on client connection
```

in our log. After some digging, the disconnections are coming from resque. Sounds like everytime a job is done, the worker doesn't close nicely the connection.

This issue is related to #306 : we have to establish a connection on forking.
I've tried to disconnect cleanly in done_working, but the working is dying when doing that.
Any idea ?

**Comment by kellyfelkins** [comment]
What is the status of this? I'm getting these errors on a rails 4 project on Heroku running resque. I added this initializer suggested on the Heroku site:

#config/initializers/resque.rb
```ruby
Resque.before_fork do
  defined?(ActiveRecord::Base) and
    ActiveRecord::Base.connection.disconnect!
end

Resque.after_fork do
  defined?(ActiveRecord::Base) and
    ActiveRecord::Base.establish_connection
end
```

Specifically I'm seeing this:

```2015-09-13T00:25:13Z app[postgres.16251]: [DATABASE] could not receive data from client: Connection reset by peer```

Apparently after a resque job completes -- though I don't think I see it after all resque jobs complete. Also, it seems like the jobs are working fine.

Thank you.

**Comment by rg** [comment]
@kellyfelkins I also added the suggested code in an initializer. But I just solved this issue by removing some errant calls to `ActiveRecord::Base.establish_connection` in models that some of our Resque workers were persisting. Those workers were thus mishandling the connection, producing the exception

`ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: EOF detected`

in addition to the `could not receive data from client: Connection reset by peer` messages, even though the jobs were successful, as in your case.

So it might be obvious, but you may want make sure the database connection isn't being manipulated inappropriately by code your workers are running.

**Comment by cyberhobo** [comment]
I'm seeing the exact behavior @kellyfelkins describes after upgrading my PostgreSQL plan on Heroku. It's possible this was happening before as well, but wasn't getting logged - either way I'd love to know if anyone resolves it.

**Comment by nakhli** [comment]
:+1: as @kellyfelkins

**Comment by mjhuddie** [comment]
Interesting !!

**Comment by mjhuddie** [comment]
Is it possible we are calling establish_connection somewhere inappropriate ?

**Comment by Aeramor** [comment]
I've tried all the variations listed here and some that are not and still have this issue.

**Comment by mkblackwell** [comment]
We were having exactly this same problem... We solved it by adding this hook to the worker task:

    def self.after_perform(*args)
        ActiveRecord::Base.connection.disconnect!
    end

For the record, here's our `resque.rake`:

    require "resque/tasks"
    require "resque/pool/tasks"
    require "#{Rails.root}/lib/eventprocessor"

    task "resque:setup" => :environment do
      ENV['QUEUE'] ||= '*'
    end

    task "resque:pool:setup" do
      # close any sockets or files in pool manager
      ActiveRecord::Base.connection.disconnect!
      # and re-open them in the resque worker parent
      Resque::Pool.after_prefork do |job|
        ActiveRecord::Base.establish_connection
        Resque.redis.client.reconnect
      end
    end
