### ISSUE TITLE
Heroku sends SIGTERM to Resque

### ISSUE THREAD

**Issue by defunkt** [resque/resque#368]
Related to #319

Heroku sends `TERM` to a process when it needs to gracefully shut down.

To Resque, `TERM` means "Immediately kill child then exit" while `QUIT` means "Wait for child to finish processing then exit".

This is the **reverse** of what these signals normally mean. Resque intentionally strays from Good Unix Practices™ to emulate nginx's signal handling. Unicorn also reverses these signals.

Perhaps we should have a `resque-heroku` gem that fixes the two bits causing the most problem. `resque-heroku` could flip Resque's `TERM` and `QUIT` handling so it behaves correctly on Heroku.

**Comment by chrishough** [comment]
It looks like this is still an issue in `resque (1.26.0)`

![screen shot 2017-01-14 at 5 16 19 pm](https://cloud.githubusercontent.com/assets/744056/21959461/36ec9458-da7d-11e6-876c-da2f0ce2ceb9.png)
