### ISSUE TITLE
Resque fails to load assets when run on Rails 3.1

### ISSUE THREAD

**Issue by daliborfilus** [resque/resque#418]
Hi,
I've added

``` ruby
mount Resque::Server, :at => '/resque-admin'
```

to my routes.rb, it works nice on development, but fails to load images/stylesheets/javascripts on production and when (via view source) I click on https://.../resque-admin/reset.css it shows weird Routing error with message:

No route matches [GET] "/opt/ruby-enterprise-1.8.7-2010.03/lib/ruby/gems/1.8/gems/resque-1.19.0/lib/resque/server/public/reset.css"

I know that Rails 3.1 has asset pipeline, but since this is standalone sinatra app it shouldn't matter, right?
Is it my fault or whats going on? Any hints welcome :)

Env:
Ruby EE 2010.03
Resque 1.19.0
Rails 3.1.0

production.rb:

``` ruby
  config.serve_static_assets = false
  config.assets.digest = true
```

**Comment by chrishough** [comment]
I am seeing this now on our servers? https://github.com/resque/resque-web/issues/117

**Comment by MothOnMars** [comment]
I ran into this on Rails 6. I updated the FAQ with the instructions for Apache: 
https://github.com/resque/resque/wiki/FAQ#apache

Related:
https://github.com/mperham/sidekiq/wiki/FAQ#why-dont-cssjsimg-assets-load-properly-when-i-go-to-sidekiqs-web-ui
https://github.com/ejschmitt/delayed_job_web#serving-static-assets
