### ISSUE TITLE
Retry failed Jobs

### ISSUE THREAD

**Issue by elefante** [resque/resque#548]
I am using resque to send emails to a huge list of users. The failed jobs goes to the failed queue, as expected.
When I click 'Retry failed jobs', and it fails again, the failed queue doubles in size, resulting in two identical emails for each user.
There are any feature, or configuration that empty the failed queue when I hit "Retry failed jobs"?

**Comment by jaredbeck** [comment]
Maybe if the button text were "Enqueue copies of failed jobs" instead of "Retry failed jobs" there would be less confusion.
