### ISSUE TITLE
Ctrl-c doesn't kill the worker immediately when the redis IP is unreachable

### ISSUE THREAD

**Issue by thbar** [resque/resque#57]
Hello,

I came accross this: if I try to kill a worker that could not connect to Redis (eg: VPN not enabled when the worker started which means the IP is unreachable), it will wait until the connection attempt times out.

```
$ QUEUE=job_list VVERBOSE=1 VERBOSE=1 rake resque:work
Setting Resque.redis to 192.168.x.y:6390
*** Starting worker Macintosh.local:80864:job_list
*** Registered signals
^C*** Exiting...
^C*** Exiting...
^C*** Exiting...
rake aborted!
Operation timed out - connect(2)
```

For a first while I though maybe the signal wasn't intercepted on my platform.

Is it expected ? If not I can work on a patch for this later on.

-- Thibaut

**Comment by GKZX** [comment]
I create a rails app by jruby(version 9.0.4.0),when I run `env RESQUE_TERM_TIMEOUT=1 TERM_CHILD=1 QUEUE=critical bundle exec rake resque:work` it returns "The signal QUIT is in use by the JVM and not work correctly on this platform" How can I fix this error?

**Comment by thbar** [comment]
@GKZX did you find a way to work-around that warning?
