### ISSUE TITLE
Ability to remove dead workers from resque-web

### ISSUE THREAD

**Issue by betelgeuse** [resque/resque#596]
Scenario:
1. a worker server crasher
2. you go look at resque-web
3. under worker tab you can see all the workers from the crashed machine

Solution:

There should be a delete operation available for the admin to tell the the workers have crashed and will not be processing jobs any more.

**Comment by razvanphp** [comment]
Since we are stuck with resque 1.x because of php-resque, can we get a solution how to remove them directly from redis at least? where are they stored?

**Comment by RVN-BR** [comment]
Is this safe to run along with running workers?  Will workers that arent dead "recreate" themselves, or must we restart all workers after running this?
