### ISSUE TITLE
Defining a Resque Specification

### ISSUE THREAD

**Issue by josegonzalez** [resque/resque#709]
Hi all.

I've been looking into various queuing systems to see what would best fit our architecture. I keep coming back to Resque because it is:
- Redis backed
- Has multiple implementations in different languages
- Comes with a large community of plugins
- There is tons of documentation on it

So naturally quite a bit of our internal spec on a new queuing system involves things in Resque. So onto the issue at hand.

An important requirement of the queuing system is that it be available with the same featureset in every language we use the system in. Given that Resque already exists, and has various implementations, it's already ahead of the curve. We just don't know how it internally handles:
- Job Queuing, specifically the key/hash structures
- Retries (if at all?)
- Future job scheduling
- Batched Jobs

If we can get details as to what the 1.x branch supports - and how it works - as well as any potential changes in 2.x, that would help inform our decision, and perhaps even allow us to provide Resque API-compatible alternatives in other languages.

Obviously I can read the code - trust me, I love git more than most people ;) - but providing such a spec in a wikidoc would be #dagital. If this is the wrong forum, feel free to close, but also feel free to get in touch if I'm not throwing a wobbly here.

**Comment by steveklabnik** [comment]
Update: 2.0 is no longer happening, but this would still be nice to have.

**Comment by chrisccerami** [comment]
@steveklabnik I'd be glad to lend a hand here if needed. I don't think I'm familiar with Resque enough yet to lead the effort, but I'm happy to help out.

**Comment by steveklabnik** [comment]
Well, the first step shouldn't be tough: just write down what Resque actually _does_. There isn't a whole lot of 'design' to do here, at least until we have a full first spec.

**Comment by chrisccerami** [comment]
That much I can probably handle.

**Comment by jeremy** [comment]
Parking this as a perpetual nice-to-have. Resque is as Resque does, for years—OK to leave it at that for the time being.

**Comment by daudn** [comment]
Can I use Resque in Python with GKE?
