### ISSUE TITLE
Workers take 100% process usage on QUIT

### ISSUE THREAD

**Issue by iRyusa** [resque/resque#723]
Hello,

Every time we want to kill our workers it remains one process per worker who takes 100% processor usage. I have to manually do a kill -9 for each remaining process.

```ruby

	def run_worker(queue, count = 1)
		puts "Starting #{count} worker(s) with QUEUE: #{queue}"
		ops = {:pgroup => true, :err => [(Rails.root + "log/workers_error.log").to_s, "a"], 
														:out => [(Rails.root + "log/workers.log").to_s, "a"]}
		env_vars = {
			"QUEUE" => queue.to_s, 
			"BACKGROUND" => "yes",
			"INTERVAL" => "1"
		}

		pid_count = 0

		count.times {
			pid_path = "tmp/pids/resque_worker_" +  pid_count.to_s + ".pid"
			env_vars["PIDFILE"] = (Rails.root + pid_path).to_s

			## Using Kernel.spawn and Process.detach because regular system() call would
			## cause the processes to quit when capistrano finishes

			pid = spawn(env_vars, "rake environment resque:work", ops)
			Process.detach(pid)

			pid_count += 1
		}
	end

	desc "Quit running workers"
	task :stop_workers => :environment do
		pids = Array.new
		Resque.workers.each do |worker|
			pids.concat(worker.worker_pids)
		end
		if pids.empty?
			puts "No workers to kill"
		else
			syscmd = "kill -s QUIT #{pids.join(' ')}"
			puts "Running syscmd: #{syscmd}"
			system(syscmd)
		end
	end
	
	desc "Start workers"
	task :start_workers => :environment do
		run_worker(RESQUE_QUEUES, RESQUE_WORKERS_COUNT)
	end
```

We use this rake task to spawn/kill our workers.

We're using these gems 

	# resque
	gem 'resque', "= 1.23.0"
	gem 'resque-scheduler', "= 2.0.0", :require => 'resque_scheduler'
	gem 'resque-retry', "= 1.0.0"
	gem 'resque_mailer', '= 2.1.0'
	gem 'resque-lock', '= 1.0.0'

I've tried to remove the resque-lock from gemfile since the plugin is no more maintained, i've try to downgrade resque at 1.22 ( may be lower ? ). 

If you have any idea, thanks !

**Comment by steveklabnik** [comment]
This is still a bug as far as I know. It'd be really nice to get a contained example.

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
