### ISSUE TITLE
Connection Retry Code Not Retrying

### ISSUE THREAD

**Issue by claco** [resque/resque#737]
Long story longer; during all of the RedisToGo issues yesterday after Hurricane Sandy, we were constantly seeing workers die off when they randomly lost their connection to our R2Go instance. Restarting the workers always worked on the first try, so these weren't long term R2Go downtimes.

I started looking through the Resque 1.23 (we're on 1.21) change logs and notice the entries about connection failures and 3 automatic retries as described here from #687->#693 via @trevorturk, which would seem to have made yesterday more tolerable.

https://github.com/defunkt/resque/commit/d39046fd568e38c43ab049dcd21832ee87633e0e

To reproduce locally, I ran "rake environment resque:work QUEUE=cache VERBOSE=1".
Once loaded, I just restarted or killed my local redis-server.

This yields the following output, which doesn't appear to retry the connection at all after upgrading to 1.23:

*** Starting worker hank:5211:cache
*** Error reserving job: #<Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (ECONNREFUSED)>
*** /Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:268:in `rescue in establish_connection'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:263:in `establish_connection'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:69:in `connect'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:282:in `ensure_connected'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:173:in `block in process'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:248:in `logging'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:172:in `process'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis/client.rb:84:in `call'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis.rb:899:in `block in lpop'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis.rb:36:in `block in synchronize'
/Users/claco/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis.rb:36:in `synchronize'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-3.0.2/lib/redis.rb:898:in `lpop'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/redis-namespace-1.2.1/lib/redis/namespace.rb:257:in `method_missing'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque.rb:149:in `pop'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/job.rb:100:in `reserve'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque.rb:303:in `reserve'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:209:in `block in reserve'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:207:in `each'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:207:in `reserve'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:136:in `block in work'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:133:in `loop'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/worker.rb:133:in `work'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/resque-1.23.0/lib/resque/tasks.rb:36:in `block (2 levels) in <top (required)>'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/claco/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/bin/rake:19:in `load'
/Users/claco/.rvm/gems/ruby-1.9.3-p286@w3/bin/rake:19:in `<main>'
rake aborted!
Error connecting to Redis on localhost:6379 (ECONNREFUSED)

**Comment by mindware** [comment]
Would it be too tricky to get the main worker to keep retrying instead of simply dying?

**Comment by steveklabnik** [comment]
As far as I know, this is still a bug, but it would be nice to get some kind of reproduction.

**Comment by steveklabnik** [comment]
@mindware that sounds like a reasonable path forward

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!

**Comment by mindware** [comment]
@steveklabnik Just a quick note, I did see @claco provided some ways to reproduce, did those not help?

**Comment by steveklabnik** [comment]
@mindware consistency is what's important here... I tried it a few times and couldn't reproduce. Does it reproduce for you?
