### ISSUE TITLE
Can't enqueue string params contain non-bmp unicode characters

### ISSUE THREAD

**Issue by yuanxinyu** [resque/resque#739]
for example : 
use resque to encode a emoji smile character.
> Resque.encode(" ")    #The input textarea doesn't support emoji too, so can't see it.
=> "\\uf60a\""

but the actual value should be "\\u1f60a". Resque throw away the byte exceeds bmp range.

**Comment by steveklabnik** [comment]
It's been a very long time, and I'm still not sure this is Resque's fault, so closing.
