### ISSUE TITLE
Processes are not dying

### ISSUE THREAD

**Issue by link-er** [resque/resque#785]
Hello
I'm using rails (= 3.2.9) and resque (1.23.0)
In production I start many workers on some queues by capistrano task (gem capistrano resque). But when I stop them - simply sending kill -s QUIT to all pids in pid-file - processes are not dying. Workers in resque-web deleting, but I can see all the processes by ps aux command.
Database is Oracle so I needed to make initializer with:
```ruby
Rails.configuration.after_initialize do
  Resque.after_fork do
    ActiveRecord::Base.connection.reconnect!
  end
end
```
or I got connection error. So when processes are not dying, connection to database is saved too. That is very bad...
How can I resolve this problem?

**Comment by steveklabnik** [comment]
Can anyone help me reproduce this?

**Comment by steveklabnik** [comment]
Without a way to reproduce this, I will not be able to investigate. If you can come up with one, please let me know, and I would be happy to re-open. Thank you!
