### ISSUE TITLE
Jobs don't enqueue in development

### ISSUE THREAD

**Issue by jayswain** [resque/resque#791]
In development, in the console, when I `Resque.enqueue(VimeoChannelFetchJob, self.id)` , I receive a 'true' response, though when I check Resque.info, I don't see the job marked as pending, working, failed or otherwise. Is this expected behavior?

When running the job the same way on the staging server, I get the desired behavior (I see the job when running Resque.info).

**Comment by juanibiapina** [comment]
I have the same issue without resque-spec.
