### ISSUE TITLE
pid 2519 SIGIOT (signal 6) (core dumped)

### ISSUE THREAD

**Issue by Houdini** [resque/resque#820]
Sorry, but I have no core dump.

With 1.23.0 workers stucks about each 200-400 tasks.
I updated to last master branch, and I start receive errors:

Resque::DirtyExit
Error
pid 2519 SIGIOT (signal 6) (core dumped)

each second task.

**Comment by charliedrage** [comment]
@hoetmaaiers super old github issue, but can confirm that this is fixed in 1.9.3
