### ISSUE TITLE
Reliability of Resque.enqueue call

### ISSUE THREAD

**Issue by davetchen** [resque/resque#840]
We've been working on an application that uses Resque to help us manage starting and stopping AWS instances. Resque has been great to work with but unfortunately, we've had a couple cases where a <code>Resque.enqueue</code> call fails and we then accrue extra costs because EC2 instances are left running.

In this case, the ruby exception returns "Connection timed out". Resque is timing out connecting to our Redis server.

My question is what are the "best practices" for handling this case? Do folks just do a number of retries in a <code>rescue</code> block? Would folks expect this to succeed on the second try -- should I add a sleep between attempts (it's hard to setup test cases for this)?

Our setup is 
- resque 1.23.0
- redis 2.6
- ruby  1.9.3p-125
- rails 3.2.12

The errors do not seem to be related to excessive load, in fact we seem to get more of the Redis "Connection timed out" errors after the system has been sitting quiet for a while. 

Also, are there any special settings that we should look at for the Redis master?   Our <code>redis.conf</code> is pretty vanilla but we are using a master/slave setup.

**Comment by pudgyhedgehog** [comment]
Is this still an issue for anyone else? I'm still seeing `Redis::TimeoutError`s caught in Bugsnag. Is there a more elegant way to solve this other than wrapping all every `Resque.enqueue` call in `begin/rescue` blocks?
