### ISSUE TITLE
ENV['VERBOSE'] logging deprecation

### ISSUE THREAD

**Issue by auxbuss** [resque/resque#866]
I use `ENV['VERBOSE'] = '1' in rake files. Now I see:

```
*** DEPRECATION WARNING: Resque::Worker#verbose and #very_verbose are 
deprecated. Please set Resque.logger.level instead
```

and the task drops into debug mode, which I believe is the old VVERBOSE behaviour, which is inappropriate in this case.

Whatever I set `Resque.logger.level` to doesn't change the logging level. That said, it's also not clear how these should now be set, since this change hasn't been described in the docs.

Just to be clear, I'm not using Rails in this case. I'm simply trying to retain the behaviour of writing messages to STDOUT at the appropriate level.

**Comment by phuongnd08** [comment]
@steveklabnik So before we are supposed to use this to start Resque with verbose logging: `VERBOSE=1 INTERVAL=1 QUEUE=session bundle exec rake resque:work`. Now what shall we use?
