### ISSUE TITLE
Allow different databases for different queues

### ISSUE THREAD

**Issue by emirkin** [resque/resque#883]
It would be really useful to have the ability to assign different DB to different queues. To give you an example, I would like to have a no-security queue to which the general public can post, while other queues are backed by a password-protected DB reserved for purely internal use.

Is something like that possible to do now?

**Comment by chrisccerami** [comment]
@steveklabnik do you still think this is viable/desirable with the cancellation of 2.0?

**Comment by steveklabnik** [comment]
I'm not sure how much work it will be, but it seems like a reasonable feature overall.

**Comment by jeremy** [comment]
Multiple workers would be a reasonable route, but that'd require deeper work. Unlikely considering Resque's stable maintenance state.

If anyone's interested, starting a pull request is the way to go. Closing this feature idea to keep open issues reserved for bugfixes and maintenance.
