### ISSUE TITLE
Backport Resque::Config to 1-x-stable

### ISSUE THREAD

**Issue by tarcieri** [resque/resque#890]
I'd love to use Resque::Config to enable having a .yml file in the new resque-web which has all the setup info.

I see Resque::Config has changed quite a bit from @begriffs original patch (mostly changes by @strzalek). I'm not married to any particular implementation but it would be great if it was available in 1-x-stable as well, as I would like for resque-web to support both 1-x-stable and 2.0

**Comment by steveklabnik** [comment]
Since 2.0 isn't happening, I'm closing this.
