### ISSUE TITLE
Shouldn't 'retry failed jobs' also clear them from the failed queue?

### ISSUE THREAD

**Issue by barmstrong** [resque/resque#924]
We have a large volume of jobs in production, various ones fail sometimes.

After deploying a fix I often find myself clicking "retry failed jobs" but then it reloads the failed jobs page and they are all still there.  So I click "clear failed jobs" as fast as I can.  But this always feels dangerous...

What if one of the ones I just retried failed again in the time between the page loading and clicking "clear failed jobs".  Now I just deleted that job and it will never run.

What if a new failed job (not in the retry list) comes in in the time between clicking those two buttons?  I also just deleted it and it will never get run.

When under load and with thousands of failed jobs, I have sometimes seen it take 5-10 seconds to click those two buttons in quick succession.  So it's conceivable jobs get lost in the middle there.

It seems like it would make more sense to have the "retry failed jobs" button actually retry AND remove them from the failed jobs.  What do you think?

There seem to be some other issues about this where it created confusion:
(duplicates) https://github.com/resque/resque/issues/548
(confusion) https://github.com/resque/resque/issues/489

Thanks!

**Comment by kamok** [comment]
I find this to be a problem for me as well. In Resque, when a job fails, you get a note of it on your Sinatra app. Great. But, when I go in there, hit Retry and works, the job should be removed automatically. Currently I'm having to decide which job I "fixed" and going down the list and removing them manually, which is quite tedious, even if I don't have millions of jobs in the failed queue.
