### ISSUE TITLE
Terrible error message when Redis doesn't exist

### ISSUE THREAD

**Issue by steveklabnik** [resque/resque#932]
When you don't have a Redis running, you get this:

```
:in `job': undefined method `get' for nil:NilClass
```

when you bundle exec resque work

**Comment by RochesterinNYC** [comment]
By `bundle exec resque work`, do you mean `bundle exec rake resque:work`?

**Comment by steveklabnik** [comment]
`resque work` was how 2.0 worked. I should check to see if it's present in 1.x, nice catch.

**Comment by chrisccerami** [comment]
Looks like on `1-x-stable` this problem doesn't exist. Here's the exception when I `bundle exec rake resque:work` on `1-x-stable`:

```
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Original Exception (Redis::CannotConnectError): Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
```
