### ISSUE TITLE
Resque::Failure::Base implements all incorrectly

### ISSUE THREAD

**Issue by dylanlingelbach** [resque/resque#952]
Resque::Failure will call to the backend's base with three arguments (offset, limit, and queue).  However Resque::Failure::Base defines all as only taking two parameters (offset and limit).

This isn't a problem for the Redis backend since it implements all correctly, but it is an issue for Airbrake and other backends that derive from Base and don't reimplement all.

**Comment by Jacobkg** [comment]
@steveklabnik I see that there was a PR merged a couple years ago that may have resolved this issue, is there anything else to investigate? I guess can ask if @dylanlingelbach knows whether this issue is since resolved.

**Comment by steveklabnik** [comment]
Yes, it would seem that this one has been fixed. @dylanahsmith let us know if that's not accurate.

**Comment by dylanahsmith** [comment]
wrong Dylan. @dylanlingelbach can you confirm that this has been fixed?

**Comment by steveklabnik** [comment]
Whoops, sorry :(

**Comment by dylanlingelbach** [comment]
I haven't used Resque since early 2014, but my issue should be resolved with this PR.

I see it was also ported to the 1-x-stable branch so the issue I reported shouldn't be an issue any more.
