### ISSUE TITLE
Investigate dead code

### ISSUE THREAD

**Issue by steveklabnik** [resque/resque#974]
Resque is an old project, and I'm sure there's a bunch of stuff that's not strictly needed anymore. Let's find out what's actually important, and throw out the rest.

This ticket will get closed when at least _someone_ gives it the once-over. I'll probably do this myself before release, too.

**Comment by RochesterinNYC** [comment]
Was this removal/charter into investigating dead code completed or is it an ongoing effort?

**Comment by steveklabnik** [comment]
Given how long it's been, I would say that it's probably still ongoing. We've just restarted Resque development after a really long hibernation period, so I have no idea where this is at today

**Comment by steveklabnik** [comment]
I would still like to see this, but it's not worth keeping an issue open.
